import Foundation

public let nucleusAndroidAppArmorProfileName = "lxc-nucleus-android"

public struct AndroidContainerDevice: Hashable, Sendable {
    public let name: String
    public let source: String
    public let major: UInt32
    public let minor: UInt32

    public init(
        name: String,
        source: String,
        major: UInt32,
        minor: UInt32
    ) {
        self.name = name
        self.source = source
        self.major = major
        self.minor = minor
    }
}

public struct AndroidContainerMountHook: Hashable, Sendable {
    public let executable: String
    public let arguments: [String]

    public init(
        executable: String,
        arguments: [String]
    ) {
        self.executable = executable
        self.arguments = arguments
    }
}

public struct AndroidContainerConfiguration: Hashable, Sendable {
    public let name: String
    public let rootFileSystem: String
    public let seccompProfile: String
    public let kernelLogDevice: String
    public let tombstones: String
    public let gfxstreamSocketDirectory: String
    public let hostKernelConfigurationDirectory: String
    public let hostUIDStart: UInt32
    public let hostGIDStart: UInt32
    public let hostUIDCount: UInt32
    public let hostGIDCount: UInt32
    public let binderDevices: [AndroidContainerDevice]
    public let mountHook: AndroidContainerMountHook

    public init(
        name: String,
        rootFileSystem: String,
        seccompProfile: String,
        kernelLogDevice: String,
        tombstones: String,
        gfxstreamSocketDirectory: String,
        hostKernelConfigurationDirectory: String,
        hostUIDStart: UInt32,
        hostGIDStart: UInt32,
        hostUIDCount: UInt32,
        hostGIDCount: UInt32,
        binderDevices: [AndroidContainerDevice],
        mountHook: AndroidContainerMountHook
    ) {
        self.name = name
        self.rootFileSystem = rootFileSystem
        self.seccompProfile = seccompProfile
        self.kernelLogDevice = kernelLogDevice
        self.tombstones = tombstones
        self.gfxstreamSocketDirectory = gfxstreamSocketDirectory
        self.hostKernelConfigurationDirectory =
            hostKernelConfigurationDirectory
        self.hostUIDStart = hostUIDStart
        self.hostGIDStart = hostGIDStart
        self.hostUIDCount = hostUIDCount
        self.hostGIDCount = hostGIDCount
        self.binderDevices = binderDevices
        self.mountHook = mountHook
    }

    public func lxcConfiguration() throws -> String {
        try validate()
        var lines = [
            "# Generated by NucleusAndroidContainerContract.",
            "lxc.uts.name = \(name)",
            "lxc.arch = x86_64",
            "lxc.rootfs.path = dir:\(rootFileSystem)",
            "lxc.rootfs.managed = 0",
            "lxc.rootfs.options = rw,idmap=container",
            "lxc.init.cmd = /system/bin/init nucleus_container",
            "lxc.init.cwd = /",
            "lxc.signal.halt = SIGTERM",
            "lxc.signal.reboot = SIGINT",
            "lxc.signal.stop = SIGKILL",
            "lxc.idmap = u 0 \(hostUIDStart) \(hostUIDCount)",
            "lxc.idmap = g 0 \(hostGIDStart) \(hostGIDCount)",
            "lxc.namespace.clone = cgroup ipc mnt net pid time user uts",
            "lxc.hook.version = 1",
            "lxc.hook.mount = "
                + ([mountHook.executable] + mountHook.arguments)
                .joined(separator: " "),
            "lxc.net.0.type = empty",
            "lxc.mount.auto = proc:rw sys:ro cgroup:rw",
            "lxc.autodev = 0",
            "lxc.pty.max = 1024",
            "lxc.console.path = none",
            // Android early-init raises RLIMIT_NICE to 40 before dropping
            // privileges. The container manager must establish that hard
            // limit because an unprivileged user namespace cannot raise the
            // host-inherited ceiling itself.
            "lxc.prlimit.nice = 40",
            // Android init must retain every capability requested by a
            // service in the product, plus SETPCAP to establish those
            // service-specific sets. LXC drops everything not named here.
            "lxc.cap.keep = audit_control block_suspend bpf chown dac_override "
                + "dac_read_search fowner fsetid ipc_lock kill mknod "
                + "net_admin net_bind_service net_raw perfmon setgid "
                + "setpcap setuid sys_admin sys_chroot sys_nice sys_ptrace "
                + "sys_resource syslog wake_alarm",
            "lxc.seccomp.profile = \(seccompProfile)",
            "lxc.apparmor.profile = \(nucleusAndroidAppArmorProfileName)",
            "lxc.cgroup.relative = 1",
            "lxc.cgroup2.devices.deny = a",
            "lxc.cgroup2.devices.allow = c 1:3 rwm",
            "lxc.cgroup2.devices.allow = c 1:5 rwm",
            "lxc.cgroup2.devices.allow = c 1:7 rwm",
            "lxc.cgroup2.devices.allow = c 1:8 rwm",
            "lxc.cgroup2.devices.allow = c 1:9 rwm",
            "lxc.cgroup2.devices.allow = c 5:2 rwm",
            "lxc.cgroup2.devices.allow = c 136:* rwm",
            "lxc.mount.entry = tmpfs dev tmpfs rw,nosuid,noexec,mode=0755,create=dir 0 0",
            "lxc.mount.entry = /dev/null dev/null none bind,create=file 0 0",
            "lxc.mount.entry = /dev/zero dev/zero none bind,create=file 0 0",
            "lxc.mount.entry = /dev/full dev/full none bind,create=file 0 0",
            "lxc.mount.entry = /dev/random dev/random none bind,create=file 0 0",
            "lxc.mount.entry = /dev/urandom dev/urandom none bind,create=file 0 0",
            "lxc.mount.entry = \(kernelLogDevice) dev/kmsg none bind,create=file 0 0",
            "lxc.mount.entry = \(kernelLogDevice) dev/kmsg_debug none bind,create=file 0 0",
            "lxc.mount.entry = \(gfxstreamSocketDirectory) dev/nucleus none bind,ro,create=dir 0 0",
            "lxc.mount.entry = tmpfs data tmpfs rw,nosuid,nodev,mode=0771,create=dir 0 0",
            "lxc.mount.entry = \(tombstones) data/tombstones none bind,create=dir 0 0",
            "lxc.mount.entry = tmpfs metadata tmpfs rw,nosuid,nodev,noexec,mode=0755,create=dir 0 0",
            "lxc.mount.entry = \(hostKernelConfigurationDirectory) metadata/nucleus none bind,ro,create=dir 0 0",
            "lxc.mount.entry = tmpfs mnt tmpfs rw,nosuid,nodev,noexec,mode=0755,create=dir 0 0",
            "lxc.mount.entry = tmpfs linkerconfig tmpfs rw,nosuid,nodev,noexec,mode=0755,create=dir 0 0",
            "lxc.mount.entry = tmpfs storage tmpfs rw,nosuid,nodev,noexec,mode=0755,create=dir 0 0",
        ]
        for device in binderDevices.sorted(by: { $0.name < $1.name }) {
            lines.append(
                "lxc.cgroup2.devices.allow = c "
                    + "\(device.major):\(device.minor) rwm")
            lines.append(
                "lxc.mount.entry = \(device.source) dev/\(device.name) "
                    + "none bind,create=file 0 0")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private func validate() throws {
        guard isValidName(name) else {
            throw AndroidContainerConfigurationError.invalidName(name)
        }
        try validateAbsolutePath(rootFileSystem, field: "rootFileSystem")
        try validateAbsolutePath(seccompProfile, field: "seccompProfile")
        try validateAbsolutePath(kernelLogDevice, field: "kernelLogDevice")
        try validateAbsolutePath(tombstones, field: "tombstones")
        try validateAbsolutePath(
            gfxstreamSocketDirectory,
            field: "gfxstreamSocketDirectory")
        try validateAbsolutePath(
            hostKernelConfigurationDirectory,
            field: "hostKernelConfigurationDirectory")
        try validateAbsolutePath(
            mountHook.executable,
            field: "mountHook.executable")
        guard !mountHook.arguments.isEmpty,
            mountHook.arguments.allSatisfy(isSafeScalar)
        else {
            throw AndroidContainerConfigurationError.invalidMountHook
        }
        guard hostUIDStart > 0,
            hostGIDStart > 0,
            hostUIDCount > 0,
            hostGIDCount > 0,
            UInt64(hostUIDStart) + UInt64(hostUIDCount)
                <= UInt64(UInt32.max) + 1,
            UInt64(hostGIDStart) + UInt64(hostGIDCount)
                <= UInt64(UInt32.max) + 1
        else {
            throw AndroidContainerConfigurationError.invalidIDMap(
                uidStart: hostUIDStart,
                gidStart: hostGIDStart,
                uidCount: hostUIDCount,
                gidCount: hostGIDCount)
        }
        let expectedNames = ["binder", "hwbinder", "vndbinder"]
        let names = binderDevices.map(\.name).sorted()
        guard names == expectedNames else {
            throw AndroidContainerConfigurationError.invalidBinderDevices(
                names)
        }
        for device in binderDevices {
            try validateAbsolutePath(
                device.source,
                field: "\(device.name).source")
            guard device.major > 0 else {
                throw AndroidContainerConfigurationError.invalidBinderDevice(
                    device.name)
            }
        }
    }
}

public enum AndroidContainerConfigurationError: Error, Equatable {
    case invalidName(String)
    case invalidPath(field: String, value: String)
    case invalidIDMap(
        uidStart: UInt32,
        gidStart: UInt32,
        uidCount: UInt32,
        gidCount: UInt32)
    case invalidBinderDevices([String])
    case invalidBinderDevice(String)
    case invalidMountHook
}

private func isValidName(_ value: String) -> Bool {
    guard let first = value.first,
        first.isLowercase || first.isNumber
    else {
        return false
    }
    return value.allSatisfy {
        $0.isLowercase || $0.isNumber || $0 == "-"
    }
}

private func validateAbsolutePath(
    _ value: String,
    field: String
) throws {
    guard value.hasPrefix("/"),
        value != "/",
        isSafeScalar(value),
        !value.split(separator: "/").contains("..")
    else {
        throw AndroidContainerConfigurationError.invalidPath(
            field: field,
            value: value)
    }
}

private func isSafeScalar(_ value: String) -> Bool {
    !value.isEmpty
        && value.allSatisfy {
            !$0.isWhitespace && !$0.isNewline && $0 != "#"
        }
}
