FROM docker.io/library/ubuntu:26.04@sha256:3131b4cc82a783df6c9df078f86e01819a13594b865c2cad47bd1bca2b7063bb

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        clang \
        clang-tools \
        coreutils \
        curl \
        git \
        libblocksruntime-dev \
        libarchive-tools \
        libbsd-dev \
        libcurl4-openssl-dev \
        libedit-dev \
        libffi-dev \
        libicu-dev \
        libncurses-dev \
        libpython3-dev \
        libsqlite3-dev \
        libssl-dev \
        libxml2-dev \
        libzstd-dev \
        lld \
        ninja-build \
        patch \
        patchelf \
        pkg-config \
        python3 \
        rsync \
        unzip \
        util-linux \
        uuid-dev \
        zlib1g-dev \
    && pkg-config --exists libcurl \
    && curl --fail --location --output /tmp/android-ndk.zip \
        https://dl.google.com/android/repository/android-ndk-r30-beta2-linux.zip \
    && echo '069427047d18cc6e44369cd7b8e711bfc2c7a3b5  /tmp/android-ndk.zip' \
        | sha1sum --check --strict \
    && unzip -q /tmp/android-ndk.zip -d /opt \
    && rm -f /tmp/android-ndk.zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl --fail --location --output /tmp/cmake.tar.gz \
        https://github.com/Kitware/CMake/releases/download/v3.30.2/cmake-3.30.2-linux-x86_64.tar.gz \
    && echo 'cdd7fb352605cee3ae53b0e18b5929b642900e33d6b0173e19f6d4f2067ebf16  /tmp/cmake.tar.gz' \
        | sha256sum --check --strict \
    && mkdir -p /opt/cmake \
    && bsdtar --extract --gzip \
        --file /tmp/cmake.tar.gz \
        --directory /opt/cmake \
        --strip-components=1 \
    && rm -f /tmp/cmake.tar.gz \
    && /opt/cmake/bin/cmake --version \
        | grep --fixed-strings 'cmake version 3.30.2'

RUN curl --fail --location --output /tmp/swift-bootstrap.tar.gz \
        https://download.swift.org/swift-6.4.x-branch/ubuntu2404/swift-6.4.x-DEVELOPMENT-SNAPSHOT-2026-07-23-a/swift-6.4.x-DEVELOPMENT-SNAPSHOT-2026-07-23-a-ubuntu24.04.tar.gz \
    && echo '05670a1487e907e732ca701bfda153e5f02aeac801dd3b07686f2aae4e0c6ad5  /tmp/swift-bootstrap.tar.gz' \
        | sha256sum --check --strict \
    && mkdir -p /opt/swift-bootstrap \
    && bsdtar --extract --gzip \
        --file /tmp/swift-bootstrap.tar.gz \
        --directory /opt/swift-bootstrap \
        --strip-components=1 \
    && rm -f /tmp/swift-bootstrap.tar.gz

RUN usermod \
        --login nucleus-build \
        --home /home/nucleus-build \
        --move-home \
        --shell /bin/bash \
        ubuntu \
    && groupmod --new-name nucleus-build ubuntu \
    && usermod \
        --groups '' \
        --comment 'Nucleus Swift Build' \
        nucleus-build

COPY --chmod=0755 entrypoint.sh /usr/local/bin/nucleus-swift-build

USER nucleus-build
WORKDIR /src

ENV ANDROID_NDK_HOME=/opt/android-ndk-r30-beta2 \
    CCACHE_COMPILERCHECK=content \
    HOME=/home/nucleus-build \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=/opt/cmake/bin:/opt/swift-bootstrap/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    SWIFTC=/opt/swift-bootstrap/usr/bin/swiftc \
    TZ=UTC

ENTRYPOINT ["/usr/local/bin/nucleus-swift-build"]
