// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for ext_data_control_source_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ExtDataControlSourceV1Requests: AnyObject {
    func offer(_ resource: UnsafeMutablePointer<wl_resource>, mime_type: UnsafePointer<CChar>?)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ExtDataControlSourceV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ExtDataControlSourceV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_data_control_source_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_data_control_source_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_ext_data_control_source_v1_requests.self, capacity: 1)
        vt.pointee.offer = offer_impl
        vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendSend(_ target: UnsafeMutablePointer<wl_resource>, mime_type: UnsafePointer<CChar>?, fd: Int32) {
        ext_data_control_source_v1_send_send(target, mime_type, fd)
    }
    public static func sendCancelled(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_data_control_source_v1_send_cancelled(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ExtDataControlSourceV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ExtDataControlSourceV1Requests
    }

    private static let offer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, mime_type in
        guard let res, let h = handler(res) else { return }
        h.offer(res, mime_type: mime_type)
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
}
