// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for ext_foreign_toplevel_handle_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ExtForeignToplevelHandleV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ExtForeignToplevelHandleV1Server>)
}
public extension ExtForeignToplevelHandleV1Requests {
    func destroy(_ request: WaylandRequest<ExtForeignToplevelHandleV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ExtForeignToplevelHandleV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_ext_foreign_toplevel_handle_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_foreign_toplevel_handle_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_foreign_toplevel_handle_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_ext_foreign_toplevel_handle_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendClosed(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe ext_foreign_toplevel_handle_v1_send_closed(target)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe ext_foreign_toplevel_handle_v1_send_done(target)
    }
    public static func sendTitle(_ target: UnsafeMutablePointer<wl_resource>, title: UnsafePointer<CChar>?) {
        unsafe ext_foreign_toplevel_handle_v1_send_title(target, title)
    }
    public static func sendAppId(_ target: UnsafeMutablePointer<wl_resource>, app_id: UnsafePointer<CChar>?) {
        unsafe ext_foreign_toplevel_handle_v1_send_app_id(target, app_id)
    }
    public static func sendIdentifier(_ target: UnsafeMutablePointer<wl_resource>, identifier: UnsafePointer<CChar>?) {
        unsafe ext_foreign_toplevel_handle_v1_send_identifier(target, identifier)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ExtForeignToplevelHandleV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtForeignToplevelHandleV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ExtForeignToplevelHandleV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ExtForeignToplevelHandleV1Server {
    @discardableResult
    func sendClosed() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_foreign_toplevel_handle_v1_send_closed(target)
        return true
    }
    @discardableResult
    func sendDone() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_foreign_toplevel_handle_v1_send_done(target)
        return true
    }
    @discardableResult
    func sendTitle(title: String) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        return unsafe withWaylandEventCString(title) { _event_titleCString in
            unsafe ext_foreign_toplevel_handle_v1_send_title(target, _event_titleCString)
            return true
        }
    }
    @discardableResult
    func sendAppId(app_id: String) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        return unsafe withWaylandEventCString(app_id) { _event_app_idCString in
            unsafe ext_foreign_toplevel_handle_v1_send_app_id(target, _event_app_idCString)
            return true
        }
    }
    @discardableResult
    func sendIdentifier(identifier: String) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        return unsafe withWaylandEventCString(identifier) { _event_identifierCString in
            unsafe ext_foreign_toplevel_handle_v1_send_identifier(target, _event_identifierCString)
            return true
        }
    }
}
public extension WlNewId where Interface == ExtForeignToplevelHandleV1Server {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<ExtForeignToplevelHandleV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ExtForeignToplevelHandleV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ExtForeignToplevelHandleV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ExtForeignToplevelHandleV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ExtForeignToplevelHandleV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ExtForeignToplevelHandleV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ExtForeignToplevelHandleV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ExtForeignToplevelHandleV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}