// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for ext_image_copy_capture_cursor_session_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ExtImageCopyCaptureCursorSessionV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func getCaptureSession(_ resource: UnsafeMutablePointer<wl_resource>, session: WlNewId)
}

public extension ExtImageCopyCaptureCursorSessionV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ExtImageCopyCaptureCursorSessionV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_image_copy_capture_cursor_session_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_image_copy_capture_cursor_session_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_ext_image_copy_capture_cursor_session_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.get_capture_session = getCaptureSession_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendEnter(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_image_copy_capture_cursor_session_v1_send_enter(target)
    }
    public static func sendLeave(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_image_copy_capture_cursor_session_v1_send_leave(target)
    }
    public static func sendPosition(_ target: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32) {
        ext_image_copy_capture_cursor_session_v1_send_position(target, x, y)
    }
    public static func sendHotspot(_ target: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32) {
        ext_image_copy_capture_cursor_session_v1_send_hotspot(target, x, y)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ExtImageCopyCaptureCursorSessionV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtImageCopyCaptureCursorSessionV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let getCaptureSession_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, session in
        guard let res, let client, let h = handler(res) else { return }
        h.getCaptureSession(res, session: WlNewId(client: client, id: session, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_ext_image_copy_capture_session_v1()))
    }
}
