// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for ext_image_copy_capture_session_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ExtImageCopyCaptureSessionV1Requests: AnyObject {
    func createFrame(_ resource: UnsafeMutablePointer<wl_resource>, frame: WlNewId)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ExtImageCopyCaptureSessionV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ExtImageCopyCaptureSessionV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_image_copy_capture_session_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_image_copy_capture_session_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_ext_image_copy_capture_session_v1_requests.self, capacity: 1)
        vt.pointee.create_frame = createFrame_impl
        vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendBufferSize(_ target: UnsafeMutablePointer<wl_resource>, width: UInt32, height: UInt32) {
        ext_image_copy_capture_session_v1_send_buffer_size(target, width, height)
    }
    public static func sendShmFormat(_ target: UnsafeMutablePointer<wl_resource>, format: UInt32) {
        ext_image_copy_capture_session_v1_send_shm_format(target, format)
    }
    public static func sendDmabufDevice(_ target: UnsafeMutablePointer<wl_resource>, device: UnsafeMutablePointer<wl_array>?) {
        ext_image_copy_capture_session_v1_send_dmabuf_device(target, device)
    }
    public static func sendDmabufFormat(_ target: UnsafeMutablePointer<wl_resource>, format: UInt32, modifiers: UnsafeMutablePointer<wl_array>?) {
        ext_image_copy_capture_session_v1_send_dmabuf_format(target, format, modifiers)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_image_copy_capture_session_v1_send_done(target)
    }
    public static func sendStopped(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_image_copy_capture_session_v1_send_stopped(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ExtImageCopyCaptureSessionV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtImageCopyCaptureSessionV1Requests
    }

    private static let createFrame_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, frame in
        guard let res, let client, let h = handler(res) else { return }
        h.createFrame(res, frame: WlNewId(client: client, id: frame, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_ext_image_copy_capture_frame_v1()))
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
}
