// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for ext_idle_notifier_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ExtIdleNotifierV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func getIdleNotification(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, timeout: UInt32, seat: UnsafeMutablePointer<wl_resource>?)
    func getInputIdleNotification(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, timeout: UInt32, seat: UnsafeMutablePointer<wl_resource>?)
}

public extension ExtIdleNotifierV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ExtIdleNotifierV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_idle_notifier_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_idle_notifier_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_ext_idle_notifier_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.get_idle_notification = getIdleNotification_impl
        vt.pointee.get_input_idle_notification = getInputIdleNotification_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ExtIdleNotifierV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtIdleNotifierV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let getIdleNotification_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, timeout, seat in
        guard let res, let client, let h = handler(res) else { return }
        h.getIdleNotification(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(2)), interface: swift_wayland_iface_ext_idle_notification_v1()), timeout: timeout, seat: seat)
    }
    private static let getInputIdleNotification_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, timeout, seat in
        guard let res, let client, let h = handler(res) else { return }
        h.getInputIdleNotification(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(2)), interface: swift_wayland_iface_ext_idle_notification_v1()), timeout: timeout, seat: seat)
    }
}
