// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for ext_session_lock_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ExtSessionLockV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func getLockSurface(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, surface: UnsafeMutablePointer<wl_resource>?, output: UnsafeMutablePointer<wl_resource>?)
    func unlockAndDestroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ExtSessionLockV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
    func unlockAndDestroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ExtSessionLockV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_session_lock_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_session_lock_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_ext_session_lock_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.get_lock_surface = getLockSurface_impl
        vt.pointee.unlock_and_destroy = unlockAndDestroy_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendLocked(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_session_lock_v1_send_locked(target)
    }
    public static func sendFinished(_ target: UnsafeMutablePointer<wl_resource>) {
        ext_session_lock_v1_send_finished(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ExtSessionLockV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ExtSessionLockV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let getLockSurface_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface, output in
        guard let res, let client, let h = handler(res) else { return }
        h.getLockSurface(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_ext_session_lock_surface_v1()), surface: surface, output: output)
    }
    private static let unlockAndDestroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.unlockAndDestroy(res) } else { wl_resource_destroy(res) }
    }
}
