// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for ext_workspace_group_handle_v1.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol ExtWorkspaceGroupHandleV1Requests: AnyObject {
    func createWorkspace(_ request: WaylandRequest<ExtWorkspaceGroupHandleV1Server>, workspace: String)
    func destroy(_ request: WaylandRequest<ExtWorkspaceGroupHandleV1Server>)
}
public extension ExtWorkspaceGroupHandleV1Requests {
    func destroy(_ request: WaylandRequest<ExtWorkspaceGroupHandleV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ExtWorkspaceGroupHandleV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_ext_workspace_group_handle_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_workspace_group_handle_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_workspace_group_handle_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_ext_workspace_group_handle_v1_requests.self, capacity: 1)
        unsafe vt.pointee.create_workspace = createWorkspace_impl
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendCapabilities(_ target: UnsafeMutablePointer<wl_resource>, capabilities: ExtWorkspaceGroupHandleV1GroupCapabilities) {
        unsafe ext_workspace_group_handle_v1_send_capabilities(target, capabilities.rawValue)
    }
    public static func sendOutputEnter(_ target: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_group_handle_v1_send_output_enter(target, output)
    }
    public static func sendOutputLeave(_ target: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_group_handle_v1_send_output_leave(target, output)
    }
    public static func sendWorkspaceEnter(_ target: UnsafeMutablePointer<wl_resource>, workspace: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_group_handle_v1_send_workspace_enter(target, workspace)
    }
    public static func sendWorkspaceLeave(_ target: UnsafeMutablePointer<wl_resource>, workspace: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_group_handle_v1_send_workspace_leave(target, workspace)
    }
    public static func sendRemoved(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe ext_workspace_group_handle_v1_send_removed(target)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ExtWorkspaceGroupHandleV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtWorkspaceGroupHandleV1Requests
    }
    private static let createWorkspace_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, workspace in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_workspace = unsafe workspace
        MainActor.assumeIsolated {
            unsafe requestHandler.createWorkspace(WaylandRequest<ExtWorkspaceGroupHandleV1Server>(requestResource), workspace: unsafe String(cString: _request_workspace!))
        }
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ExtWorkspaceGroupHandleV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ExtWorkspaceGroupHandleV1Server {
    @discardableResult
    func sendCapabilities(capabilities: ExtWorkspaceGroupHandleV1GroupCapabilities) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_capabilities(target, capabilities.rawValue)
        return true
    }
    @discardableResult
    func sendOutputEnter(output: WaylandResourceHandle<WlOutputServer>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_outputResource = unsafe output.resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_output_enter(target, _event_outputResource)
        return true
    }
    @discardableResult
    func sendOutputLeave(output: WaylandResourceHandle<WlOutputServer>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_outputResource = unsafe output.resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_output_leave(target, _event_outputResource)
        return true
    }
    @discardableResult
    func sendWorkspaceEnter(workspace: WaylandResourceHandle<ExtWorkspaceHandleV1Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_workspaceResource = unsafe workspace.resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_workspace_enter(target, _event_workspaceResource)
        return true
    }
    @discardableResult
    func sendWorkspaceLeave(workspace: WaylandResourceHandle<ExtWorkspaceHandleV1Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_workspaceResource = unsafe workspace.resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_workspace_leave(target, _event_workspaceResource)
        return true
    }
    @discardableResult
    func sendRemoved() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_workspace_group_handle_v1_send_removed(target)
        return true
    }
}
public extension WlNewId where Interface == ExtWorkspaceGroupHandleV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ExtWorkspaceGroupHandleV1Requests>(
        owner: (WaylandResourceHandle<ExtWorkspaceGroupHandleV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ExtWorkspaceGroupHandleV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ExtWorkspaceGroupHandleV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ExtWorkspaceGroupHandleV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ExtWorkspaceGroupHandleV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ExtWorkspaceGroupHandleV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ExtWorkspaceGroupHandleV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ExtWorkspaceGroupHandleV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ExtWorkspaceGroupHandleV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ExtWorkspaceGroupHandleV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}