// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for ext_workspace_manager_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ExtWorkspaceManagerV1Requests: AnyObject {
    func commit(_ request: WaylandRequest<ExtWorkspaceManagerV1Server>)
    func stop(_ request: WaylandRequest<ExtWorkspaceManagerV1Server>)
}
public enum ExtWorkspaceManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_ext_workspace_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_ext_workspace_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_ext_workspace_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_ext_workspace_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.commit = commit_impl
        unsafe vt.pointee.stop = stop_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendWorkspaceGroup(_ target: UnsafeMutablePointer<wl_resource>, workspace_group: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_manager_v1_send_workspace_group(target, workspace_group)
    }
    public static func sendWorkspace(_ target: UnsafeMutablePointer<wl_resource>, workspace: UnsafeMutablePointer<wl_resource>?) {
        unsafe ext_workspace_manager_v1_send_workspace(target, workspace)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe ext_workspace_manager_v1_send_done(target)
    }
    public static func sendFinished(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe ext_workspace_manager_v1_send_finished(target)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ExtWorkspaceManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ExtWorkspaceManagerV1Requests
    }
    private static let commit_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.commit(WaylandRequest<ExtWorkspaceManagerV1Server>(requestResource))
        }
    }
    private static let stop_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.stop(WaylandRequest<ExtWorkspaceManagerV1Server>(requestResource))
        }
    }
}
public extension WaylandResourceHandle where Interface == ExtWorkspaceManagerV1Server {
    @discardableResult
    func sendWorkspaceGroup(workspace_group: WaylandResourceHandle<ExtWorkspaceGroupHandleV1Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_workspace_groupResource = unsafe workspace_group.resource else {
            return false
        }
        unsafe ext_workspace_manager_v1_send_workspace_group(target, _event_workspace_groupResource)
        return true
    }
    @discardableResult
    func sendWorkspace(workspace: WaylandResourceHandle<ExtWorkspaceHandleV1Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_workspaceResource = unsafe workspace.resource else {
            return false
        }
        unsafe ext_workspace_manager_v1_send_workspace(target, _event_workspaceResource)
        return true
    }
    @discardableResult
    func sendDone() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_workspace_manager_v1_send_done(target)
        return true
    }
    @discardableResult
    func sendFinished() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe ext_workspace_manager_v1_send_finished(target)
        return true
    }
}
public extension WlNewId where Interface == ExtWorkspaceManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ExtWorkspaceManagerV1Requests>(
        owner: (WaylandResourceHandle<ExtWorkspaceManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ExtWorkspaceManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ExtWorkspaceManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ExtWorkspaceManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ExtWorkspaceManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ExtWorkspaceManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ExtWorkspaceManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ExtWorkspaceManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ExtWorkspaceManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ExtWorkspaceManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}