// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for org_kde_kwin_appmenu: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol OrgKdeKwinAppmenuRequests: AnyObject {
    func setAddress(_ resource: UnsafeMutablePointer<wl_resource>, service_name: UnsafePointer<CChar>?, object_path: UnsafePointer<CChar>?)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension OrgKdeKwinAppmenuRequests {
    func release(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum OrgKdeKwinAppmenuServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_org_kde_kwin_appmenu_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_org_kde_kwin_appmenu_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_org_kde_kwin_appmenu_requests.self, capacity: 1)
        vt.pointee.set_address = setAddress_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> OrgKdeKwinAppmenuRequests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? OrgKdeKwinAppmenuRequests
    }

    private static let setAddress_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?, UnsafePointer<CChar>?) -> Void = { _, res, service_name, object_path in
        guard let res, let h = handler(res) else { return }
        h.setAddress(res, service_name: service_name, object_path: object_path)
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.release(res) } else { wl_resource_destroy(res) }
    }
}
