// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for org_kde_kwin_blur_manager.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol OrgKdeKwinBlurManagerRequests: AnyObject {
    func create(_ request: WaylandRequest<OrgKdeKwinBlurManagerServer>, id: WlNewId<OrgKdeKwinBlurServer>, surface: WaylandBorrowedObject<WlSurfaceServer>)
    func unset(_ request: WaylandRequest<OrgKdeKwinBlurManagerServer>, surface: WaylandBorrowedObject<WlSurfaceServer>)
}
public enum OrgKdeKwinBlurManagerServer: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_org_kde_kwin_blur_manager()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_org_kde_kwin_blur_manager_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_org_kde_kwin_blur_manager_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_org_kde_kwin_blur_manager_requests.self, capacity: 1)
        unsafe vt.pointee.create = create_impl
        unsafe vt.pointee.unset = unset_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any OrgKdeKwinBlurManagerRequests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any OrgKdeKwinBlurManagerRequests
    }
    private static let create_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.create(WaylandRequest<OrgKdeKwinBlurManagerServer>(requestResource), id: WlNewId<OrgKdeKwinBlurServer>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!))
        }
    }
    private static let unset_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, surface in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.unset(WaylandRequest<OrgKdeKwinBlurManagerServer>(requestResource), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!))
        }
    }
}
public extension WlNewId where Interface == OrgKdeKwinBlurManagerServer {
    @discardableResult
    @MainActor
    func create<Owner: OrgKdeKwinBlurManagerRequests>(
        owner: (WaylandResourceHandle<OrgKdeKwinBlurManagerServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: OrgKdeKwinBlurManagerServer.requestVtable(), owner: owner, installed: installed)
    }
}
public extension OrgKdeKwinBlurManagerServer {
    @discardableResult
    @MainActor
    static func createResource<Owner: OrgKdeKwinBlurManagerRequests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<OrgKdeKwinBlurManagerServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: OrgKdeKwinBlurManagerServer.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: OrgKdeKwinBlurManagerRequests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<OrgKdeKwinBlurManagerServer>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<OrgKdeKwinBlurManagerServer>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<OrgKdeKwinBlurManagerServer> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}