// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for org_kde_kwin_blur: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol OrgKdeKwinBlurRequests: AnyObject {
    func commit(_ resource: UnsafeMutablePointer<wl_resource>)
    func setRegion(_ resource: UnsafeMutablePointer<wl_resource>, region: UnsafeMutablePointer<wl_resource>?)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension OrgKdeKwinBlurRequests {
    func release(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum OrgKdeKwinBlurServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_org_kde_kwin_blur_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_org_kde_kwin_blur_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_org_kde_kwin_blur_requests.self, capacity: 1)
        vt.pointee.commit = commit_impl
        vt.pointee.set_region = setRegion_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> OrgKdeKwinBlurRequests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? OrgKdeKwinBlurRequests
    }

    private static let commit_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.commit(res)
    }
    private static let setRegion_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, region in
        guard let res, let h = handler(res) else { return }
        h.setRegion(res, region: region)
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.release(res) } else { wl_resource_destroy(res) }
    }
}
