// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for org_kde_kwin_appmenu_manager.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol OrgKdeKwinAppmenuManagerRequests: AnyObject {
    func create(_ request: WaylandRequest<OrgKdeKwinAppmenuManagerServer>, id: WlNewId<OrgKdeKwinAppmenuServer>, surface: WaylandBorrowedObject<WlSurfaceServer>)
    func release(_ request: WaylandRequest<OrgKdeKwinAppmenuManagerServer>)
}
public extension OrgKdeKwinAppmenuManagerRequests {
    func release(_ request: WaylandRequest<OrgKdeKwinAppmenuManagerServer>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum OrgKdeKwinAppmenuManagerServer: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_org_kde_kwin_appmenu_manager()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_org_kde_kwin_appmenu_manager_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_org_kde_kwin_appmenu_manager_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_org_kde_kwin_appmenu_manager_requests.self, capacity: 1)
        unsafe vt.pointee.create = create_impl
        unsafe vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any OrgKdeKwinAppmenuManagerRequests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any OrgKdeKwinAppmenuManagerRequests
    }
    private static let create_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.create(WaylandRequest<OrgKdeKwinAppmenuManagerServer>(requestResource), id: WlNewId<OrgKdeKwinAppmenuServer>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(2))), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!))
        }
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.release(WaylandRequest<OrgKdeKwinAppmenuManagerServer>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WlNewId where Interface == OrgKdeKwinAppmenuManagerServer {
    @discardableResult
    @MainActor
    func create<Owner: OrgKdeKwinAppmenuManagerRequests>(
        owner: (WaylandResourceHandle<OrgKdeKwinAppmenuManagerServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: OrgKdeKwinAppmenuManagerServer.requestVtable(), owner: owner, installed: installed)
    }
}
public extension OrgKdeKwinAppmenuManagerServer {
    @discardableResult
    @MainActor
    static func createResource<Owner: OrgKdeKwinAppmenuManagerRequests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<OrgKdeKwinAppmenuManagerServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: OrgKdeKwinAppmenuManagerServer.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: OrgKdeKwinAppmenuManagerRequests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<OrgKdeKwinAppmenuManagerServer>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<OrgKdeKwinAppmenuManagerServer>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<OrgKdeKwinAppmenuManagerServer> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}