// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_data_device_manager: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WlDataDeviceManagerRequests: AnyObject {
    func createDataSource(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func getDataDevice(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, seat: UnsafeMutablePointer<wl_resource>?)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension WlDataDeviceManagerRequests {
    func release(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlDataDeviceManagerServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_data_device_manager_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_data_device_manager_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_data_device_manager_requests.self, capacity: 1)
        vt.pointee.create_data_source = createDataSource_impl
        vt.pointee.get_data_device = getDataDevice_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WlDataDeviceManagerRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlDataDeviceManagerRequests
    }

    private static let createDataSource_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.createDataSource(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(4)), interface: swift_wayland_iface_wl_data_source()))
    }
    private static let getDataDevice_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, seat in
        guard let res, let client, let h = handler(res) else { return }
        h.getDataDevice(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(4)), interface: swift_wayland_iface_wl_data_device()), seat: seat)
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.release(res) } else { wl_resource_destroy(res) }
    }
}
