// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_pointer: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WlPointerRequests: AnyObject {
    func setCursor(_ resource: UnsafeMutablePointer<wl_resource>, serial: UInt32, surface: UnsafeMutablePointer<wl_resource>?, hotspot_x: Int32, hotspot_y: Int32)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension WlPointerRequests {
    func release(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlPointerServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_pointer_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_pointer_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_pointer_requests.self, capacity: 1)
        vt.pointee.set_cursor = setCursor_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendEnter(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32, surface: UnsafeMutablePointer<wl_resource>?, surface_x: Double, surface_y: Double) {
        wl_pointer_send_enter(target, serial, surface, swift_wayland_fixed_from_double(surface_x), swift_wayland_fixed_from_double(surface_y))
    }
    public static func sendLeave(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32, surface: UnsafeMutablePointer<wl_resource>?) {
        wl_pointer_send_leave(target, serial, surface)
    }
    public static func sendMotion(_ target: UnsafeMutablePointer<wl_resource>, time: UInt32, surface_x: Double, surface_y: Double) {
        wl_pointer_send_motion(target, time, swift_wayland_fixed_from_double(surface_x), swift_wayland_fixed_from_double(surface_y))
    }
    public static func sendButton(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32, time: UInt32, button: UInt32, state: UInt32) {
        wl_pointer_send_button(target, serial, time, button, state)
    }
    public static func sendAxis(_ target: UnsafeMutablePointer<wl_resource>, time: UInt32, axis: UInt32, value: Double) {
        wl_pointer_send_axis(target, time, axis, swift_wayland_fixed_from_double(value))
    }
    public static func sendFrame(_ target: UnsafeMutablePointer<wl_resource>) {
        wl_pointer_send_frame(target)
    }
    public static func sendAxisSource(_ target: UnsafeMutablePointer<wl_resource>, axis_source: UInt32) {
        wl_pointer_send_axis_source(target, axis_source)
    }
    public static func sendAxisStop(_ target: UnsafeMutablePointer<wl_resource>, time: UInt32, axis: UInt32) {
        wl_pointer_send_axis_stop(target, time, axis)
    }
    public static func sendAxisDiscrete(_ target: UnsafeMutablePointer<wl_resource>, axis: UInt32, discrete: Int32) {
        wl_pointer_send_axis_discrete(target, axis, discrete)
    }
    public static func sendAxisValue120(_ target: UnsafeMutablePointer<wl_resource>, axis: UInt32, value120: Int32) {
        wl_pointer_send_axis_value120(target, axis, value120)
    }
    public static func sendAxisRelativeDirection(_ target: UnsafeMutablePointer<wl_resource>, axis: UInt32, direction: UInt32) {
        wl_pointer_send_axis_relative_direction(target, axis, direction)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WlPointerRequests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WlPointerRequests
    }

    private static let setCursor_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, serial, surface, hotspot_x, hotspot_y in
        guard let res, let h = handler(res) else { return }
        h.setCursor(res, serial: serial, surface: surface, hotspot_x: hotspot_x, hotspot_y: hotspot_y)
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.release(res) } else { wl_resource_destroy(res) }
    }
}
