// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_region: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol WlRegionRequests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func add(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
    func subtract(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
}

public extension WlRegionRequests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlRegionServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_region_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_region_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_region_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.add = add_impl
        vt.pointee.subtract = subtract_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WlRegionRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlRegionRequests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let add_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.add(res, x: x, y: y, width: width, height: height)
    }
    private static let subtract_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.subtract(res, x: x, y: y, width: width, height: height)
    }
}
