// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_seat: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WlSeatRequests: AnyObject {
    func getPointer(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func getKeyboard(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func getTouch(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension WlSeatRequests {
    func release(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlSeatServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_seat_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_seat_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_seat_requests.self, capacity: 1)
        vt.pointee.get_pointer = getPointer_impl
        vt.pointee.get_keyboard = getKeyboard_impl
        vt.pointee.get_touch = getTouch_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendCapabilities(_ target: UnsafeMutablePointer<wl_resource>, capabilities: UInt32) {
        wl_seat_send_capabilities(target, capabilities)
    }
    public static func sendName(_ target: UnsafeMutablePointer<wl_resource>, name: UnsafePointer<CChar>?) {
        wl_seat_send_name(target, name)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WlSeatRequests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WlSeatRequests
    }

    private static let getPointer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.getPointer(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(10)), interface: swift_wayland_iface_wl_pointer()))
    }
    private static let getKeyboard_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.getKeyboard(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(10)), interface: swift_wayland_iface_wl_keyboard()))
    }
    private static let getTouch_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.getTouch(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(10)), interface: swift_wayland_iface_wl_touch()))
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.release(res) } else { wl_resource_destroy(res) }
    }
}
