// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_shell: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WlShellRequests: AnyObject {
    func getShellSurface(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, surface: UnsafeMutablePointer<wl_resource>?)
}

public enum WlShellServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_shell_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_shell_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_shell_requests.self, capacity: 1)
        vt.pointee.get_shell_surface = getShellSurface_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WlShellRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlShellRequests
    }

    private static let getShellSurface_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface in
        guard let res, let client, let h = handler(res) else { return }
        h.getShellSurface(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wl_shell_surface()), surface: surface)
    }
}
