// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_shell_surface: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WlShellSurfaceRequests: AnyObject {
    func pong(_ resource: UnsafeMutablePointer<wl_resource>, serial: UInt32)
    func move(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32)
    func resize(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32, edges: UInt32)
    func setToplevel(_ resource: UnsafeMutablePointer<wl_resource>)
    func setTransient(_ resource: UnsafeMutablePointer<wl_resource>, parent: UnsafeMutablePointer<wl_resource>?, x: Int32, y: Int32, flags: UInt32)
    func setFullscreen(_ resource: UnsafeMutablePointer<wl_resource>, method: UInt32, framerate: UInt32, output: UnsafeMutablePointer<wl_resource>?)
    func setPopup(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32, parent: UnsafeMutablePointer<wl_resource>?, x: Int32, y: Int32, flags: UInt32)
    func setMaximized(_ resource: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?)
    func setTitle(_ resource: UnsafeMutablePointer<wl_resource>, title: UnsafePointer<CChar>?)
    func setClass(_ resource: UnsafeMutablePointer<wl_resource>, class_: UnsafePointer<CChar>?)
}

public enum WlShellSurfaceServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_shell_surface_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_shell_surface_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_shell_surface_requests.self, capacity: 1)
        vt.pointee.pong = pong_impl
        vt.pointee.move = move_impl
        vt.pointee.resize = resize_impl
        vt.pointee.set_toplevel = setToplevel_impl
        vt.pointee.set_transient = setTransient_impl
        vt.pointee.set_fullscreen = setFullscreen_impl
        vt.pointee.set_popup = setPopup_impl
        vt.pointee.set_maximized = setMaximized_impl
        vt.pointee.set_title = setTitle_impl
        vt.pointee.set_class = setClass_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendPing(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32) {
        wl_shell_surface_send_ping(target, serial)
    }
    public static func sendConfigure(_ target: UnsafeMutablePointer<wl_resource>, edges: UInt32, width: Int32, height: Int32) {
        wl_shell_surface_send_configure(target, edges, width, height)
    }
    public static func sendPopupDone(_ target: UnsafeMutablePointer<wl_resource>) {
        wl_shell_surface_send_popup_done(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WlShellSurfaceRequests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WlShellSurfaceRequests
    }

    private static let pong_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, serial in
        guard let res, let h = handler(res) else { return }
        h.pong(res, serial: serial)
    }
    private static let move_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, seat, serial in
        guard let res, let h = handler(res) else { return }
        h.move(res, seat: seat, serial: serial)
    }
    private static let resize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32) -> Void = { _, res, seat, serial, edges in
        guard let res, let h = handler(res) else { return }
        h.resize(res, seat: seat, serial: serial, edges: edges)
    }
    private static let setToplevel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setToplevel(res)
    }
    private static let setTransient_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, UInt32) -> Void = { _, res, parent, x, y, flags in
        guard let res, let h = handler(res) else { return }
        h.setTransient(res, parent: parent, x: x, y: y, flags: flags)
    }
    private static let setFullscreen_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, method, framerate, output in
        guard let res, let h = handler(res) else { return }
        h.setFullscreen(res, method: method, framerate: framerate, output: output)
    }
    private static let setPopup_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?, Int32, Int32, UInt32) -> Void = { _, res, seat, serial, parent, x, y, flags in
        guard let res, let h = handler(res) else { return }
        h.setPopup(res, seat: seat, serial: serial, parent: parent, x: x, y: y, flags: flags)
    }
    private static let setMaximized_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, output in
        guard let res, let h = handler(res) else { return }
        h.setMaximized(res, output: output)
    }
    private static let setTitle_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, title in
        guard let res, let h = handler(res) else { return }
        h.setTitle(res, title: title)
    }
    private static let setClass_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, class_ in
        guard let res, let h = handler(res) else { return }
        h.setClass(res, class_: class_)
    }
}
