// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_shm_pool: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WlShmPoolRequests: AnyObject {
    func createBuffer(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, offset: Int32, width: Int32, height: Int32, stride: Int32, format: UInt32)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func resize(_ resource: UnsafeMutablePointer<wl_resource>, size: Int32)
}

public extension WlShmPoolRequests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlShmPoolServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_shm_pool_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_shm_pool_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_shm_pool_requests.self, capacity: 1)
        vt.pointee.create_buffer = createBuffer_impl
        vt.pointee.destroy = destroy_impl
        vt.pointee.resize = resize_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WlShmPoolRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlShmPoolRequests
    }

    private static let createBuffer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, Int32, Int32, Int32, Int32, UInt32) -> Void = { client, res, id, offset, width, height, stride, format in
        guard let res, let client, let h = handler(res) else { return }
        h.createBuffer(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wl_buffer()), offset: offset, width: width, height: height, stride: stride, format: format)
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let resize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32) -> Void = { _, res, size in
        guard let res, let h = handler(res) else { return }
        h.resize(res, size: size)
    }
}
