// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wl_surface: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WlSurfaceRequests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func attach(_ resource: UnsafeMutablePointer<wl_resource>, buffer: UnsafeMutablePointer<wl_resource>?, x: Int32, y: Int32)
    func damage(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
    func frame(_ resource: UnsafeMutablePointer<wl_resource>, callback: WlNewId)
    func setOpaqueRegion(_ resource: UnsafeMutablePointer<wl_resource>, region: UnsafeMutablePointer<wl_resource>?)
    func setInputRegion(_ resource: UnsafeMutablePointer<wl_resource>, region: UnsafeMutablePointer<wl_resource>?)
    func commit(_ resource: UnsafeMutablePointer<wl_resource>)
    func setBufferTransform(_ resource: UnsafeMutablePointer<wl_resource>, transform: Int32)
    func setBufferScale(_ resource: UnsafeMutablePointer<wl_resource>, scale: Int32)
    func damageBuffer(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
    func offset(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32)
    func getRelease(_ resource: UnsafeMutablePointer<wl_resource>, callback: WlNewId)
}

public extension WlSurfaceRequests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WlSurfaceServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_surface_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_surface_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wl_surface_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.attach = attach_impl
        vt.pointee.damage = damage_impl
        vt.pointee.frame = frame_impl
        vt.pointee.set_opaque_region = setOpaqueRegion_impl
        vt.pointee.set_input_region = setInputRegion_impl
        vt.pointee.commit = commit_impl
        vt.pointee.set_buffer_transform = setBufferTransform_impl
        vt.pointee.set_buffer_scale = setBufferScale_impl
        vt.pointee.damage_buffer = damageBuffer_impl
        vt.pointee.offset = offset_impl
        vt.pointee.get_release = getRelease_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendEnter(_ target: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?) {
        wl_surface_send_enter(target, output)
    }
    public static func sendLeave(_ target: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?) {
        wl_surface_send_leave(target, output)
    }
    public static func sendPreferredBufferScale(_ target: UnsafeMutablePointer<wl_resource>, factor: Int32) {
        wl_surface_send_preferred_buffer_scale(target, factor)
    }
    public static func sendPreferredBufferTransform(_ target: UnsafeMutablePointer<wl_resource>, transform: UInt32) {
        wl_surface_send_preferred_buffer_transform(target, transform)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WlSurfaceRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlSurfaceRequests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let attach_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, buffer, x, y in
        guard let res, let h = handler(res) else { return }
        h.attach(res, buffer: buffer, x: x, y: y)
    }
    private static let damage_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.damage(res, x: x, y: y, width: width, height: height)
    }
    private static let frame_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, callback in
        guard let res, let client, let h = handler(res) else { return }
        h.frame(res, callback: WlNewId(client: client, id: callback, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wl_callback()))
    }
    private static let setOpaqueRegion_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, region in
        guard let res, let h = handler(res) else { return }
        h.setOpaqueRegion(res, region: region)
    }
    private static let setInputRegion_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, region in
        guard let res, let h = handler(res) else { return }
        h.setInputRegion(res, region: region)
    }
    private static let commit_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.commit(res)
    }
    private static let setBufferTransform_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32) -> Void = { _, res, transform in
        guard let res, let h = handler(res) else { return }
        h.setBufferTransform(res, transform: transform)
    }
    private static let setBufferScale_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32) -> Void = { _, res, scale in
        guard let res, let h = handler(res) else { return }
        h.setBufferScale(res, scale: scale)
    }
    private static let damageBuffer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.damageBuffer(res, x: x, y: y, width: width, height: height)
    }
    private static let offset_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, x, y in
        guard let res, let h = handler(res) else { return }
        h.offset(res, x: x, y: y)
    }
    private static let getRelease_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, callback in
        guard let res, let client, let h = handler(res) else { return }
        h.getRelease(res, callback: WlNewId(client: client, id: callback, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wl_callback()))
    }
}
