// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for wl_subsurface.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol WlSubsurfaceRequests: AnyObject {
    func destroy(_ request: WaylandRequest<WlSubsurfaceServer>)
    func setPosition(_ request: WaylandRequest<WlSubsurfaceServer>, x: Int32, y: Int32)
    func placeAbove(_ request: WaylandRequest<WlSubsurfaceServer>, sibling: WaylandBorrowedObject<WlSurfaceServer>)
    func placeBelow(_ request: WaylandRequest<WlSubsurfaceServer>, sibling: WaylandBorrowedObject<WlSurfaceServer>)
    func setSync(_ request: WaylandRequest<WlSubsurfaceServer>)
    func setDesync(_ request: WaylandRequest<WlSubsurfaceServer>)
}
public extension WlSubsurfaceRequests {
    func destroy(_ request: WaylandRequest<WlSubsurfaceServer>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum WlSubsurfaceServer: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_wl_subsurface()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wl_subsurface_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wl_subsurface_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_wl_subsurface_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.set_position = setPosition_impl
        unsafe vt.pointee.place_above = placeAbove_impl
        unsafe vt.pointee.place_below = placeBelow_impl
        unsafe vt.pointee.set_sync = setSync_impl
        unsafe vt.pointee.set_desync = setDesync_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any WlSubsurfaceRequests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WlSubsurfaceRequests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<WlSubsurfaceServer>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let setPosition_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, x, y in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.setPosition(WaylandRequest<WlSubsurfaceServer>(requestResource), x: x, y: y)
        }
    }
    private static let placeAbove_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, sibling in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_sibling = unsafe sibling
        MainActor.assumeIsolated {
            unsafe requestHandler.placeAbove(WaylandRequest<WlSubsurfaceServer>(requestResource), sibling: WaylandBorrowedObject<WlSurfaceServer>(_request_sibling!))
        }
    }
    private static let placeBelow_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, sibling in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_sibling = unsafe sibling
        MainActor.assumeIsolated {
            unsafe requestHandler.placeBelow(WaylandRequest<WlSubsurfaceServer>(requestResource), sibling: WaylandBorrowedObject<WlSurfaceServer>(_request_sibling!))
        }
    }
    private static let setSync_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.setSync(WaylandRequest<WlSubsurfaceServer>(requestResource))
        }
    }
    private static let setDesync_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.setDesync(WaylandRequest<WlSubsurfaceServer>(requestResource))
        }
    }
}
public extension WaylandRequest where Interface == WlSubsurfaceServer {
    func postError(_ code: WlSubsurfaceError, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == WlSubsurfaceServer {
    @discardableResult
    func postError(_ code: WlSubsurfaceError, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == WlSubsurfaceServer {
    @discardableResult
    @MainActor
    func create<Owner: WlSubsurfaceRequests>(
        owner: (WaylandResourceHandle<WlSubsurfaceServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: WlSubsurfaceServer.requestVtable(), owner: owner, installed: installed)
    }
}
public extension WlSubsurfaceServer {
    @discardableResult
    @MainActor
    static func createResource<Owner: WlSubsurfaceRequests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<WlSubsurfaceServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: WlSubsurfaceServer.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: WlSubsurfaceRequests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<WlSubsurfaceServer>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<WlSubsurfaceServer>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<WlSubsurfaceServer> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}