// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wp_cursor_shape_manager_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WpCursorShapeManagerV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func getPointer(_ resource: UnsafeMutablePointer<wl_resource>, cursor_shape_device: WlNewId, pointer: UnsafeMutablePointer<wl_resource>?)
    func getTabletToolV2(_ resource: UnsafeMutablePointer<wl_resource>, cursor_shape_device: WlNewId, tablet_tool: UnsafeMutablePointer<wl_resource>?)
}

public extension WpCursorShapeManagerV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WpCursorShapeManagerV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_cursor_shape_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_cursor_shape_manager_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wp_cursor_shape_manager_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.get_pointer = getPointer_impl
        vt.pointee.get_tablet_tool_v2 = getTabletToolV2_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WpCursorShapeManagerV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WpCursorShapeManagerV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let getPointer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, cursor_shape_device, pointer in
        guard let res, let client, let h = handler(res) else { return }
        h.getPointer(res, cursor_shape_device: WlNewId(client: client, id: cursor_shape_device, version: Swift::min(wl_resource_get_version(res), Int32(2)), interface: swift_wayland_iface_wp_cursor_shape_device_v1()), pointer: pointer)
    }
    private static let getTabletToolV2_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, cursor_shape_device, tablet_tool in
        guard let res, let client, let h = handler(res) else { return }
        h.getTabletToolV2(res, cursor_shape_device: WlNewId(client: client, id: cursor_shape_device, version: Swift::min(wl_resource_get_version(res), Int32(2)), interface: swift_wayland_iface_wp_cursor_shape_device_v1()), tablet_tool: tablet_tool)
    }
}
