// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wp_drm_lease_request_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WpDrmLeaseRequestV1Requests: AnyObject {
    func requestConnector(_ resource: UnsafeMutablePointer<wl_resource>, connector: UnsafeMutablePointer<wl_resource>?)
    func submit(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
}

public enum WpDrmLeaseRequestV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_drm_lease_request_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_drm_lease_request_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wp_drm_lease_request_v1_requests.self, capacity: 1)
        vt.pointee.request_connector = requestConnector_impl
        vt.pointee.submit = submit_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WpDrmLeaseRequestV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WpDrmLeaseRequestV1Requests
    }

    private static let requestConnector_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, connector in
        guard let res, let h = handler(res) else { return }
        h.requestConnector(res, connector: connector)
    }
    private static let submit_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.submit(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wp_drm_lease_v1()))
        wl_resource_destroy(res)
    }
}
