// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wp_drm_lease_device_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WpDrmLeaseDeviceV1Requests: AnyObject {
    func createLeaseRequest(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func release(_ resource: UnsafeMutablePointer<wl_resource>)
}

public enum WpDrmLeaseDeviceV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_drm_lease_device_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_drm_lease_device_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wp_drm_lease_device_v1_requests.self, capacity: 1)
        vt.pointee.create_lease_request = createLeaseRequest_impl
        vt.pointee.release = release_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendDrmFd(_ target: UnsafeMutablePointer<wl_resource>, fd: Int32) {
        wp_drm_lease_device_v1_send_drm_fd(target, fd)
    }
    public static func sendConnector(_ target: UnsafeMutablePointer<wl_resource>, id: UnsafeMutablePointer<wl_resource>?) {
        wp_drm_lease_device_v1_send_connector(target, id)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        wp_drm_lease_device_v1_send_done(target)
    }
    public static func sendReleased(_ target: UnsafeMutablePointer<wl_resource>) {
        wp_drm_lease_device_v1_send_released(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WpDrmLeaseDeviceV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WpDrmLeaseDeviceV1Requests
    }

    private static let createLeaseRequest_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.createLeaseRequest(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wp_drm_lease_request_v1()))
    }
    private static let release_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.release(res)
    }
}
