// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wp_fifo_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol WpFifoV1Requests: AnyObject {
    func setBarrier(_ resource: UnsafeMutablePointer<wl_resource>)
    func waitBarrier(_ resource: UnsafeMutablePointer<wl_resource>)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension WpFifoV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum WpFifoV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_fifo_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_fifo_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wp_fifo_v1_requests.self, capacity: 1)
        vt.pointee.set_barrier = setBarrier_impl
        vt.pointee.wait_barrier = waitBarrier_impl
        vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> WpFifoV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? WpFifoV1Requests
    }

    private static let setBarrier_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setBarrier(res)
    }
    private static let waitBarrier_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.waitBarrier(res)
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
}
