// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for wp_image_description_reference_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol WpImageDescriptionReferenceV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<WpImageDescriptionReferenceV1Server>)
}
public extension WpImageDescriptionReferenceV1Requests {
    func destroy(_ request: WaylandRequest<WpImageDescriptionReferenceV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum WpImageDescriptionReferenceV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_wp_image_description_reference_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_image_description_reference_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_image_description_reference_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_wp_image_description_reference_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any WpImageDescriptionReferenceV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WpImageDescriptionReferenceV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<WpImageDescriptionReferenceV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WlNewId where Interface == WpImageDescriptionReferenceV1Server {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<WpImageDescriptionReferenceV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: WpImageDescriptionReferenceV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension WpImageDescriptionReferenceV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<WpImageDescriptionReferenceV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: WpImageDescriptionReferenceV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<WpImageDescriptionReferenceV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<WpImageDescriptionReferenceV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<WpImageDescriptionReferenceV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}