// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for wp_image_description_creator_icc_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol WpImageDescriptionCreatorIccV1Requests: AnyObject {
    func create(_ resource: UnsafeMutablePointer<wl_resource>, image_description: WlNewId)
    func setIccFile(_ resource: UnsafeMutablePointer<wl_resource>, icc_profile: Int32, offset: UInt32, length: UInt32)
}

public enum WpImageDescriptionCreatorIccV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_image_description_creator_icc_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_image_description_creator_icc_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_wp_image_description_creator_icc_v1_requests.self, capacity: 1)
        vt.pointee.create = create_impl
        vt.pointee.set_icc_file = setIccFile_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any WpImageDescriptionCreatorIccV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WpImageDescriptionCreatorIccV1Requests
    }

    private static let create_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, image_description in
        guard let res, let client, let h = handler(res) else { return }
        h.create(res, image_description: WlNewId(client: client, id: image_description, version: Swift::min(wl_resource_get_version(res), Int32(2)), interface: swift_wayland_iface_wp_image_description_v1()))
        wl_resource_destroy(res)
    }
    private static let setIccFile_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, UInt32, UInt32) -> Void = { _, res, icc_profile, offset, length in
        guard let res, let h = handler(res) else { return }
        h.setIccFile(res, icc_profile: icc_profile, offset: offset, length: length)
    }
}
