// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for wp_linux_drm_syncobj_manager_v1.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol WpLinuxDrmSyncobjManagerV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>)
    func getSurface(_ request: WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>, id: WlNewId<WpLinuxDrmSyncobjSurfaceV1Server>, surface: WaylandBorrowedObject<WlSurfaceServer>)
    func importTimeline(_ request: WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>, id: WlNewId<WpLinuxDrmSyncobjTimelineV1Server>, fd: consuming WaylandOwnedFileDescriptor)
}
public extension WpLinuxDrmSyncobjManagerV1Requests {
    func destroy(_ request: WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum WpLinuxDrmSyncobjManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_wp_linux_drm_syncobj_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_linux_drm_syncobj_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_linux_drm_syncobj_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_wp_linux_drm_syncobj_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.get_surface = getSurface_impl
        unsafe vt.pointee.import_timeline = importTimeline_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any WpLinuxDrmSyncobjManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WpLinuxDrmSyncobjManagerV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let getSurface_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.getSurface(WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>(requestResource), id: WlNewId<WpLinuxDrmSyncobjSurfaceV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!))
        }
    }
    private static let importTimeline_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, Int32) -> Void = { client, res, id, fd in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        MainActor.assumeIsolated {
            unsafe requestHandler.importTimeline(WaylandRequest<WpLinuxDrmSyncobjManagerV1Server>(requestResource), id: WlNewId<WpLinuxDrmSyncobjTimelineV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))), fd: WaylandOwnedFileDescriptor(fd))
        }
    }
}
public extension WaylandRequest where Interface == WpLinuxDrmSyncobjManagerV1Server {
    func postError(_ code: WpLinuxDrmSyncobjManagerV1Error, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == WpLinuxDrmSyncobjManagerV1Server {
    @discardableResult
    func postError(_ code: WpLinuxDrmSyncobjManagerV1Error, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == WpLinuxDrmSyncobjManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: WpLinuxDrmSyncobjManagerV1Requests>(
        owner: (WaylandResourceHandle<WpLinuxDrmSyncobjManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: WpLinuxDrmSyncobjManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension WpLinuxDrmSyncobjManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: WpLinuxDrmSyncobjManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<WpLinuxDrmSyncobjManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: WpLinuxDrmSyncobjManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: WpLinuxDrmSyncobjManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<WpLinuxDrmSyncobjManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<WpLinuxDrmSyncobjManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<WpLinuxDrmSyncobjManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}