// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for wp_presentation.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol WpPresentationRequests: AnyObject {
    func destroy(_ request: WaylandRequest<WpPresentationServer>)
    func feedback(_ request: WaylandRequest<WpPresentationServer>, surface: WaylandBorrowedObject<WlSurfaceServer>, callback: WlNewId<WpPresentationFeedbackServer>)
}
public extension WpPresentationRequests {
    func destroy(_ request: WaylandRequest<WpPresentationServer>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum WpPresentationServer: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_wp_presentation()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_wp_presentation_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_wp_presentation_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_wp_presentation_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.feedback = feedback_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendClockId(_ target: UnsafeMutablePointer<wl_resource>, clk_id: UInt32) {
        unsafe wp_presentation_send_clock_id(target, clk_id)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any WpPresentationRequests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any WpPresentationRequests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<WpPresentationServer>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let feedback_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, surface, callback in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.feedback(WaylandRequest<WpPresentationServer>(requestResource), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!), callback: WlNewId<WpPresentationFeedbackServer>(client: requestClient, id: callback, version: Swift::min(wl_resource_get_version(requestResource), Int32(2))))
        }
    }
}
public extension WaylandResourceHandle where Interface == WpPresentationServer {
    @discardableResult
    func sendClockId(clk_id: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe wp_presentation_send_clock_id(target, clk_id)
        return true
    }
}
public extension WaylandRequest where Interface == WpPresentationServer {
    func postError(_ code: WpPresentationError, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == WpPresentationServer {
    @discardableResult
    func postError(_ code: WpPresentationError, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == WpPresentationServer {
    @discardableResult
    @MainActor
    func create<Owner: WpPresentationRequests>(
        owner: (WaylandResourceHandle<WpPresentationServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: WpPresentationServer.requestVtable(), owner: owner, installed: installed)
    }
}
public extension WpPresentationServer {
    @discardableResult
    @MainActor
    static func createResource<Owner: WpPresentationRequests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<WpPresentationServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: WpPresentationServer.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: WpPresentationRequests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<WpPresentationServer>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<WpPresentationServer>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<WpPresentationServer> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}