// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for wp_presentation_feedback.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
public enum WpPresentationFeedbackServer: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_wp_presentation_feedback()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        nil
    }
    public static func sendSyncOutput(_ target: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?) {
        unsafe wp_presentation_feedback_send_sync_output(target, output)
    }
    public static func sendPresented(_ target: UnsafeMutablePointer<wl_resource>, tv_sec_hi: UInt32, tv_sec_lo: UInt32, tv_nsec: UInt32, refresh: UInt32, seq_hi: UInt32, seq_lo: UInt32, flags: WpPresentationFeedbackKind) {
        unsafe wp_presentation_feedback_send_presented(target, tv_sec_hi, tv_sec_lo, tv_nsec, refresh, seq_hi, seq_lo, flags.rawValue)
    }
    public static func sendDiscarded(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe wp_presentation_feedback_send_discarded(target)
    }
}
public extension WaylandResourceHandle where Interface == WpPresentationFeedbackServer {
    @discardableResult
    func sendSyncOutput(output: WaylandResourceHandle<WlOutputServer>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_outputResource = unsafe output.resource else {
            return false
        }
        unsafe wp_presentation_feedback_send_sync_output(target, _event_outputResource)
        return true
    }
    @discardableResult
    func sendPresented(tv_sec_hi: UInt32, tv_sec_lo: UInt32, tv_nsec: UInt32, refresh: UInt32, seq_hi: UInt32, seq_lo: UInt32, flags: WpPresentationFeedbackKind) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe wp_presentation_feedback_send_presented(target, tv_sec_hi, tv_sec_lo, tv_nsec, refresh, seq_hi, seq_lo, flags.rawValue)
        return true
    }
    @discardableResult
    func sendDiscarded() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe wp_presentation_feedback_send_discarded(target)
        return true
    }
}
public extension WlNewId where Interface == WpPresentationFeedbackServer {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<WpPresentationFeedbackServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: WpPresentationFeedbackServer.requestVtable(), owner: owner, installed: installed)
    }
    @discardableResult
    @MainActor
    func createBare() -> UnsafeMutablePointer<wl_resource>? {
        unsafe _createBare()
    }
}
public extension WpPresentationFeedbackServer {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<WpPresentationFeedbackServer>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: WpPresentationFeedbackServer.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<WpPresentationFeedbackServer>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<WpPresentationFeedbackServer>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<WpPresentationFeedbackServer> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}