// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for xdg_activation_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol XdgActivationV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<XdgActivationV1Server>)
    func getActivationToken(_ request: WaylandRequest<XdgActivationV1Server>, id: WlNewId<XdgActivationTokenV1Server>)
    func activate(_ request: WaylandRequest<XdgActivationV1Server>, token: String, surface: WaylandBorrowedObject<WlSurfaceServer>)
}
public extension XdgActivationV1Requests {
    func destroy(_ request: WaylandRequest<XdgActivationV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum XdgActivationV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_xdg_activation_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_activation_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_activation_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_xdg_activation_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.get_activation_token = getActivationToken_impl
        unsafe vt.pointee.activate = activate_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any XdgActivationV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any XdgActivationV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<XdgActivationV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let getActivationToken_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        MainActor.assumeIsolated {
            unsafe requestHandler.getActivationToken(WaylandRequest<XdgActivationV1Server>(requestResource), id: WlNewId<XdgActivationTokenV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))))
        }
    }
    private static let activate_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, token, surface in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_token = unsafe token
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.activate(WaylandRequest<XdgActivationV1Server>(requestResource), token: unsafe String(cString: _request_token!), surface: WaylandBorrowedObject<WlSurfaceServer>(_request_surface!))
        }
    }
}
public extension WlNewId where Interface == XdgActivationV1Server {
    @discardableResult
    @MainActor
    func create<Owner: XdgActivationV1Requests>(
        owner: (WaylandResourceHandle<XdgActivationV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: XdgActivationV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension XdgActivationV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: XdgActivationV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<XdgActivationV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: XdgActivationV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: XdgActivationV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<XdgActivationV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<XdgActivationV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<XdgActivationV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}