// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for xdg_positioner: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol XdgPositionerRequests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func setSize(_ resource: UnsafeMutablePointer<wl_resource>, width: Int32, height: Int32)
    func setAnchorRect(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
    func setAnchor(_ resource: UnsafeMutablePointer<wl_resource>, anchor: UInt32)
    func setGravity(_ resource: UnsafeMutablePointer<wl_resource>, gravity: UInt32)
    func setConstraintAdjustment(_ resource: UnsafeMutablePointer<wl_resource>, constraint_adjustment: UInt32)
    func setOffset(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32)
    func setReactive(_ resource: UnsafeMutablePointer<wl_resource>)
    func setParentSize(_ resource: UnsafeMutablePointer<wl_resource>, parent_width: Int32, parent_height: Int32)
    func setParentConfigure(_ resource: UnsafeMutablePointer<wl_resource>, serial: UInt32)
}

public extension XdgPositionerRequests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum XdgPositionerServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_positioner_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_positioner_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_xdg_positioner_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.set_size = setSize_impl
        vt.pointee.set_anchor_rect = setAnchorRect_impl
        vt.pointee.set_anchor = setAnchor_impl
        vt.pointee.set_gravity = setGravity_impl
        vt.pointee.set_constraint_adjustment = setConstraintAdjustment_impl
        vt.pointee.set_offset = setOffset_impl
        vt.pointee.set_reactive = setReactive_impl
        vt.pointee.set_parent_size = setParentSize_impl
        vt.pointee.set_parent_configure = setParentConfigure_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any XdgPositionerRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any XdgPositionerRequests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let setSize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, width, height in
        guard let res, let h = handler(res) else { return }
        h.setSize(res, width: width, height: height)
    }
    private static let setAnchorRect_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.setAnchorRect(res, x: x, y: y, width: width, height: height)
    }
    private static let setAnchor_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, anchor in
        guard let res, let h = handler(res) else { return }
        h.setAnchor(res, anchor: anchor)
    }
    private static let setGravity_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, gravity in
        guard let res, let h = handler(res) else { return }
        h.setGravity(res, gravity: gravity)
    }
    private static let setConstraintAdjustment_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, constraint_adjustment in
        guard let res, let h = handler(res) else { return }
        h.setConstraintAdjustment(res, constraint_adjustment: constraint_adjustment)
    }
    private static let setOffset_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, x, y in
        guard let res, let h = handler(res) else { return }
        h.setOffset(res, x: x, y: y)
    }
    private static let setReactive_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setReactive(res)
    }
    private static let setParentSize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, parent_width, parent_height in
        guard let res, let h = handler(res) else { return }
        h.setParentSize(res, parent_width: parent_width, parent_height: parent_height)
    }
    private static let setParentConfigure_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, serial in
        guard let res, let h = handler(res) else { return }
        h.setParentConfigure(res, serial: serial)
    }
}
