// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for xdg_popup: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol XdgPopupRequests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func grab(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32)
    func reposition(_ resource: UnsafeMutablePointer<wl_resource>, positioner: UnsafeMutablePointer<wl_resource>?, token: UInt32)
}

public extension XdgPopupRequests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum XdgPopupServer {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_popup_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_popup_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_xdg_popup_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.grab = grab_impl
        vt.pointee.reposition = reposition_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendConfigure(_ target: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32) {
        xdg_popup_send_configure(target, x, y, width, height)
    }
    public static func sendPopupDone(_ target: UnsafeMutablePointer<wl_resource>) {
        xdg_popup_send_popup_done(target)
    }
    public static func sendRepositioned(_ target: UnsafeMutablePointer<wl_resource>, token: UInt32) {
        xdg_popup_send_repositioned(target, token)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any XdgPopupRequests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any XdgPopupRequests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let grab_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, seat, serial in
        guard let res, let h = handler(res) else { return }
        h.grab(res, seat: seat, serial: serial)
    }
    private static let reposition_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, positioner, token in
        guard let res, let h = handler(res) else { return }
        h.reposition(res, positioner: positioner, token: token)
    }
}
