// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for xdg_session_manager_v1.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol XdgSessionManagerV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<XdgSessionManagerV1Server>)
    func getSession(_ request: WaylandRequest<XdgSessionManagerV1Server>, id: WlNewId<XdgSessionV1Server>, reason: XdgSessionManagerV1Reason, session_id: String?)
}
public extension XdgSessionManagerV1Requests {
    func destroy(_ request: WaylandRequest<XdgSessionManagerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum XdgSessionManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_xdg_session_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_session_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_session_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_xdg_session_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.get_session = getSession_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any XdgSessionManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any XdgSessionManagerV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<XdgSessionManagerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let getSession_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32, UnsafePointer<CChar>?) -> Void = { client, res, id, reason, session_id in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_session_id = unsafe session_id
        MainActor.assumeIsolated {
            unsafe requestHandler.getSession(WaylandRequest<XdgSessionManagerV1Server>(requestResource), id: WlNewId<XdgSessionV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))), reason: XdgSessionManagerV1Reason(rawValue: reason), session_id: _request_session_id.map {
                    unsafe String(cString: $0)
                })
        }
    }
}
public extension WaylandRequest where Interface == XdgSessionManagerV1Server {
    func postError(_ code: XdgSessionManagerV1Error, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == XdgSessionManagerV1Server {
    @discardableResult
    func postError(_ code: XdgSessionManagerV1Error, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == XdgSessionManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: XdgSessionManagerV1Requests>(
        owner: (WaylandResourceHandle<XdgSessionManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: XdgSessionManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension XdgSessionManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: XdgSessionManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<XdgSessionManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: XdgSessionManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: XdgSessionManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<XdgSessionManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<XdgSessionManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<XdgSessionManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}