// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for xdg_toplevel_icon_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol XdgToplevelIconV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func setName(_ resource: UnsafeMutablePointer<wl_resource>, icon_name: UnsafePointer<CChar>?)
    func addBuffer(_ resource: UnsafeMutablePointer<wl_resource>, buffer: UnsafeMutablePointer<wl_resource>?, scale: Int32)
}

public extension XdgToplevelIconV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum XdgToplevelIconV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_toplevel_icon_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_toplevel_icon_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_xdg_toplevel_icon_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.set_name = setName_impl
        vt.pointee.add_buffer = addBuffer_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any XdgToplevelIconV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any XdgToplevelIconV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let setName_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, icon_name in
        guard let res, let h = handler(res) else { return }
        h.setName(res, icon_name: icon_name)
    }
    private static let addBuffer_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, Int32) -> Void = { _, res, buffer, scale in
        guard let res, let h = handler(res) else { return }
        h.addBuffer(res, buffer: buffer, scale: scale)
    }
}
