// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for xdg_toplevel_icon_manager_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol XdgToplevelIconManagerV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func createIcon(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func setIcon(_ resource: UnsafeMutablePointer<wl_resource>, toplevel: UnsafeMutablePointer<wl_resource>?, icon: UnsafeMutablePointer<wl_resource>?)
}

public extension XdgToplevelIconManagerV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum XdgToplevelIconManagerV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_xdg_toplevel_icon_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_xdg_toplevel_icon_manager_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_xdg_toplevel_icon_manager_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.create_icon = createIcon_impl
        vt.pointee.set_icon = setIcon_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendIconSize(_ target: UnsafeMutablePointer<wl_resource>, size: Int32) {
        xdg_toplevel_icon_manager_v1_send_icon_size(target, size)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        xdg_toplevel_icon_manager_v1_send_done(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> XdgToplevelIconManagerV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? XdgToplevelIconManagerV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let createIcon_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.createIcon(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_xdg_toplevel_icon_v1()))
    }
    private static let setIcon_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, toplevel, icon in
        guard let res, let h = handler(res) else { return }
        h.setIcon(res, toplevel: toplevel, icon: icon)
    }
}
