// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwlr_output_configuration_v1.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol ZwlrOutputConfigurationV1Requests: AnyObject {
    func enableHead(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>, id: WlNewId<ZwlrOutputConfigurationHeadV1Server>, head: WaylandBorrowedObject<ZwlrOutputHeadV1Server>)
    func disableHead(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>, head: WaylandBorrowedObject<ZwlrOutputHeadV1Server>)
    func apply(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>)
    func test(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>)
    func destroy(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>)
}
public extension ZwlrOutputConfigurationV1Requests {
    func destroy(_ request: WaylandRequest<ZwlrOutputConfigurationV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwlrOutputConfigurationV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwlr_output_configuration_v1()
    public nonisolated static let maximumVersion: Int32 = 4
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwlr_output_configuration_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwlr_output_configuration_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwlr_output_configuration_v1_requests.self, capacity: 1)
        unsafe vt.pointee.enable_head = enableHead_impl
        unsafe vt.pointee.disable_head = disableHead_impl
        unsafe vt.pointee.apply = apply_impl
        unsafe vt.pointee.test = test_impl
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendSucceeded(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwlr_output_configuration_v1_send_succeeded(target)
    }
    public static func sendFailed(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwlr_output_configuration_v1_send_failed(target)
    }
    public static func sendCancelled(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwlr_output_configuration_v1_send_cancelled(target)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwlrOutputConfigurationV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwlrOutputConfigurationV1Requests
    }
    private static let enableHead_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, head in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_head = unsafe head
        MainActor.assumeIsolated {
            unsafe requestHandler.enableHead(WaylandRequest<ZwlrOutputConfigurationV1Server>(requestResource), id: WlNewId<ZwlrOutputConfigurationHeadV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(4))), head: WaylandBorrowedObject<ZwlrOutputHeadV1Server>(_request_head!))
        }
    }
    private static let disableHead_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, head in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_head = unsafe head
        MainActor.assumeIsolated {
            unsafe requestHandler.disableHead(WaylandRequest<ZwlrOutputConfigurationV1Server>(requestResource), head: WaylandBorrowedObject<ZwlrOutputHeadV1Server>(_request_head!))
        }
    }
    private static let apply_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.apply(WaylandRequest<ZwlrOutputConfigurationV1Server>(requestResource))
        }
    }
    private static let test_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        MainActor.assumeIsolated {
            unsafe requestHandler.test(WaylandRequest<ZwlrOutputConfigurationV1Server>(requestResource))
        }
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwlrOutputConfigurationV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ZwlrOutputConfigurationV1Server {
    @discardableResult
    func sendSucceeded() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwlr_output_configuration_v1_send_succeeded(target)
        return true
    }
    @discardableResult
    func sendFailed() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwlr_output_configuration_v1_send_failed(target)
        return true
    }
    @discardableResult
    func sendCancelled() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwlr_output_configuration_v1_send_cancelled(target)
        return true
    }
}
public extension WaylandRequest where Interface == ZwlrOutputConfigurationV1Server {
    func postError(_ code: ZwlrOutputConfigurationV1Error, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == ZwlrOutputConfigurationV1Server {
    @discardableResult
    func postError(_ code: ZwlrOutputConfigurationV1Error, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == ZwlrOutputConfigurationV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ZwlrOutputConfigurationV1Requests>(
        owner: (WaylandResourceHandle<ZwlrOutputConfigurationV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwlrOutputConfigurationV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwlrOutputConfigurationV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZwlrOutputConfigurationV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwlrOutputConfigurationV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwlrOutputConfigurationV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZwlrOutputConfigurationV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwlrOutputConfigurationV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwlrOutputConfigurationV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwlrOutputConfigurationV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}