// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_input_panel_surface_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol ZwpInputPanelSurfaceV1Requests: AnyObject {
    func setToplevel(_ resource: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?, position: UInt32)
    func setOverlayPanel(_ resource: UnsafeMutablePointer<wl_resource>)
}

public enum ZwpInputPanelSurfaceV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_input_panel_surface_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_input_panel_surface_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_input_panel_surface_v1_requests.self, capacity: 1)
        vt.pointee.set_toplevel = setToplevel_impl
        vt.pointee.set_overlay_panel = setOverlayPanel_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZwpInputPanelSurfaceV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpInputPanelSurfaceV1Requests
    }

    private static let setToplevel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, output, position in
        guard let res, let h = handler(res) else { return }
        h.setToplevel(res, output: output, position: position)
    }
    private static let setOverlayPanel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setOverlayPanel(res)
    }
}
