// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_keyboard_shortcuts_inhibit_manager_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ZwpKeyboardShortcutsInhibitManagerV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func inhibitShortcuts(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, surface: UnsafeMutablePointer<wl_resource>?, seat: UnsafeMutablePointer<wl_resource>?)
}

public extension ZwpKeyboardShortcutsInhibitManagerV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpKeyboardShortcutsInhibitManagerV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_keyboard_shortcuts_inhibit_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_keyboard_shortcuts_inhibit_manager_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_keyboard_shortcuts_inhibit_manager_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.inhibit_shortcuts = inhibitShortcuts_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZwpKeyboardShortcutsInhibitManagerV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpKeyboardShortcutsInhibitManagerV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let inhibitShortcuts_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, surface, seat in
        guard let res, let client, let h = handler(res) else { return }
        h.inhibitShortcuts(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_zwp_keyboard_shortcuts_inhibitor_v1()), surface: surface, seat: seat)
    }
}
