// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_linux_buffer_params_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ZwpLinuxBufferParamsV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func add(_ resource: UnsafeMutablePointer<wl_resource>, fd: Int32, plane_idx: UInt32, offset: UInt32, stride: UInt32, modifier_hi: UInt32, modifier_lo: UInt32)
    func create(_ resource: UnsafeMutablePointer<wl_resource>, width: Int32, height: Int32, format: UInt32, flags: UInt32)
    func createImmed(_ resource: UnsafeMutablePointer<wl_resource>, buffer_id: WlNewId, width: Int32, height: Int32, format: UInt32, flags: UInt32)
}

public extension ZwpLinuxBufferParamsV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpLinuxBufferParamsV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_linux_buffer_params_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_linux_buffer_params_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_linux_buffer_params_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.add = add_impl
        vt.pointee.create = create_impl
        vt.pointee.create_immed = createImmed_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendCreated(_ target: UnsafeMutablePointer<wl_resource>, buffer: UnsafeMutablePointer<wl_resource>?) {
        zwp_linux_buffer_params_v1_send_created(target, buffer)
    }
    public static func sendFailed(_ target: UnsafeMutablePointer<wl_resource>) {
        zwp_linux_buffer_params_v1_send_failed(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZwpLinuxBufferParamsV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpLinuxBufferParamsV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let add_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, UInt32, UInt32, UInt32, UInt32, UInt32) -> Void = { _, res, fd, plane_idx, offset, stride, modifier_hi, modifier_lo in
        guard let res, let h = handler(res) else { return }
        h.add(res, fd: fd, plane_idx: plane_idx, offset: offset, stride: stride, modifier_hi: modifier_hi, modifier_lo: modifier_lo)
    }
    private static let create_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, UInt32, UInt32) -> Void = { _, res, width, height, format, flags in
        guard let res, let h = handler(res) else { return }
        h.create(res, width: width, height: height, format: format, flags: flags)
    }
    private static let createImmed_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, Int32, Int32, UInt32, UInt32) -> Void = { client, res, buffer_id, width, height, format, flags in
        guard let res, let client, let h = handler(res) else { return }
        h.createImmed(res, buffer_id: WlNewId(client: client, id: buffer_id, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_wl_buffer()), width: width, height: height, format: format, flags: flags)
    }
}
