// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_linux_surface_synchronization_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ZwpLinuxSurfaceSynchronizationV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func setAcquireFence(_ resource: UnsafeMutablePointer<wl_resource>, fd: Int32)
    func getRelease(_ resource: UnsafeMutablePointer<wl_resource>, release: WlNewId)
}

public extension ZwpLinuxSurfaceSynchronizationV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpLinuxSurfaceSynchronizationV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_linux_surface_synchronization_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_linux_surface_synchronization_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_linux_surface_synchronization_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.set_acquire_fence = setAcquireFence_impl
        vt.pointee.get_release = getRelease_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ZwpLinuxSurfaceSynchronizationV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ZwpLinuxSurfaceSynchronizationV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let setAcquireFence_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32) -> Void = { _, res, fd in
        guard let res, let h = handler(res) else { return }
        h.setAcquireFence(res, fd: fd)
    }
    private static let getRelease_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, release in
        guard let res, let client, let h = handler(res) else { return }
        h.getRelease(res, release: WlNewId(client: client, id: release, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_zwp_linux_buffer_release_v1()))
    }
}
