// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_locked_pointer_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ZwpLockedPointerV1Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func setCursorPositionHint(_ resource: UnsafeMutablePointer<wl_resource>, surface_x: Double, surface_y: Double)
    func setRegion(_ resource: UnsafeMutablePointer<wl_resource>, region: UnsafeMutablePointer<wl_resource>?)
}

public extension ZwpLockedPointerV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpLockedPointerV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_locked_pointer_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_locked_pointer_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_locked_pointer_v1_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.set_cursor_position_hint = setCursorPositionHint_impl
        vt.pointee.set_region = setRegion_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendLocked(_ target: UnsafeMutablePointer<wl_resource>) {
        zwp_locked_pointer_v1_send_locked(target)
    }
    public static func sendUnlocked(_ target: UnsafeMutablePointer<wl_resource>) {
        zwp_locked_pointer_v1_send_unlocked(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ZwpLockedPointerV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ZwpLockedPointerV1Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let setCursorPositionHint_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, wl_fixed_t, wl_fixed_t) -> Void = { _, res, surface_x, surface_y in
        guard let res, let h = handler(res) else { return }
        h.setCursorPositionHint(res, surface_x: swift_wayland_fixed_to_double(surface_x), surface_y: swift_wayland_fixed_to_double(surface_y))
    }
    private static let setRegion_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, region in
        guard let res, let h = handler(res) else { return }
        h.setRegion(res, region: region)
    }
}
