// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_primary_selection_device_manager_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ZwpPrimarySelectionDeviceManagerV1Requests: AnyObject {
    func createSource(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId)
    func getDevice(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, seat: UnsafeMutablePointer<wl_resource>?)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ZwpPrimarySelectionDeviceManagerV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpPrimarySelectionDeviceManagerV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_primary_selection_device_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_primary_selection_device_manager_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_primary_selection_device_manager_v1_requests.self, capacity: 1)
        vt.pointee.create_source = createSource_impl
        vt.pointee.get_device = getDevice_impl
        vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ZwpPrimarySelectionDeviceManagerV1Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ZwpPrimarySelectionDeviceManagerV1Requests
    }

    private static let createSource_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res, let client, let h = handler(res) else { return }
        h.createSource(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_zwp_primary_selection_source_v1()))
    }
    private static let getDevice_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, seat in
        guard let res, let client, let h = handler(res) else { return }
        h.getDevice(res, id: WlNewId(client: client, id: id, version: Swift.min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_zwp_primary_selection_device_v1()), seat: seat)
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
}
