// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_primary_selection_device_v1: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol ZwpPrimarySelectionDeviceV1Requests: AnyObject {
    func setSelection(_ resource: UnsafeMutablePointer<wl_resource>, source: UnsafeMutablePointer<wl_resource>?, serial: UInt32)
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ZwpPrimarySelectionDeviceV1Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpPrimarySelectionDeviceV1Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_primary_selection_device_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_primary_selection_device_v1_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_primary_selection_device_v1_requests.self, capacity: 1)
        vt.pointee.set_selection = setSelection_impl
        vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendDataOffer(_ target: UnsafeMutablePointer<wl_resource>, offer: UnsafeMutablePointer<wl_resource>?) {
        zwp_primary_selection_device_v1_send_data_offer(target, offer)
    }
    public static func sendSelection(_ target: UnsafeMutablePointer<wl_resource>, id: UnsafeMutablePointer<wl_resource>?) {
        zwp_primary_selection_device_v1_send_selection(target, id)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZwpPrimarySelectionDeviceV1Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpPrimarySelectionDeviceV1Requests
    }

    private static let setSelection_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, source, serial in
        guard let res, let h = handler(res) else { return }
        h.setSelection(res, source: source, serial: serial)
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
}
