// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_relative_pointer_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZwpRelativePointerV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ZwpRelativePointerV1Server>)
}
public extension ZwpRelativePointerV1Requests {
    func destroy(_ request: WaylandRequest<ZwpRelativePointerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwpRelativePointerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_relative_pointer_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_relative_pointer_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_relative_pointer_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_relative_pointer_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendRelativeMotion(_ target: UnsafeMutablePointer<wl_resource>, utime_hi: UInt32, utime_lo: UInt32, dx: Double, dy: Double, dx_unaccel: Double, dy_unaccel: Double) {
        unsafe zwp_relative_pointer_v1_send_relative_motion(target, utime_hi, utime_lo, swift_wayland_fixed_from_double(dx), swift_wayland_fixed_from_double(dy), swift_wayland_fixed_from_double(dx_unaccel), swift_wayland_fixed_from_double(dy_unaccel))
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpRelativePointerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpRelativePointerV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwpRelativePointerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ZwpRelativePointerV1Server {
    @discardableResult
    func sendRelativeMotion(utime_hi: UInt32, utime_lo: UInt32, dx: Double, dy: Double, dx_unaccel: Double, dy_unaccel: Double) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_relative_pointer_v1_send_relative_motion(target, utime_hi, utime_lo, swift_wayland_fixed_from_double(dx), swift_wayland_fixed_from_double(dy), swift_wayland_fixed_from_double(dx_unaccel), swift_wayland_fixed_from_double(dy_unaccel))
        return true
    }
}
public extension WlNewId where Interface == ZwpRelativePointerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<ZwpRelativePointerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpRelativePointerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpRelativePointerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpRelativePointerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpRelativePointerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpRelativePointerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpRelativePointerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpRelativePointerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}