// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_tablet_tool_v2.

public import WaylandServerC
public import WaylandServer
public import WaylandProtocolTypes
@MainActor public protocol ZwpTabletToolV2Requests: AnyObject {
    func setCursor(_ request: WaylandRequest<ZwpTabletToolV2Server>, serial: UInt32, surface: WaylandBorrowedObject<WlSurfaceServer>?, hotspot_x: Int32, hotspot_y: Int32)
    func destroy(_ request: WaylandRequest<ZwpTabletToolV2Server>)
}
public extension ZwpTabletToolV2Requests {
    func destroy(_ request: WaylandRequest<ZwpTabletToolV2Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwpTabletToolV2Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_tablet_tool_v2()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_tablet_tool_v2_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_tablet_tool_v2_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_tablet_tool_v2_requests.self, capacity: 1)
        unsafe vt.pointee.set_cursor = setCursor_impl
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendType(_ target: UnsafeMutablePointer<wl_resource>, tool_type: ZwpTabletToolV2Type) {
        unsafe zwp_tablet_tool_v2_send_type(target, tool_type.rawValue)
    }
    public static func sendHardwareSerial(_ target: UnsafeMutablePointer<wl_resource>, hardware_serial_hi: UInt32, hardware_serial_lo: UInt32) {
        unsafe zwp_tablet_tool_v2_send_hardware_serial(target, hardware_serial_hi, hardware_serial_lo)
    }
    public static func sendHardwareIdWacom(_ target: UnsafeMutablePointer<wl_resource>, hardware_id_hi: UInt32, hardware_id_lo: UInt32) {
        unsafe zwp_tablet_tool_v2_send_hardware_id_wacom(target, hardware_id_hi, hardware_id_lo)
    }
    public static func sendCapability(_ target: UnsafeMutablePointer<wl_resource>, capability: ZwpTabletToolV2Capability) {
        unsafe zwp_tablet_tool_v2_send_capability(target, capability.rawValue)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwp_tablet_tool_v2_send_done(target)
    }
    public static func sendRemoved(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwp_tablet_tool_v2_send_removed(target)
    }
    public static func sendProximityIn(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32, tablet: UnsafeMutablePointer<wl_resource>?, surface: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_tool_v2_send_proximity_in(target, serial, tablet, surface)
    }
    public static func sendProximityOut(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwp_tablet_tool_v2_send_proximity_out(target)
    }
    public static func sendDown(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32) {
        unsafe zwp_tablet_tool_v2_send_down(target, serial)
    }
    public static func sendUp(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwp_tablet_tool_v2_send_up(target)
    }
    public static func sendMotion(_ target: UnsafeMutablePointer<wl_resource>, x: Double, y: Double) {
        unsafe zwp_tablet_tool_v2_send_motion(target, swift_wayland_fixed_from_double(x), swift_wayland_fixed_from_double(y))
    }
    public static func sendPressure(_ target: UnsafeMutablePointer<wl_resource>, pressure: UInt32) {
        unsafe zwp_tablet_tool_v2_send_pressure(target, pressure)
    }
    public static func sendDistance(_ target: UnsafeMutablePointer<wl_resource>, distance: UInt32) {
        unsafe zwp_tablet_tool_v2_send_distance(target, distance)
    }
    public static func sendTilt(_ target: UnsafeMutablePointer<wl_resource>, tilt_x: Double, tilt_y: Double) {
        unsafe zwp_tablet_tool_v2_send_tilt(target, swift_wayland_fixed_from_double(tilt_x), swift_wayland_fixed_from_double(tilt_y))
    }
    public static func sendRotation(_ target: UnsafeMutablePointer<wl_resource>, degrees: Double) {
        unsafe zwp_tablet_tool_v2_send_rotation(target, swift_wayland_fixed_from_double(degrees))
    }
    public static func sendSlider(_ target: UnsafeMutablePointer<wl_resource>, position: Int32) {
        unsafe zwp_tablet_tool_v2_send_slider(target, position)
    }
    public static func sendWheel(_ target: UnsafeMutablePointer<wl_resource>, degrees: Double, clicks: Int32) {
        unsafe zwp_tablet_tool_v2_send_wheel(target, swift_wayland_fixed_from_double(degrees), clicks)
    }
    public static func sendButton(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32, button: UInt32, state: ZwpTabletToolV2ButtonState) {
        unsafe zwp_tablet_tool_v2_send_button(target, serial, button, state.rawValue)
    }
    public static func sendFrame(_ target: UnsafeMutablePointer<wl_resource>, time: UInt32) {
        unsafe zwp_tablet_tool_v2_send_frame(target, time)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpTabletToolV2Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpTabletToolV2Requests
    }
    private static let setCursor_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, serial, surface, hotspot_x, hotspot_y in
        guard let res = unsafe res, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let _request_surface = unsafe surface
        MainActor.assumeIsolated {
            unsafe requestHandler.setCursor(WaylandRequest<ZwpTabletToolV2Server>(requestResource), serial: serial, surface: _request_surface == nil ? nil : .some(WaylandBorrowedObject<WlSurfaceServer>(_request_surface!)), hotspot_x: hotspot_x, hotspot_y: hotspot_y)
        }
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwpTabletToolV2Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ZwpTabletToolV2Server {
    @discardableResult
    func sendType(tool_type: ZwpTabletToolV2Type) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_type(target, tool_type.rawValue)
        return true
    }
    @discardableResult
    func sendHardwareSerial(hardware_serial_hi: UInt32, hardware_serial_lo: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_hardware_serial(target, hardware_serial_hi, hardware_serial_lo)
        return true
    }
    @discardableResult
    func sendHardwareIdWacom(hardware_id_hi: UInt32, hardware_id_lo: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_hardware_id_wacom(target, hardware_id_hi, hardware_id_lo)
        return true
    }
    @discardableResult
    func sendCapability(capability: ZwpTabletToolV2Capability) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_capability(target, capability.rawValue)
        return true
    }
    @discardableResult
    func sendDone() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_done(target)
        return true
    }
    @discardableResult
    func sendRemoved() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_removed(target)
        return true
    }
    @discardableResult
    func sendProximityIn(serial: UInt32, tablet: WaylandResourceHandle<ZwpTabletV2Server>, surface: WaylandResourceHandle<WlSurfaceServer>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_tabletResource = unsafe tablet.resource else {
            return false
        }
        guard let _event_surfaceResource = unsafe surface.resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_proximity_in(target, serial, _event_tabletResource, _event_surfaceResource)
        return true
    }
    @discardableResult
    func sendProximityOut() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_proximity_out(target)
        return true
    }
    @discardableResult
    func sendDown(serial: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_down(target, serial)
        return true
    }
    @discardableResult
    func sendUp() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_up(target)
        return true
    }
    @discardableResult
    func sendMotion(x: Double, y: Double) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_motion(target, swift_wayland_fixed_from_double(x), swift_wayland_fixed_from_double(y))
        return true
    }
    @discardableResult
    func sendPressure(pressure: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_pressure(target, pressure)
        return true
    }
    @discardableResult
    func sendDistance(distance: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_distance(target, distance)
        return true
    }
    @discardableResult
    func sendTilt(tilt_x: Double, tilt_y: Double) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_tilt(target, swift_wayland_fixed_from_double(tilt_x), swift_wayland_fixed_from_double(tilt_y))
        return true
    }
    @discardableResult
    func sendRotation(degrees: Double) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_rotation(target, swift_wayland_fixed_from_double(degrees))
        return true
    }
    @discardableResult
    func sendSlider(position: Int32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_slider(target, position)
        return true
    }
    @discardableResult
    func sendWheel(degrees: Double, clicks: Int32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_wheel(target, swift_wayland_fixed_from_double(degrees), clicks)
        return true
    }
    @discardableResult
    func sendButton(serial: UInt32, button: UInt32, state: ZwpTabletToolV2ButtonState) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_button(target, serial, button, state.rawValue)
        return true
    }
    @discardableResult
    func sendFrame(time: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_tool_v2_send_frame(target, time)
        return true
    }
}
public extension WaylandRequest where Interface == ZwpTabletToolV2Server {
    func postError(_ code: ZwpTabletToolV2Error, message: String) {
        postError(code: code.rawValue, message: message)
    }
}
public extension WaylandResourceHandle where Interface == ZwpTabletToolV2Server {
    @discardableResult
    func postError(_ code: ZwpTabletToolV2Error, message: String) -> Bool {
        postError(code: code.rawValue, message: message)
    }
}
public extension WlNewId where Interface == ZwpTabletToolV2Server {
    @discardableResult
    @MainActor
    func create<Owner: ZwpTabletToolV2Requests>(
        owner: (WaylandResourceHandle<ZwpTabletToolV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpTabletToolV2Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpTabletToolV2Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZwpTabletToolV2Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpTabletToolV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpTabletToolV2Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZwpTabletToolV2Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpTabletToolV2Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpTabletToolV2Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpTabletToolV2Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}