// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_tablet_pad_group_v2.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZwpTabletPadGroupV2Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ZwpTabletPadGroupV2Server>)
}
public extension ZwpTabletPadGroupV2Requests {
    func destroy(_ request: WaylandRequest<ZwpTabletPadGroupV2Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwpTabletPadGroupV2Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_tablet_pad_group_v2()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_tablet_pad_group_v2_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_tablet_pad_group_v2_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_tablet_pad_group_v2_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendButtons(_ target: UnsafeMutablePointer<wl_resource>, buttons: UnsafeMutablePointer<wl_array>?) {
        unsafe zwp_tablet_pad_group_v2_send_buttons(target, buttons)
    }
    public static func sendRing(_ target: UnsafeMutablePointer<wl_resource>, ring: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_pad_group_v2_send_ring(target, ring)
    }
    public static func sendStrip(_ target: UnsafeMutablePointer<wl_resource>, strip: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_pad_group_v2_send_strip(target, strip)
    }
    public static func sendModes(_ target: UnsafeMutablePointer<wl_resource>, modes: UInt32) {
        unsafe zwp_tablet_pad_group_v2_send_modes(target, modes)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>) {
        unsafe zwp_tablet_pad_group_v2_send_done(target)
    }
    public static func sendModeSwitch(_ target: UnsafeMutablePointer<wl_resource>, time: UInt32, serial: UInt32, mode: UInt32) {
        unsafe zwp_tablet_pad_group_v2_send_mode_switch(target, time, serial, mode)
    }
    public static func sendDial(_ target: UnsafeMutablePointer<wl_resource>, dial: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_pad_group_v2_send_dial(target, dial)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpTabletPadGroupV2Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpTabletPadGroupV2Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwpTabletPadGroupV2Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ZwpTabletPadGroupV2Server {
    var supportsDial: Bool {
        guard let version else {
            return false
        }
        return version >= 2
    }
    @discardableResult
    func sendButtons<ButtonsElement>(buttons: [ButtonsElement]) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        return unsafe withWaylandEventArray(buttons) { _event_buttonsArray in
            unsafe zwp_tablet_pad_group_v2_send_buttons(target, _event_buttonsArray)
            return true
        }
    }
    @discardableResult
    func sendRing(ring: WaylandResourceHandle<ZwpTabletPadRingV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_ringResource = unsafe ring.resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_ring(target, _event_ringResource)
        return true
    }
    @discardableResult
    func sendStrip(strip: WaylandResourceHandle<ZwpTabletPadStripV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_stripResource = unsafe strip.resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_strip(target, _event_stripResource)
        return true
    }
    @discardableResult
    func sendModes(modes: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_modes(target, modes)
        return true
    }
    @discardableResult
    func sendDone() -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_done(target)
        return true
    }
    @discardableResult
    func sendModeSwitch(time: UInt32, serial: UInt32, mode: UInt32) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_mode_switch(target, time, serial, mode)
        return true
    }
    @discardableResult
    func sendDial(dial: WaylandResourceHandle<ZwpTabletPadDialV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        precondition(supportsDial, "zwp_tablet_pad_group_v2.dial requires version 2")
        guard let _event_dialResource = unsafe dial.resource else {
            return false
        }
        unsafe zwp_tablet_pad_group_v2_send_dial(target, _event_dialResource)
        return true
    }
}
public extension WlNewId where Interface == ZwpTabletPadGroupV2Server {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<ZwpTabletPadGroupV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpTabletPadGroupV2Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpTabletPadGroupV2Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpTabletPadGroupV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpTabletPadGroupV2Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpTabletPadGroupV2Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpTabletPadGroupV2Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpTabletPadGroupV2Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}