// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zwp_text_input_v3: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

import WaylandServerC
import WaylandServer

public protocol ZwpTextInputV3Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func enable(_ resource: UnsafeMutablePointer<wl_resource>)
    func disable(_ resource: UnsafeMutablePointer<wl_resource>)
    func setSurroundingText(_ resource: UnsafeMutablePointer<wl_resource>, text: UnsafePointer<CChar>?, cursor: Int32, anchor: Int32)
    func setTextChangeCause(_ resource: UnsafeMutablePointer<wl_resource>, cause: UInt32)
    func setContentType(_ resource: UnsafeMutablePointer<wl_resource>, hint: UInt32, purpose: UInt32)
    func setCursorRectangle(_ resource: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32)
    func commit(_ resource: UnsafeMutablePointer<wl_resource>)
    func setAvailableActions(_ resource: UnsafeMutablePointer<wl_resource>, available_actions: UnsafeMutablePointer<wl_array>?)
    func showInputPanel(_ resource: UnsafeMutablePointer<wl_resource>)
    func hideInputPanel(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ZwpTextInputV3Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZwpTextInputV3Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_text_input_v3_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_text_input_v3_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zwp_text_input_v3_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.enable = enable_impl
        vt.pointee.disable = disable_impl
        vt.pointee.set_surrounding_text = setSurroundingText_impl
        vt.pointee.set_text_change_cause = setTextChangeCause_impl
        vt.pointee.set_content_type = setContentType_impl
        vt.pointee.set_cursor_rectangle = setCursorRectangle_impl
        vt.pointee.commit = commit_impl
        vt.pointee.set_available_actions = setAvailableActions_impl
        vt.pointee.show_input_panel = showInputPanel_impl
        vt.pointee.hide_input_panel = hideInputPanel_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendEnter(_ target: UnsafeMutablePointer<wl_resource>, surface: UnsafeMutablePointer<wl_resource>?) {
        zwp_text_input_v3_send_enter(target, surface)
    }
    public static func sendLeave(_ target: UnsafeMutablePointer<wl_resource>, surface: UnsafeMutablePointer<wl_resource>?) {
        zwp_text_input_v3_send_leave(target, surface)
    }
    public static func sendPreeditString(_ target: UnsafeMutablePointer<wl_resource>, text: UnsafePointer<CChar>?, cursor_begin: Int32, cursor_end: Int32) {
        zwp_text_input_v3_send_preedit_string(target, text, cursor_begin, cursor_end)
    }
    public static func sendCommitString(_ target: UnsafeMutablePointer<wl_resource>, text: UnsafePointer<CChar>?) {
        zwp_text_input_v3_send_commit_string(target, text)
    }
    public static func sendDeleteSurroundingText(_ target: UnsafeMutablePointer<wl_resource>, before_length: UInt32, after_length: UInt32) {
        zwp_text_input_v3_send_delete_surrounding_text(target, before_length, after_length)
    }
    public static func sendDone(_ target: UnsafeMutablePointer<wl_resource>, serial: UInt32) {
        zwp_text_input_v3_send_done(target, serial)
    }
    public static func sendAction(_ target: UnsafeMutablePointer<wl_resource>, action: UInt32, serial: UInt32) {
        zwp_text_input_v3_send_action(target, action, serial)
    }
    public static func sendLanguage(_ target: UnsafeMutablePointer<wl_resource>, language: UnsafePointer<CChar>?) {
        zwp_text_input_v3_send_language(target, language)
    }
    public static func sendPreeditHint(_ target: UnsafeMutablePointer<wl_resource>, start: UInt32, end: UInt32, hint: UInt32) {
        zwp_text_input_v3_send_preedit_hint(target, start, end, hint)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> ZwpTextInputV3Requests? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? ZwpTextInputV3Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let enable_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.enable(res)
    }
    private static let disable_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.disable(res)
    }
    private static let setSurroundingText_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?, Int32, Int32) -> Void = { _, res, text, cursor, anchor in
        guard let res, let h = handler(res) else { return }
        h.setSurroundingText(res, text: text, cursor: cursor, anchor: anchor)
    }
    private static let setTextChangeCause_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, cause in
        guard let res, let h = handler(res) else { return }
        h.setTextChangeCause(res, cause: cause)
    }
    private static let setContentType_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32) -> Void = { _, res, hint, purpose in
        guard let res, let h = handler(res) else { return }
        h.setContentType(res, hint: hint, purpose: purpose)
    }
    private static let setCursorRectangle_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32, Int32, Int32) -> Void = { _, res, x, y, width, height in
        guard let res, let h = handler(res) else { return }
        h.setCursorRectangle(res, x: x, y: y, width: width, height: height)
    }
    private static let commit_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.commit(res)
    }
    private static let setAvailableActions_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_array>?) -> Void = { _, res, available_actions in
        guard let res, let h = handler(res) else { return }
        h.setAvailableActions(res, available_actions: available_actions)
    }
    private static let showInputPanel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.showInputPanel(res)
    }
    private static let hideInputPanel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.hideInputPanel(res)
    }
}
