// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_text_input_manager_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZwpTextInputManagerV1Requests: AnyObject {
    func createTextInput(_ request: WaylandRequest<ZwpTextInputManagerV1Server>, id: WlNewId<ZwpTextInputV1Server>)
}
public enum ZwpTextInputManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_text_input_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_text_input_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_text_input_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_text_input_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.create_text_input = createTextInput_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpTextInputManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpTextInputManagerV1Requests
    }
    private static let createTextInput_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { client, res, id in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        MainActor.assumeIsolated {
            unsafe requestHandler.createTextInput(WaylandRequest<ZwpTextInputManagerV1Server>(requestResource), id: WlNewId<ZwpTextInputV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))))
        }
    }
}
public extension WlNewId where Interface == ZwpTextInputManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ZwpTextInputManagerV1Requests>(
        owner: (WaylandResourceHandle<ZwpTextInputManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpTextInputManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpTextInputManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZwpTextInputManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpTextInputManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpTextInputManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZwpTextInputManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpTextInputManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpTextInputManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpTextInputManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}