// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_tablet_manager_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZwpTabletManagerV1Requests: AnyObject {
    func getTabletSeat(_ request: WaylandRequest<ZwpTabletManagerV1Server>, tablet_seat: WlNewId<ZwpTabletSeatV1Server>, seat: WaylandBorrowedObject<WlSeatServer>)
    func destroy(_ request: WaylandRequest<ZwpTabletManagerV1Server>)
}
public extension ZwpTabletManagerV1Requests {
    func destroy(_ request: WaylandRequest<ZwpTabletManagerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwpTabletManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_tablet_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 1
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_tablet_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_tablet_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_tablet_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.get_tablet_seat = getTabletSeat_impl
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpTabletManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpTabletManagerV1Requests
    }
    private static let getTabletSeat_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, tablet_seat, seat in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_seat = unsafe seat
        MainActor.assumeIsolated {
            unsafe requestHandler.getTabletSeat(WaylandRequest<ZwpTabletManagerV1Server>(requestResource), tablet_seat: WlNewId<ZwpTabletSeatV1Server>(client: requestClient, id: tablet_seat, version: Swift::min(wl_resource_get_version(requestResource), Int32(1))), seat: WaylandBorrowedObject<WlSeatServer>(_request_seat!))
        }
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwpTabletManagerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WlNewId where Interface == ZwpTabletManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ZwpTabletManagerV1Requests>(
        owner: (WaylandResourceHandle<ZwpTabletManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpTabletManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpTabletManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZwpTabletManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpTabletManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpTabletManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZwpTabletManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpTabletManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpTabletManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpTabletManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}