// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zwp_tablet_seat_v2.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZwpTabletSeatV2Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ZwpTabletSeatV2Server>)
}
public extension ZwpTabletSeatV2Requests {
    func destroy(_ request: WaylandRequest<ZwpTabletSeatV2Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZwpTabletSeatV2Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zwp_tablet_seat_v2()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zwp_tablet_seat_v2_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zwp_tablet_seat_v2_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zwp_tablet_seat_v2_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    public static func sendTabletAdded(_ target: UnsafeMutablePointer<wl_resource>, id: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_seat_v2_send_tablet_added(target, id)
    }
    public static func sendToolAdded(_ target: UnsafeMutablePointer<wl_resource>, id: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_seat_v2_send_tool_added(target, id)
    }
    public static func sendPadAdded(_ target: UnsafeMutablePointer<wl_resource>, id: UnsafeMutablePointer<wl_resource>?) {
        unsafe zwp_tablet_seat_v2_send_pad_added(target, id)
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZwpTabletSeatV2Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZwpTabletSeatV2Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZwpTabletSeatV2Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
}
public extension WaylandResourceHandle where Interface == ZwpTabletSeatV2Server {
    @discardableResult
    func sendTabletAdded(id: WaylandResourceHandle<ZwpTabletV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_idResource = unsafe id.resource else {
            return false
        }
        unsafe zwp_tablet_seat_v2_send_tablet_added(target, _event_idResource)
        return true
    }
    @discardableResult
    func sendToolAdded(id: WaylandResourceHandle<ZwpTabletToolV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_idResource = unsafe id.resource else {
            return false
        }
        unsafe zwp_tablet_seat_v2_send_tool_added(target, _event_idResource)
        return true
    }
    @discardableResult
    func sendPadAdded(id: WaylandResourceHandle<ZwpTabletPadV2Server>) -> Bool {
        guard let target = unsafe resource else {
            return false
        }
        guard let _event_idResource = unsafe id.resource else {
            return false
        }
        unsafe zwp_tablet_seat_v2_send_pad_added(target, _event_idResource)
        return true
    }
}
public extension WlNewId where Interface == ZwpTabletSeatV2Server {
    @discardableResult
    @MainActor
    func create<Owner: AnyObject>(
        owner: (WaylandResourceHandle<ZwpTabletSeatV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZwpTabletSeatV2Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZwpTabletSeatV2Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: AnyObject>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZwpTabletSeatV2Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZwpTabletSeatV2Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: AnyObject>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZwpTabletSeatV2Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZwpTabletSeatV2Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZwpTabletSeatV2Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}