// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zxdg_importer_v2: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
public import WaylandServer

public protocol ZxdgImporterV2Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func importToplevel(_ resource: UnsafeMutablePointer<wl_resource>, id: WlNewId, handle: UnsafePointer<CChar>?)
}

public extension ZxdgImporterV2Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZxdgImporterV2Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zxdg_importer_v2_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zxdg_importer_v2_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zxdg_importer_v2_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.import_toplevel = importToplevel_impl
        return UnsafeRawPointer(raw)
    }()

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZxdgImporterV2Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZxdgImporterV2Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let importToplevel_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafePointer<CChar>?) -> Void = { client, res, id, handle in
        guard let res, let client, let h = handler(res) else { return }
        h.importToplevel(res, id: WlNewId(client: client, id: id, version: Swift::min(wl_resource_get_version(res), Int32(1)), interface: swift_wayland_iface_zxdg_imported_v2()), handle: handle)
    }
}
