// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zxdg_toplevel_v6: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol ZxdgToplevelV6Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func setParent(_ resource: UnsafeMutablePointer<wl_resource>, parent: UnsafeMutablePointer<wl_resource>?)
    func setTitle(_ resource: UnsafeMutablePointer<wl_resource>, title: UnsafePointer<CChar>?)
    func setAppId(_ resource: UnsafeMutablePointer<wl_resource>, app_id: UnsafePointer<CChar>?)
    func showWindowMenu(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32, x: Int32, y: Int32)
    func move(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32)
    func resize(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32, edges: UInt32)
    func setMaxSize(_ resource: UnsafeMutablePointer<wl_resource>, width: Int32, height: Int32)
    func setMinSize(_ resource: UnsafeMutablePointer<wl_resource>, width: Int32, height: Int32)
    func setMaximized(_ resource: UnsafeMutablePointer<wl_resource>)
    func unsetMaximized(_ resource: UnsafeMutablePointer<wl_resource>)
    func setFullscreen(_ resource: UnsafeMutablePointer<wl_resource>, output: UnsafeMutablePointer<wl_resource>?)
    func unsetFullscreen(_ resource: UnsafeMutablePointer<wl_resource>)
    func setMinimized(_ resource: UnsafeMutablePointer<wl_resource>)
}

public extension ZxdgToplevelV6Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZxdgToplevelV6Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zxdg_toplevel_v6_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zxdg_toplevel_v6_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zxdg_toplevel_v6_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.set_parent = setParent_impl
        vt.pointee.set_title = setTitle_impl
        vt.pointee.set_app_id = setAppId_impl
        vt.pointee.show_window_menu = showWindowMenu_impl
        vt.pointee.move = move_impl
        vt.pointee.resize = resize_impl
        vt.pointee.set_max_size = setMaxSize_impl
        vt.pointee.set_min_size = setMinSize_impl
        vt.pointee.set_maximized = setMaximized_impl
        vt.pointee.unset_maximized = unsetMaximized_impl
        vt.pointee.set_fullscreen = setFullscreen_impl
        vt.pointee.unset_fullscreen = unsetFullscreen_impl
        vt.pointee.set_minimized = setMinimized_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendConfigure(_ target: UnsafeMutablePointer<wl_resource>, width: Int32, height: Int32, states: UnsafeMutablePointer<wl_array>?) {
        zxdg_toplevel_v6_send_configure(target, width, height, states)
    }
    public static func sendClose(_ target: UnsafeMutablePointer<wl_resource>) {
        zxdg_toplevel_v6_send_close(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZxdgToplevelV6Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZxdgToplevelV6Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let setParent_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, parent in
        guard let res, let h = handler(res) else { return }
        h.setParent(res, parent: parent)
    }
    private static let setTitle_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, title in
        guard let res, let h = handler(res) else { return }
        h.setTitle(res, title: title)
    }
    private static let setAppId_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafePointer<CChar>?) -> Void = { _, res, app_id in
        guard let res, let h = handler(res) else { return }
        h.setAppId(res, app_id: app_id)
    }
    private static let showWindowMenu_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32, Int32, Int32) -> Void = { _, res, seat, serial, x, y in
        guard let res, let h = handler(res) else { return }
        h.showWindowMenu(res, seat: seat, serial: serial, x: x, y: y)
    }
    private static let move_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, seat, serial in
        guard let res, let h = handler(res) else { return }
        h.move(res, seat: seat, serial: serial)
    }
    private static let resize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32, UInt32) -> Void = { _, res, seat, serial, edges in
        guard let res, let h = handler(res) else { return }
        h.resize(res, seat: seat, serial: serial, edges: edges)
    }
    private static let setMaxSize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, width, height in
        guard let res, let h = handler(res) else { return }
        h.setMaxSize(res, width: width, height: height)
    }
    private static let setMinSize_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, Int32, Int32) -> Void = { _, res, width, height in
        guard let res, let h = handler(res) else { return }
        h.setMinSize(res, width: width, height: height)
    }
    private static let setMaximized_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setMaximized(res)
    }
    private static let unsetMaximized_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.unsetMaximized(res)
    }
    private static let setFullscreen_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res, output in
        guard let res, let h = handler(res) else { return }
        h.setFullscreen(res, output: output)
    }
    private static let unsetFullscreen_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.unsetFullscreen(res)
    }
    private static let setMinimized_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res, let h = handler(res) else { return }
        h.setMinimized(res)
    }
}
