// Generated by SwiftWaylandGen. Do not edit.
//
// Typed server dispatch for zxdg_popup_v6: a handler protocol (one method per request), the
// request vtable + owner recovery + arg marshalling, and typed event senders.

public import WaylandServerC
import WaylandServer

public protocol ZxdgPopupV6Requests: AnyObject {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>)
    func grab(_ resource: UnsafeMutablePointer<wl_resource>, seat: UnsafeMutablePointer<wl_resource>?, serial: UInt32)
}

public extension ZxdgPopupV6Requests {
    func destroy(_ resource: UnsafeMutablePointer<wl_resource>) { wl_resource_destroy(resource) }
}

public enum ZxdgPopupV6Server {
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zxdg_popup_v6_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zxdg_popup_v6_requests>.alignment)
        raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = raw.bindMemory(to: swift_wayland_zxdg_popup_v6_requests.self, capacity: 1)
        vt.pointee.destroy = destroy_impl
        vt.pointee.grab = grab_impl
        return UnsafeRawPointer(raw)
    }()

    public static func sendConfigure(_ target: UnsafeMutablePointer<wl_resource>, x: Int32, y: Int32, width: Int32, height: Int32) {
        zxdg_popup_v6_send_configure(target, x, y, width, height)
    }
    public static func sendPopupDone(_ target: UnsafeMutablePointer<wl_resource>) {
        zxdg_popup_v6_send_popup_done(target)
    }

    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> (any ZxdgPopupV6Requests)? {
        guard let ud = wl_resource_get_user_data(res) else { return nil }
        return Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZxdgPopupV6Requests
    }

    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res else { return }
        if let h = handler(res) { h.destroy(res) } else { wl_resource_destroy(res) }
    }
    private static let grab_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UnsafeMutablePointer<wl_resource>?, UInt32) -> Void = { _, res, seat, serial in
        guard let res, let h = handler(res) else { return }
        h.grab(res, seat: seat, serial: serial)
    }
}
