// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zxdg_output_manager_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZxdgOutputManagerV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ZxdgOutputManagerV1Server>)
    func getXdgOutput(_ request: WaylandRequest<ZxdgOutputManagerV1Server>, id: WlNewId<ZxdgOutputV1Server>, output: WaylandBorrowedObject<WlOutputServer>)
}
public extension ZxdgOutputManagerV1Requests {
    func destroy(_ request: WaylandRequest<ZxdgOutputManagerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZxdgOutputManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zxdg_output_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 3
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zxdg_output_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zxdg_output_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zxdg_output_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.get_xdg_output = getXdgOutput_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZxdgOutputManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZxdgOutputManagerV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZxdgOutputManagerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let getXdgOutput_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, output in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_output = unsafe output
        MainActor.assumeIsolated {
            unsafe requestHandler.getXdgOutput(WaylandRequest<ZxdgOutputManagerV1Server>(requestResource), id: WlNewId<ZxdgOutputV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(3))), output: WaylandBorrowedObject<WlOutputServer>(_request_output!))
        }
    }
}
public extension WlNewId where Interface == ZxdgOutputManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ZxdgOutputManagerV1Requests>(
        owner: (WaylandResourceHandle<ZxdgOutputManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZxdgOutputManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZxdgOutputManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZxdgOutputManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZxdgOutputManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZxdgOutputManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZxdgOutputManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZxdgOutputManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZxdgOutputManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZxdgOutputManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}