// Generated by SwiftWaylandGen. Do not edit.
// Typed server descriptor and dispatch for zxdg_decoration_manager_v1.

public import WaylandServerC
public import WaylandServer
@MainActor public protocol ZxdgDecorationManagerV1Requests: AnyObject {
    func destroy(_ request: WaylandRequest<ZxdgDecorationManagerV1Server>)
    func getToplevelDecoration(_ request: WaylandRequest<ZxdgDecorationManagerV1Server>, id: WlNewId<ZxdgToplevelDecorationV1Server>, toplevel: WaylandBorrowedObject<XdgToplevelServer>)
}
public extension ZxdgDecorationManagerV1Requests {
    func destroy(_ request: WaylandRequest<ZxdgDecorationManagerV1Server>) {
        unsafe wl_resource_destroy(request.resource)
    }
}
public enum ZxdgDecorationManagerV1Server: WaylandServerInterface {
    public nonisolated(unsafe) static let interface = unsafe swift_wayland_iface_zxdg_decoration_manager_v1()
    public nonisolated static let maximumVersion: Int32 = 2
    public nonisolated(unsafe) static let vtable: UnsafeRawPointer = {
        let size = MemoryLayout<swift_wayland_zxdg_decoration_manager_v1_requests>.stride
        let raw = UnsafeMutableRawPointer.allocate(
            byteCount: size, alignment: MemoryLayout<swift_wayland_zxdg_decoration_manager_v1_requests>.alignment)
        unsafe raw.initializeMemory(as: UInt8.self, repeating: 0, count: size)
        let vt = unsafe raw.bindMemory(to: swift_wayland_zxdg_decoration_manager_v1_requests.self, capacity: 1)
        unsafe vt.pointee.destroy = destroy_impl
        unsafe vt.pointee.get_toplevel_decoration = getToplevelDecoration_impl
        return UnsafeRawPointer(raw)
    }()
    public nonisolated static func requestVtable() -> UnsafeRawPointer? {
        unsafe vtable
    }
    private static func handler(_ res: UnsafeMutablePointer<wl_resource>) -> any ZxdgDecorationManagerV1Requests? {
        guard let ud = unsafe wl_resource_get_user_data(res) else {
            return nil
        }
        return unsafe Unmanaged<AnyObject>.fromOpaque(ud).takeUnretainedValue() as? any ZxdgDecorationManagerV1Requests
    }
    private static let destroy_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?) -> Void = { _, res in
        guard let res = unsafe res else {
            return
        }
        if let h = unsafe handler(res) {
            nonisolated(unsafe) let requestHandler = h
            nonisolated(unsafe) let requestResource = unsafe res
            MainActor.assumeIsolated {
                unsafe requestHandler.destroy(WaylandRequest<ZxdgDecorationManagerV1Server>(requestResource))
            }
        } else {
            unsafe wl_resource_destroy(res)
        }
    }
    private static let getToplevelDecoration_impl: @convention(c) (OpaquePointer?, UnsafeMutablePointer<wl_resource>?, UInt32, UnsafeMutablePointer<wl_resource>?) -> Void = { client, res, id, toplevel in
        guard let res = unsafe res, let client = unsafe client, let h = unsafe handler(res) else {
            return
        }
        nonisolated(unsafe) let requestHandler = h
        nonisolated(unsafe) let requestResource = unsafe res
        nonisolated(unsafe) let requestClient = unsafe client
        nonisolated(unsafe) let _request_toplevel = unsafe toplevel
        MainActor.assumeIsolated {
            unsafe requestHandler.getToplevelDecoration(WaylandRequest<ZxdgDecorationManagerV1Server>(requestResource), id: WlNewId<ZxdgToplevelDecorationV1Server>(client: requestClient, id: id, version: Swift::min(wl_resource_get_version(requestResource), Int32(2))), toplevel: WaylandBorrowedObject<XdgToplevelServer>(_request_toplevel!))
        }
    }
}
public extension WlNewId where Interface == ZxdgDecorationManagerV1Server {
    @discardableResult
    @MainActor
    func create<Owner: ZxdgDecorationManagerV1Requests>(
        owner: (WaylandResourceHandle<ZxdgDecorationManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe _create(vtable: ZxdgDecorationManagerV1Server.requestVtable(), owner: owner, installed: installed)
    }
}
public extension ZxdgDecorationManagerV1Server {
    @discardableResult
    @MainActor
    static func createResource<Owner: ZxdgDecorationManagerV1Requests>(
        client: OpaquePointer,
        version: Int32,
        id: UInt32 = 0,
        owner: (WaylandResourceHandle<ZxdgDecorationManagerV1Server>) -> Owner?,
        installed: (Owner) -> Void = { _ in
        }
    ) -> Owner? {
        unsafe WaylandResource.create(
            client: client, interface: ZxdgDecorationManagerV1Server.self,
            version: Swift.min(version, maximumVersion), id: id,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
    @MainActor
    static func global<Implementation: AnyObject, Owner: ZxdgDecorationManagerV1Requests>(
        implementation: Implementation,
        advertisedVersion: Int32 = maximumVersion,
        owner: @escaping (Implementation, WaylandResourceHandle<ZxdgDecorationManagerV1Server>) -> Owner?,
        installed: @escaping (Implementation, Owner, WaylandResourceHandle<ZxdgDecorationManagerV1Server>) -> Void = { _, _, _ in
        }
    ) -> WaylandGlobalSpecification<ZxdgDecorationManagerV1Server> {
        unsafe WaylandGlobalSpecification(
            implementation: implementation,
            advertisedVersion: advertisedVersion,
            vtable: requestVtable(), owner: owner,
            installed: installed)
    }
}