public let androidRuntimeRequiredKernelModules = [
    "binder_linux",
    "erofs",
    // Android netd uses the legacy xtables ABI inside the container network
    // namespace. Load its table and rule modules from the initial namespace:
    // an unprivileged user namespace cannot trigger host module autoloading.
    "ip_tables",
    "ip6_tables",
    "iptable_filter",
    "ip6table_filter",
    "iptable_mangle",
    "ip6table_mangle",
    "iptable_raw",
    "ip6table_raw",
    "iptable_nat",
    "ip6table_nat",
    "xt_connmark",
    "xt_conntrack",
    "xt_CT",
    "xt_state",
    "xt_mark",
    "xt_NFLOG",
    "nfnetlink_log",
    "ipt_REJECT",
    "ip6t_REJECT",
    "xt_TCPMSS",
    "xt_u32",
    "xt_tcpudp",
    "xt_multiport",
    "xt_owner",
    "xt_policy",
    "xt_quota",
    "ipt_rpfilter",
    "ip6t_rpfilter",
    "xt_bpf",
    "xt_IDLETIMER",
    "xt_MASQUERADE",
    "xt_socket",
    "xt_comment",
    "xt_limit",
]
