// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for ext_image_copy_capture_session_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ExtImageCopyCaptureSessionV1Events: AnyObject {
    func bufferSize(_ proxy: OpaquePointer, width: UInt32, height: UInt32)
    func shmFormat(_ proxy: OpaquePointer, format: UInt32)
    func dmabufDevice(_ proxy: OpaquePointer, device: UnsafeMutablePointer<wl_array>?)
    func dmabufFormat(_ proxy: OpaquePointer, format: UInt32, modifiers: UnsafeMutablePointer<wl_array>?)
    func done(_ proxy: OpaquePointer)
    func stopped(_ proxy: OpaquePointer)
}

public enum ExtImageCopyCaptureSessionV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<ext_image_copy_capture_session_v1_listener> = {
        let p = UnsafeMutablePointer<ext_image_copy_capture_session_v1_listener>.allocate(capacity: 1)
        p.initialize(to: ext_image_copy_capture_session_v1_listener())
        p.pointee.buffer_size = bufferSize_impl
        p.pointee.shm_format = shmFormat_impl
        p.pointee.dmabuf_device = dmabufDevice_impl
        p.pointee.dmabuf_format = dmabufFormat_impl
        p.pointee.done = done_impl
        p.pointee.stopped = stopped_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        ext_image_copy_capture_session_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ExtImageCopyCaptureSessionV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ExtImageCopyCaptureSessionV1Events
    }

    private static let bufferSize_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32) -> Void = { data, proxy, width, height in
        guard let data, let proxy, let h = handler(data) else { return }
        h.bufferSize(proxy, width: width, height: height)
    }
    private static let shmFormat_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, format in
        guard let data, let proxy, let h = handler(data) else { return }
        h.shmFormat(proxy, format: format)
    }
    private static let dmabufDevice_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafeMutablePointer<wl_array>?) -> Void = { data, proxy, device in
        guard let data, let proxy, let h = handler(data) else { return }
        h.dmabufDevice(proxy, device: device)
    }
    private static let dmabufFormat_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UnsafeMutablePointer<wl_array>?) -> Void = { data, proxy, format, modifiers in
        guard let data, let proxy, let h = handler(data) else { return }
        h.dmabufFormat(proxy, format: format, modifiers: modifiers)
    }
    private static let done_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.done(proxy)
    }
    private static let stopped_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.stopped(proxy)
    }
}
