// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for ext_image_copy_capture_cursor_session_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ExtImageCopyCaptureCursorSessionV1Events: AnyObject {
    func enter(_ proxy: OpaquePointer)
    func leave(_ proxy: OpaquePointer)
    func position(_ proxy: OpaquePointer, x: Int32, y: Int32)
    func hotspot(_ proxy: OpaquePointer, x: Int32, y: Int32)
}

public enum ExtImageCopyCaptureCursorSessionV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<ext_image_copy_capture_cursor_session_v1_listener> = {
        let p = UnsafeMutablePointer<ext_image_copy_capture_cursor_session_v1_listener>.allocate(capacity: 1)
        p.initialize(to: ext_image_copy_capture_cursor_session_v1_listener())
        p.pointee.enter = enter_impl
        p.pointee.leave = leave_impl
        p.pointee.position = position_impl
        p.pointee.hotspot = hotspot_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        ext_image_copy_capture_cursor_session_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ExtImageCopyCaptureCursorSessionV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ExtImageCopyCaptureCursorSessionV1Events
    }

    private static let enter_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.enter(proxy)
    }
    private static let leave_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.leave(proxy)
    }
    private static let position_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32, Int32) -> Void = { data, proxy, x, y in
        guard let data, let proxy, let h = handler(data) else { return }
        h.position(proxy, x: x, y: y)
    }
    private static let hotspot_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32, Int32) -> Void = { data, proxy, x, y in
        guard let data, let proxy, let h = handler(data) else { return }
        h.hotspot(proxy, x: x, y: y)
    }
}
