// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for ext_idle_notification_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ExtIdleNotificationV1Events: AnyObject {
    func idled(_ proxy: OpaquePointer)
    func resumed(_ proxy: OpaquePointer)
}

public enum ExtIdleNotificationV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<ext_idle_notification_v1_listener> = {
        let p = UnsafeMutablePointer<ext_idle_notification_v1_listener>.allocate(capacity: 1)
        p.initialize(to: ext_idle_notification_v1_listener())
        p.pointee.idled = idled_impl
        p.pointee.resumed = resumed_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        ext_idle_notification_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ExtIdleNotificationV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ExtIdleNotificationV1Events
    }

    private static let idled_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.idled(proxy)
    }
    private static let resumed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.resumed(proxy)
    }
}
