// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for ext_image_copy_capture_frame_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ExtImageCopyCaptureFrameV1Events: AnyObject {
    func transform(_ proxy: OpaquePointer, transform: UInt32)
    func damage(_ proxy: OpaquePointer, x: Int32, y: Int32, width: Int32, height: Int32)
    func presentationTime(_ proxy: OpaquePointer, tv_sec_hi: UInt32, tv_sec_lo: UInt32, tv_nsec: UInt32)
    func ready(_ proxy: OpaquePointer)
    func failed(_ proxy: OpaquePointer, reason: UInt32)
}

public enum ExtImageCopyCaptureFrameV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<ext_image_copy_capture_frame_v1_listener> = {
        let p = UnsafeMutablePointer<ext_image_copy_capture_frame_v1_listener>.allocate(capacity: 1)
        p.initialize(to: ext_image_copy_capture_frame_v1_listener())
        p.pointee.transform = transform_impl
        p.pointee.damage = damage_impl
        p.pointee.presentation_time = presentationTime_impl
        p.pointee.ready = ready_impl
        p.pointee.failed = failed_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        ext_image_copy_capture_frame_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ExtImageCopyCaptureFrameV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ExtImageCopyCaptureFrameV1Events
    }

    private static let transform_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, transform in
        guard let data, let proxy, let h = handler(data) else { return }
        h.transform(proxy, transform: transform)
    }
    private static let damage_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32, Int32, Int32, Int32) -> Void = { data, proxy, x, y, width, height in
        guard let data, let proxy, let h = handler(data) else { return }
        h.damage(proxy, x: x, y: y, width: width, height: height)
    }
    private static let presentationTime_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32, UInt32) -> Void = { data, proxy, tv_sec_hi, tv_sec_lo, tv_nsec in
        guard let data, let proxy, let h = handler(data) else { return }
        h.presentationTime(proxy, tv_sec_hi: tv_sec_hi, tv_sec_lo: tv_sec_lo, tv_nsec: tv_nsec)
    }
    private static let ready_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.ready(proxy)
    }
    private static let failed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, reason in
        guard let data, let proxy, let h = handler(data) else { return }
        h.failed(proxy, reason: reason)
    }
}
