// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for ext_transient_seat_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ExtTransientSeatV1Events: AnyObject {
    func ready(_ proxy: OpaquePointer, global_name: UInt32)
    func denied(_ proxy: OpaquePointer)
}

public enum ExtTransientSeatV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<ext_transient_seat_v1_listener> = {
        let p = UnsafeMutablePointer<ext_transient_seat_v1_listener>.allocate(capacity: 1)
        p.initialize(to: ext_transient_seat_v1_listener())
        p.pointee.ready = ready_impl
        p.pointee.denied = denied_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        ext_transient_seat_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ExtTransientSeatV1Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ExtTransientSeatV1Events
    }

    private static let ready_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, global_name in
        guard let data, let proxy, let h = handler(data) else { return }
        h.ready(proxy, global_name: global_name)
    }
    private static let denied_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.denied(proxy)
    }
}
