// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for wl_buffer: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol WlBufferEvents: AnyObject {
    func release(_ proxy: OpaquePointer)
}

public enum WlBufferClient {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<wl_buffer_listener> = {
        let p = UnsafeMutablePointer<wl_buffer_listener>.allocate(capacity: 1)
        p.initialize(to: wl_buffer_listener())
        p.pointee.release = release_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        wl_buffer_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any WlBufferEvents)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any WlBufferEvents
    }

    private static let release_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.release(proxy)
    }
}
