// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for wl_touch: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol WlTouchEvents: AnyObject {
    func down(_ proxy: OpaquePointer, serial: UInt32, time: UInt32, surface: OpaquePointer?, id: Int32, x: Double, y: Double)
    func up(_ proxy: OpaquePointer, serial: UInt32, time: UInt32, id: Int32)
    func motion(_ proxy: OpaquePointer, time: UInt32, id: Int32, x: Double, y: Double)
    func frame(_ proxy: OpaquePointer)
    func cancel(_ proxy: OpaquePointer)
    func shape(_ proxy: OpaquePointer, id: Int32, major: Double, minor: Double)
    func orientation(_ proxy: OpaquePointer, id: Int32, orientation: Double)
}

public enum WlTouchClient {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<wl_touch_listener> = {
        let p = UnsafeMutablePointer<wl_touch_listener>.allocate(capacity: 1)
        p.initialize(to: wl_touch_listener())
        p.pointee.down = down_impl
        p.pointee.up = up_impl
        p.pointee.motion = motion_impl
        p.pointee.frame = frame_impl
        p.pointee.cancel = cancel_impl
        p.pointee.shape = shape_impl
        p.pointee.orientation = orientation_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        wl_touch_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> WlTouchEvents? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? WlTouchEvents
    }

    private static let down_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32, OpaquePointer?, Int32, wl_fixed_t, wl_fixed_t) -> Void = { data, proxy, serial, time, surface, id, x, y in
        guard let data, let proxy, let h = handler(data) else { return }
        h.down(proxy, serial: serial, time: time, surface: surface, id: id, x: swift_wayland_fixed_to_double(x), y: swift_wayland_fixed_to_double(y))
    }
    private static let up_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32, Int32) -> Void = { data, proxy, serial, time, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.up(proxy, serial: serial, time: time, id: id)
    }
    private static let motion_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, Int32, wl_fixed_t, wl_fixed_t) -> Void = { data, proxy, time, id, x, y in
        guard let data, let proxy, let h = handler(data) else { return }
        h.motion(proxy, time: time, id: id, x: swift_wayland_fixed_to_double(x), y: swift_wayland_fixed_to_double(y))
    }
    private static let frame_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.frame(proxy)
    }
    private static let cancel_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.cancel(proxy)
    }
    private static let shape_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32, wl_fixed_t, wl_fixed_t) -> Void = { data, proxy, id, major, minor in
        guard let data, let proxy, let h = handler(data) else { return }
        h.shape(proxy, id: id, major: swift_wayland_fixed_to_double(major), minor: swift_wayland_fixed_to_double(minor))
    }
    private static let orientation_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32, wl_fixed_t) -> Void = { data, proxy, id, orientation in
        guard let data, let proxy, let h = handler(data) else { return }
        h.orientation(proxy, id: id, orientation: swift_wayland_fixed_to_double(orientation))
    }
}
