// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for wp_color_manager_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol WpColorManagerV1Events: AnyObject {
    func supportedIntent(_ proxy: OpaquePointer, render_intent: UInt32)
    func supportedFeature(_ proxy: OpaquePointer, feature: UInt32)
    func supportedTfNamed(_ proxy: OpaquePointer, tf: UInt32)
    func supportedPrimariesNamed(_ proxy: OpaquePointer, primaries: UInt32)
    func done(_ proxy: OpaquePointer)
}

public enum WpColorManagerV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<wp_color_manager_v1_listener> = {
        let p = UnsafeMutablePointer<wp_color_manager_v1_listener>.allocate(capacity: 1)
        p.initialize(to: wp_color_manager_v1_listener())
        p.pointee.supported_intent = supportedIntent_impl
        p.pointee.supported_feature = supportedFeature_impl
        p.pointee.supported_tf_named = supportedTfNamed_impl
        p.pointee.supported_primaries_named = supportedPrimariesNamed_impl
        p.pointee.done = done_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        wp_color_manager_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> WpColorManagerV1Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? WpColorManagerV1Events
    }

    private static let supportedIntent_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, render_intent in
        guard let data, let proxy, let h = handler(data) else { return }
        h.supportedIntent(proxy, render_intent: render_intent)
    }
    private static let supportedFeature_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, feature in
        guard let data, let proxy, let h = handler(data) else { return }
        h.supportedFeature(proxy, feature: feature)
    }
    private static let supportedTfNamed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, tf in
        guard let data, let proxy, let h = handler(data) else { return }
        h.supportedTfNamed(proxy, tf: tf)
    }
    private static let supportedPrimariesNamed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, primaries in
        guard let data, let proxy, let h = handler(data) else { return }
        h.supportedPrimariesNamed(proxy, primaries: primaries)
    }
    private static let done_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.done(proxy)
    }
}
