// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for wp_drm_lease_device_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol WpDrmLeaseDeviceV1Events: AnyObject {
    func drmFd(_ proxy: OpaquePointer, fd: Int32)
    func connector(_ proxy: OpaquePointer, id: OpaquePointer?)
    func done(_ proxy: OpaquePointer)
    func released(_ proxy: OpaquePointer)
}

public enum WpDrmLeaseDeviceV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<wp_drm_lease_device_v1_listener> = {
        let p = UnsafeMutablePointer<wp_drm_lease_device_v1_listener>.allocate(capacity: 1)
        p.initialize(to: wp_drm_lease_device_v1_listener())
        p.pointee.drm_fd = drmFd_impl
        p.pointee.connector = connector_impl
        p.pointee.done = done_impl
        p.pointee.released = released_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        wp_drm_lease_device_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any WpDrmLeaseDeviceV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any WpDrmLeaseDeviceV1Events
    }

    private static let drmFd_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32) -> Void = { data, proxy, fd in
        guard let data, let proxy, let h = handler(data) else { return }
        h.drmFd(proxy, fd: fd)
    }
    private static let connector_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.connector(proxy, id: id)
    }
    private static let done_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.done(proxy)
    }
    private static let released_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.released(proxy)
    }
}
