// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwlr_foreign_toplevel_manager_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwlrForeignToplevelManagerV1Events: AnyObject {
    func toplevel(_ proxy: OpaquePointer, toplevel: OpaquePointer?)
    func finished(_ proxy: OpaquePointer)
}

public enum ZwlrForeignToplevelManagerV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwlr_foreign_toplevel_manager_v1_listener> = {
        let p = UnsafeMutablePointer<zwlr_foreign_toplevel_manager_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwlr_foreign_toplevel_manager_v1_listener())
        p.pointee.toplevel = toplevel_impl
        p.pointee.finished = finished_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwlr_foreign_toplevel_manager_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwlrForeignToplevelManagerV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwlrForeignToplevelManagerV1Events
    }

    private static let toplevel_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, toplevel in
        guard let data, let proxy, let h = handler(data) else { return }
        h.toplevel(proxy, toplevel: toplevel)
    }
    private static let finished_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.finished(proxy)
    }
}
