// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwlr_output_configuration_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwlrOutputConfigurationV1Events: AnyObject {
    func succeeded(_ proxy: OpaquePointer)
    func failed(_ proxy: OpaquePointer)
    func cancelled(_ proxy: OpaquePointer)
}

public enum ZwlrOutputConfigurationV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwlr_output_configuration_v1_listener> = {
        let p = UnsafeMutablePointer<zwlr_output_configuration_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwlr_output_configuration_v1_listener())
        p.pointee.succeeded = succeeded_impl
        p.pointee.failed = failed_impl
        p.pointee.cancelled = cancelled_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwlr_output_configuration_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwlrOutputConfigurationV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwlrOutputConfigurationV1Events
    }

    private static let succeeded_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.succeeded(proxy)
    }
    private static let failed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.failed(proxy)
    }
    private static let cancelled_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.cancelled(proxy)
    }
}
