// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_fullscreen_shell_mode_feedback_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ZwpFullscreenShellModeFeedbackV1Events: AnyObject {
    func modeSuccessful(_ proxy: OpaquePointer)
    func modeFailed(_ proxy: OpaquePointer)
    func presentCancelled(_ proxy: OpaquePointer)
}

public enum ZwpFullscreenShellModeFeedbackV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_fullscreen_shell_mode_feedback_v1_listener> = {
        let p = UnsafeMutablePointer<zwp_fullscreen_shell_mode_feedback_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_fullscreen_shell_mode_feedback_v1_listener())
        p.pointee.mode_successful = modeSuccessful_impl
        p.pointee.mode_failed = modeFailed_impl
        p.pointee.present_cancelled = presentCancelled_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_fullscreen_shell_mode_feedback_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ZwpFullscreenShellModeFeedbackV1Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ZwpFullscreenShellModeFeedbackV1Events
    }

    private static let modeSuccessful_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.modeSuccessful(proxy)
    }
    private static let modeFailed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.modeFailed(proxy)
    }
    private static let presentCancelled_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.presentCancelled(proxy)
    }
}
