// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_linux_buffer_release_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwpLinuxBufferReleaseV1Events: AnyObject {
    func fencedRelease(_ proxy: OpaquePointer, fence: Int32)
    func immediateRelease(_ proxy: OpaquePointer)
}

public enum ZwpLinuxBufferReleaseV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_linux_buffer_release_v1_listener> = {
        let p = UnsafeMutablePointer<zwp_linux_buffer_release_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_linux_buffer_release_v1_listener())
        p.pointee.fenced_release = fencedRelease_impl
        p.pointee.immediate_release = immediateRelease_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_linux_buffer_release_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwpLinuxBufferReleaseV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwpLinuxBufferReleaseV1Events
    }

    private static let fencedRelease_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, Int32) -> Void = { data, proxy, fence in
        guard let data, let proxy, let h = handler(data) else { return }
        h.fencedRelease(proxy, fence: fence)
    }
    private static let immediateRelease_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.immediateRelease(proxy)
    }
}
