// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_primary_selection_offer_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ZwpPrimarySelectionOfferV1Events: AnyObject {
    func offer(_ proxy: OpaquePointer, mime_type: UnsafePointer<CChar>?)
}

public enum ZwpPrimarySelectionOfferV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_primary_selection_offer_v1_listener> = {
        let p = UnsafeMutablePointer<zwp_primary_selection_offer_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_primary_selection_offer_v1_listener())
        p.pointee.offer = offer_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_primary_selection_offer_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ZwpPrimarySelectionOfferV1Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ZwpPrimarySelectionOfferV1Events
    }

    private static let offer_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafePointer<CChar>?) -> Void = { data, proxy, mime_type in
        guard let data, let proxy, let h = handler(data) else { return }
        h.offer(proxy, mime_type: mime_type)
    }
}
