// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_primary_selection_device_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwpPrimarySelectionDeviceV1Events: AnyObject {
    func dataOffer(_ proxy: OpaquePointer, offer: OpaquePointer?)
    func selection(_ proxy: OpaquePointer, id: OpaquePointer?)
}

public enum ZwpPrimarySelectionDeviceV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_primary_selection_device_v1_listener> = {
        let p = UnsafeMutablePointer<zwp_primary_selection_device_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_primary_selection_device_v1_listener())
        p.pointee.data_offer = dataOffer_impl
        p.pointee.selection = selection_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_primary_selection_device_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwpPrimarySelectionDeviceV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwpPrimarySelectionDeviceV1Events
    }

    private static let dataOffer_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, offer in
        guard let data, let proxy, let h = handler(data) else { return }
        h.dataOffer(proxy, offer: offer)
    }
    private static let selection_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.selection(proxy, id: id)
    }
}
