// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_tablet_seat_v2: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ZwpTabletSeatV2Events: AnyObject {
    func tabletAdded(_ proxy: OpaquePointer, id: OpaquePointer?)
    func toolAdded(_ proxy: OpaquePointer, id: OpaquePointer?)
    func padAdded(_ proxy: OpaquePointer, id: OpaquePointer?)
}

public enum ZwpTabletSeatV2Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_tablet_seat_v2_listener> = {
        let p = UnsafeMutablePointer<zwp_tablet_seat_v2_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_tablet_seat_v2_listener())
        p.pointee.tablet_added = tabletAdded_impl
        p.pointee.tool_added = toolAdded_impl
        p.pointee.pad_added = padAdded_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_tablet_seat_v2_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ZwpTabletSeatV2Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ZwpTabletSeatV2Events
    }

    private static let tabletAdded_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.tabletAdded(proxy, id: id)
    }
    private static let toolAdded_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.toolAdded(proxy, id: id)
    }
    private static let padAdded_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, id in
        guard let data, let proxy, let h = handler(data) else { return }
        h.padAdded(proxy, id: id)
    }
}
