// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_tablet_pad_v2: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwpTabletPadV2Events: AnyObject {
    func group(_ proxy: OpaquePointer, pad_group: OpaquePointer?)
    func path(_ proxy: OpaquePointer, path: UnsafePointer<CChar>?)
    func buttons(_ proxy: OpaquePointer, buttons: UInt32)
    func done(_ proxy: OpaquePointer)
    func button(_ proxy: OpaquePointer, time: UInt32, button: UInt32, state: UInt32)
    func enter(_ proxy: OpaquePointer, serial: UInt32, tablet: OpaquePointer?, surface: OpaquePointer?)
    func leave(_ proxy: OpaquePointer, serial: UInt32, surface: OpaquePointer?)
    func removed(_ proxy: OpaquePointer)
}

public enum ZwpTabletPadV2Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_tablet_pad_v2_listener> = {
        let p = UnsafeMutablePointer<zwp_tablet_pad_v2_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_tablet_pad_v2_listener())
        p.pointee.group = group_impl
        p.pointee.path = path_impl
        p.pointee.buttons = buttons_impl
        p.pointee.done = done_impl
        p.pointee.button = button_impl
        p.pointee.enter = enter_impl
        p.pointee.leave = leave_impl
        p.pointee.removed = removed_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_tablet_pad_v2_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwpTabletPadV2Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwpTabletPadV2Events
    }

    private static let group_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, pad_group in
        guard let data, let proxy, let h = handler(data) else { return }
        h.group(proxy, pad_group: pad_group)
    }
    private static let path_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafePointer<CChar>?) -> Void = { data, proxy, path in
        guard let data, let proxy, let h = handler(data) else { return }
        h.path(proxy, path: path)
    }
    private static let buttons_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, buttons in
        guard let data, let proxy, let h = handler(data) else { return }
        h.buttons(proxy, buttons: buttons)
    }
    private static let done_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.done(proxy)
    }
    private static let button_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32, UInt32) -> Void = { data, proxy, time, button, state in
        guard let data, let proxy, let h = handler(data) else { return }
        h.button(proxy, time: time, button: button, state: state)
    }
    private static let enter_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, OpaquePointer?, OpaquePointer?) -> Void = { data, proxy, serial, tablet, surface in
        guard let data, let proxy, let h = handler(data) else { return }
        h.enter(proxy, serial: serial, tablet: tablet, surface: surface)
    }
    private static let leave_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, OpaquePointer?) -> Void = { data, proxy, serial, surface in
        guard let data, let proxy, let h = handler(data) else { return }
        h.leave(proxy, serial: serial, surface: surface)
    }
    private static let removed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.removed(proxy)
    }
}
