// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zwp_tablet_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZwpTabletV1Events: AnyObject {
    func name(_ proxy: OpaquePointer, name: UnsafePointer<CChar>?)
    func id(_ proxy: OpaquePointer, vid: UInt32, pid: UInt32)
    func path(_ proxy: OpaquePointer, path: UnsafePointer<CChar>?)
    func done(_ proxy: OpaquePointer)
    func removed(_ proxy: OpaquePointer)
}

public enum ZwpTabletV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zwp_tablet_v1_listener> = {
        let p = UnsafeMutablePointer<zwp_tablet_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zwp_tablet_v1_listener())
        p.pointee.name = name_impl
        p.pointee.id = id_impl
        p.pointee.path = path_impl
        p.pointee.done = done_impl
        p.pointee.removed = removed_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zwp_tablet_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZwpTabletV1Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZwpTabletV1Events
    }

    private static let name_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafePointer<CChar>?) -> Void = { data, proxy, name in
        guard let data, let proxy, let h = handler(data) else { return }
        h.name(proxy, name: name)
    }
    private static let id_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32, UInt32) -> Void = { data, proxy, vid, pid in
        guard let data, let proxy, let h = handler(data) else { return }
        h.id(proxy, vid: vid, pid: pid)
    }
    private static let path_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafePointer<CChar>?) -> Void = { data, proxy, path in
        guard let data, let proxy, let h = handler(data) else { return }
        h.path(proxy, path: path)
    }
    private static let done_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.done(proxy)
    }
    private static let removed_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?) -> Void = { data, proxy in
        guard let data, let proxy, let h = handler(data) else { return }
        h.removed(proxy)
    }
}
