// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zxdg_toplevel_decoration_v1: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ZxdgToplevelDecorationV1Events: AnyObject {
    func configure(_ proxy: OpaquePointer, mode: UInt32)
}

public enum ZxdgToplevelDecorationV1Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zxdg_toplevel_decoration_v1_listener> = {
        let p = UnsafeMutablePointer<zxdg_toplevel_decoration_v1_listener>.allocate(capacity: 1)
        p.initialize(to: zxdg_toplevel_decoration_v1_listener())
        p.pointee.configure = configure_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zxdg_toplevel_decoration_v1_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ZxdgToplevelDecorationV1Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ZxdgToplevelDecorationV1Events
    }

    private static let configure_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, mode in
        guard let data, let proxy, let h = handler(data) else { return }
        h.configure(proxy, mode: mode)
    }
}
