// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zxdg_exported_v2: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

public import WaylandClientC

public protocol ZxdgExportedV2Events: AnyObject {
    func handle(_ proxy: OpaquePointer, handle: UnsafePointer<CChar>?)
}

public enum ZxdgExportedV2Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zxdg_exported_v2_listener> = {
        let p = UnsafeMutablePointer<zxdg_exported_v2_listener>.allocate(capacity: 1)
        p.initialize(to: zxdg_exported_v2_listener())
        p.pointee.handle = handle_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zxdg_exported_v2_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> (any ZxdgExportedV2Events)? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? any ZxdgExportedV2Events
    }

    private static let handle_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UnsafePointer<CChar>?) -> Void = { data, proxy, handle in
        guard let data, let proxy, let h = handler(data) else { return }
        h.handle(proxy, handle: handle)
    }
}
