// Generated by SwiftWaylandGen. Do not edit.
//
// Typed client dispatch for zxdg_surface_v6: a handler protocol (one method per event), the
// libwayland listener + owner recovery + arg marshalling, and an addListener that wires it.

import WaylandClientC

public protocol ZxdgSurfaceV6Events: AnyObject {
    func configure(_ proxy: OpaquePointer, serial: UInt32)
}

public enum ZxdgSurfaceV6Client {
    public nonisolated(unsafe) static let listener: UnsafeMutablePointer<zxdg_surface_v6_listener> = {
        let p = UnsafeMutablePointer<zxdg_surface_v6_listener>.allocate(capacity: 1)
        p.initialize(to: zxdg_surface_v6_listener())
        p.pointee.configure = configure_impl
        return p
    }()

    /// Wire the listener to a proxy. The owner is borrowed (unretained) — the caller must
    /// keep it alive for the proxy's lifetime, matching libwayland's user_data contract.
    @discardableResult
    public static func addListener(_ proxy: OpaquePointer, owner: AnyObject) -> Int32 {
        zxdg_surface_v6_add_listener(proxy, listener, Unmanaged.passUnretained(owner).toOpaque())
    }

    private static func handler(_ data: UnsafeMutableRawPointer) -> ZxdgSurfaceV6Events? {
        Unmanaged<AnyObject>.fromOpaque(data).takeUnretainedValue() as? ZxdgSurfaceV6Events
    }

    private static let configure_impl: @convention(c) (UnsafeMutableRawPointer?, OpaquePointer?, UInt32) -> Void = { data, proxy, serial in
        guard let data, let proxy, let h = handler(data) else { return }
        h.configure(proxy, serial: serial)
    }
}
