set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION "$ENV{NUCLEUS_ANDROID_API_LEVEL}")
set(CMAKE_ANDROID_ARCH_ABI "$ENV{NUCLEUS_ANDROID_ABI}")
set(CMAKE_ANDROID_NDK "$ENV{ANDROID_NDK_HOME}")
set(CMAKE_SYSROOT
    "$ENV{ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")

set(CMAKE_C_COMPILER /usr/local/bin/nucleus-android-clang)
set(CMAKE_CXX_COMPILER /usr/local/bin/nucleus-android-clang++)
set(CMAKE_AR /usr/bin/llvm-ar)
set(CMAKE_RANLIB /usr/bin/llvm-ranlib)
set(CMAKE_STRIP /usr/bin/llvm-strip)
set(CMAKE_NM /usr/bin/llvm-nm)
set(CMAKE_OBJCOPY /usr/bin/llvm-objcopy)
set(CMAKE_OBJDUMP /usr/bin/llvm-objdump)
set(CMAKE_READELF /usr/bin/llvm-readelf)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
