import ArgumentParser
import Foundation
import SystemPackage

enum ColliderSkillDocumentation {
    static let root = ".agents/skills/collider"

    static func documents() throws -> [String: Data] {
        let tool = try JSONDecoder().decode(
            ToolInfo.self,
            from: Data(ColliderCommand._dumpHelp().utf8))
        return [
            "SKILL.md": Data((skill + "\n").utf8),
            "agents/openai.yaml": Data((agentMetadata + "\n").utf8),
            "references/commands.md": Data(commandReference(tool.command).utf8),
        ]
    }

    static func write(to repositoryRoot: FilePath) throws {
        let destination = URL(
            fileURLWithPath: repositoryRoot.appending(root).string,
            isDirectory: true)
        for (relativePath, contents) in try documents() {
            let output = destination.appendingPathComponent(relativePath)
            try FileManager.default.createDirectory(
                at: output.deletingLastPathComponent(),
                withIntermediateDirectories: true)
            try contents.write(to: output, options: .atomic)
        }
    }

    private static let skill = """
        ---
        name: collider
        description: Build, test, inspect, and operate the Nucleus repository with its Collider CLI. Use for Nucleus bootstrap, component builds and tests, task-graph inspection, run logs, cache maintenance, SDK generation, and Android-image work.
        ---

        # Use Collider

        Read the repository `AGENTS.md` before changing code or running a workflow.

        1. On a fresh clone, run `./collider-setup.sh` once to provision dependencies and install the `collider` launcher.
        2. After setup, invoke `collider` from anywhere inside the clone. Never invoke the built executable directly and never source `tools/host-env.sh` for normal Collider usage.
        3. Select the narrowest component or task surface that satisfies the request. Use `--dry-run` before an expensive build when task selection or cache state is uncertain.
        4. Let Collider own Apple-container creation, persistent workspaces, cancellation, logs, and cleanup. Do not replace its Swift container API path with `container` CLI commands.
        5. Keep container actions offline. Host-side Collider actions own downloads and caches; retry an intermittent host download instead of reducing package-manager concurrency or enabling container networking.
        6. Inspect durable execution state with `collider runs` and `collider logs`; use the run or task log named by a failure before changing behavior.
        7. Preserve the build graph's incremental contract. Use `--rebuild` only when the user requests a forced rebuild or the declared outputs cannot establish the required state.

        Read [references/commands.md](references/commands.md) when exact command, argument, option, or subcommand syntax is needed. That reference is generated from Swift Argument Parser's structured representation of the current Collider command tree.

        Regenerate this skill after changing Collider command grammar:

        ```sh
        collider skill generate
        ```

        Do not edit generated files under `.agents/skills/collider` by hand. Change `ColliderSkillDocumentation` and regenerate them.
        """

    private static let agentMetadata = """
        interface:
          display_name: "Collider"
          short_description: "Build, test, and operate Nucleus with Collider"
          default_prompt: "Use $collider to build or test the appropriate Nucleus component."
        """

    private static func commandReference(_ rootCommand: CommandInfo) -> String {
        var sections = [
            "# Collider command reference",
            "",
            "Generated from the current \(platformName) Swift Argument Parser command tree. Do not edit this file by hand.",
            "",
        ]
        appendCommand(rootCommand, path: [], to: &sections)
        return sections.joined(separator: "\n") + "\n"
    }

    private static var platformName: String {
        #if os(macOS)
        "macOS"
        #elseif os(Linux)
        "Linux"
        #else
        "host"
        #endif
    }

    private static func appendCommand(
        _ command: CommandInfo,
        path: [String],
        to sections: inout [String]
    ) {
        guard command.shouldDisplay ?? true else { return }
        let commandPath = path + [command.commandName]
        sections.append("## `\(commandPath.joined(separator: " "))`")
        sections.append("")
        if let abstract = command.abstract, !abstract.isEmpty {
            sections.append(markdownText(abstract))
            sections.append("")
        }
        if let discussion = command.discussion, !discussion.isEmpty {
            sections.append(markdownText(discussion))
            sections.append("")
        }
        sections.append("Usage: `\(usage(command, path: commandPath))`")
        sections.append("")

        let arguments = (command.arguments ?? []).filter {
            $0.shouldDisplay ?? true
        }
        if !arguments.isEmpty {
            sections.append("Arguments and options:")
            sections.append("")
            for argument in arguments {
                sections.append("- \(argumentReference(argument))")
            }
            sections.append("")
        }

        let subcommands = (command.subcommands ?? []).filter {
            $0.shouldDisplay ?? true
        }
        if !subcommands.isEmpty {
            sections.append("Subcommands:")
            sections.append("")
            for subcommand in subcommands {
                let description = subcommand.abstract.map(markdownText) ?? ""
                sections.append(
                    "- `\(subcommand.commandName)`"
                        + (description.isEmpty ? "" : ": \(description)"))
            }
            sections.append("")
        }

        for subcommand in subcommands {
            appendCommand(subcommand, path: commandPath, to: &sections)
        }
    }

    private static func usage(_ command: CommandInfo, path: [String]) -> String {
        var fields = [path.joined(separator: " ")]
        fields += (command.arguments ?? []).compactMap(usageField)
        if !(command.subcommands ?? []).isEmpty {
            fields.append("<subcommand>")
        }
        return fields.joined(separator: " ")
    }

    private static func usageField(_ argument: ArgumentInfo) -> String? {
        guard argument.shouldDisplay ?? true else { return nil }
        let value = argument.valueName.map { "<\($0)>" }
        let field: String
        switch argument.kind {
        case "positional":
            field = value ?? "<value>"
        case "option":
            field = [preferredName(argument), value].compactMap { $0 }.joined(
                separator: " ")
        case "flag":
            field = preferredName(argument)
        default:
            return nil
        }
        let repeated = argument.isRepeating == true ? "..." : ""
        return argument.isOptional == true
            ? "[\(field)\(repeated)]"
            : "\(field)\(repeated)"
    }

    private static func argumentReference(_ argument: ArgumentInfo) -> String {
        let names: String
        if argument.kind == "positional" {
            names = "`<\(argument.valueName ?? "value")>`"
        } else {
            let rendered = (argument.names ?? []).map { name in
                let prefix = name.kind == "long" ? "--" : "-"
                return "`\(prefix)\(name.name)`"
            }
            names =
                rendered.joined(separator: ", ")
                + (argument.kind == "option"
                    ? " `<\(argument.valueName ?? "value")>`" : "")
        }
        var details: [String] = []
        if let abstract = argument.abstract, !abstract.isEmpty {
            details.append(markdownText(abstract))
        }
        if let values = argument.allValues, !values.isEmpty {
            details.append("values: \(values.map { "`\($0)`" }.joined(separator: ", "))")
        }
        if let defaultValue = argument.defaultValue, !defaultValue.isEmpty {
            details.append("default: `\(defaultValue)`")
        }
        return names + (details.isEmpty ? "" : " — " + details.joined(separator: "; "))
    }

    private static func preferredName(_ argument: ArgumentInfo) -> String {
        guard let name = argument.preferredName else { return "<option>" }
        return (name.kind == "long" ? "--" : "-") + name.name
    }

    private static func markdownText(_ value: String) -> String {
        value.replacingOccurrences(of: "\n", with: " ")
    }
}

private struct ToolInfo: Decodable {
    let command: CommandInfo
}

private struct CommandInfo: Decodable {
    let commandName: String
    let shouldDisplay: Bool?
    let abstract: String?
    let discussion: String?
    let subcommands: [CommandInfo]?
    let arguments: [ArgumentInfo]?
}

private struct ArgumentInfo: Decodable {
    struct Name: Decodable {
        let kind: String
        let name: String
    }

    let kind: String
    let shouldDisplay: Bool?
    let isOptional: Bool?
    let isRepeating: Bool?
    let names: [Name]?
    let preferredName: Name?
    let valueName: String?
    let defaultValue: String?
    let allValues: [String]?
    let abstract: String?
}
