/* Generated by SwiftWaylandGen (swiftpm/tools/SwiftWaylandGen). Do not edit.
 *
 * Façades over libwayland's own server headers for decls the Swift clang importer
 * cannot express directly. libwayland's structs and event senders
 * are consumed from Swift unchanged; this header adds only the interface-descriptor accessors,
 * the wl_fixed helpers, and the request-vtable typedefs.
 *
 * The included protocols are the selected set plus their transitive interface-dependency
 * closure (e.g. cursor-shape pulls in tablet, whose interface it references).
 */
#ifndef WAYLANDSERVERC_H
#define WAYLANDSERVERC_H

#include <wayland-server.h>

#define namespace swift_wayland_wl_kw_namespace
#define export swift_wayland_wl_kw_export
#define import swift_wayland_wl_kw_import
#define class swift_wayland_wl_kw_class
#define new swift_wayland_wl_kw_new
#define delete swift_wayland_wl_kw_delete
#define template swift_wayland_wl_kw_template
#define operator swift_wayland_wl_kw_operator
#define this swift_wayland_wl_kw_this
#define private swift_wayland_wl_kw_private
#define public swift_wayland_wl_kw_public
#define protected swift_wayland_wl_kw_protected
#define virtual swift_wayland_wl_kw_virtual
#define friend swift_wayland_wl_kw_friend
#define typename swift_wayland_wl_kw_typename
#define register swift_wayland_wl_kw_register

#include "blur-server-protocol.h"
#include "appmenu-server-protocol.h"
#include "wlr_foreign_toplevel_management_unstable_v1-server-protocol.h"
#include "wlr_gamma_control_unstable_v1-server-protocol.h"
#include "wlr_layer_shell_unstable_v1-server-protocol.h"
#include "wlr_output_management_unstable_v1-server-protocol.h"
#include "wlr_screencopy_unstable_v1-server-protocol.h"
#include "linux_dmabuf_v1-server-protocol.h"
#include "presentation_time-server-protocol.h"
#include "tablet_v2-server-protocol.h"
#include "viewporter-server-protocol.h"
#include "xdg_shell-server-protocol.h"
#include "alpha_modifier_v1-server-protocol.h"
#include "color_management_v1-server-protocol.h"
#include "color_representation_v1-server-protocol.h"
#include "commit_timing_v1-server-protocol.h"
#include "content_type_v1-server-protocol.h"
#include "cursor_shape_v1-server-protocol.h"
#include "drm_lease_v1-server-protocol.h"
#include "ext_background_effect_v1-server-protocol.h"
#include "ext_data_control_v1-server-protocol.h"
#include "ext_foreign_toplevel_list_v1-server-protocol.h"
#include "ext_idle_notify_v1-server-protocol.h"
#include "ext_image_capture_source_v1-server-protocol.h"
#include "ext_image_copy_capture_v1-server-protocol.h"
#include "ext_session_lock_v1-server-protocol.h"
#include "ext_transient_seat_v1-server-protocol.h"
#include "ext_workspace_v1-server-protocol.h"
#include "fifo_v1-server-protocol.h"
#include "fractional_scale_v1-server-protocol.h"
#include "linux_drm_syncobj_v1-server-protocol.h"
#include "pointer_warp_v1-server-protocol.h"
#include "security_context_v1-server-protocol.h"
#include "single_pixel_buffer_v1-server-protocol.h"
#include "tearing_control_v1-server-protocol.h"
#include "xdg_activation_v1-server-protocol.h"
#include "xdg_dialog_v1-server-protocol.h"
#include "xdg_session_management_v1-server-protocol.h"
#include "xdg_system_bell_v1-server-protocol.h"
#include "xdg_toplevel_drag_v1-server-protocol.h"
#include "xdg_toplevel_icon_v1-server-protocol.h"
#include "xdg_toplevel_tag_v1-server-protocol.h"
#include "xwayland_shell_v1-server-protocol.h"
#include "fullscreen_shell_unstable_v1-server-protocol.h"
#include "idle_inhibit_unstable_v1-server-protocol.h"
#include "input_method_unstable_v1-server-protocol.h"
#include "input_timestamps_unstable_v1-server-protocol.h"
#include "keyboard_shortcuts_inhibit_unstable_v1-server-protocol.h"
#include "zwp_linux_explicit_synchronization_unstable_v1-server-protocol.h"
#include "pointer_constraints_unstable_v1-server-protocol.h"
#include "pointer_gestures_unstable_v1-server-protocol.h"
#include "wp_primary_selection_unstable_v1-server-protocol.h"
#include "relative_pointer_unstable_v1-server-protocol.h"
#include "tablet_unstable_v1-server-protocol.h"
#include "text_input_unstable_v1-server-protocol.h"
#include "text_input_unstable_v3-server-protocol.h"
#include "xdg_decoration_unstable_v1-server-protocol.h"
#include "xdg_foreign_unstable_v1-server-protocol.h"
#include "xdg_foreign_unstable_v2-server-protocol.h"
#include "xdg_output_unstable_v1-server-protocol.h"
#include "xdg_shell_unstable_v6-server-protocol.h"
#include "xwayland_keyboard_grab_unstable_v1-server-protocol.h"

#undef namespace
#undef export
#undef import
#undef class
#undef new
#undef delete
#undef template
#undef operator
#undef this
#undef private
#undef public
#undef protected
#undef virtual
#undef friend
#undef typename
#undef register


/* Variadic/macro façades: non-variadic signatures Swift can import. */
#include <stdlib.h>

/* wl_resource_post_error is variadic; expose a plain message form. The message is passed
 * through "%s" so caller text is never a format string. */
static inline void swift_wayland_resource_post_error(struct wl_resource *resource,
                                               uint32_t code, const char *msg) {
    wl_resource_post_error(resource, code, "%s", msg);
}

/* A destroy listener with one opaque owner slot, used by Swift to turn a
 * cross-request wl_resource borrow into a checked live reference. */
struct swift_wayland_resource_lifetime_listener {
    struct wl_listener listener;
    void *owner;
};

static inline struct swift_wayland_resource_lifetime_listener *
swift_wayland_resource_lifetime_listener_create(
    void *owner, void (*notify)(struct wl_listener *, void *)) {
    struct swift_wayland_resource_lifetime_listener *box =
        (struct swift_wayland_resource_lifetime_listener *)calloc(1, sizeof(*box));
    if (!box) return NULL;
    box->listener.notify = notify;
    box->owner = owner;
    return box;
}

static inline void swift_wayland_resource_lifetime_listener_attach(
    struct swift_wayland_resource_lifetime_listener *box,
    struct wl_resource *resource) {
    wl_resource_add_destroy_listener(resource, &box->listener);
}

static inline void *swift_wayland_resource_lifetime_listener_owner(
    struct wl_listener *listener) {
    struct swift_wayland_resource_lifetime_listener *box =
        wl_container_of(listener, box, listener);
    return box->owner;
}

static inline struct swift_wayland_resource_lifetime_listener *
swift_wayland_resource_lifetime_listener_box(struct wl_listener *listener) {
    struct swift_wayland_resource_lifetime_listener *box =
        wl_container_of(listener, box, listener);
    return box;
}

static inline void swift_wayland_resource_lifetime_listener_destroy(
    struct swift_wayland_resource_lifetime_listener *box) {
    if (!box) return;
    wl_list_remove(&box->listener.link);
    free(box);
}
/* wl_fixed_t <-> double. The wl_fixed_* inlines use a union type-pun the Swift clang
 * importer may decline to import; these plain wrappers always do. */
static inline wl_fixed_t swift_wayland_fixed_from_double(double d) { return wl_fixed_from_double(d); }
static inline double swift_wayland_fixed_to_double(wl_fixed_t f) { return wl_fixed_to_double(f); }


/* Interface-descriptor accessors — the client binds/creates by &<name>_interface; the server
 * reads them for globals. Expose each as a plain accessor so Swift gets a clean pointer. */
static inline const struct wl_interface *swift_wayland_iface_wl_display(void) { return &wl_display_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_registry(void) { return &wl_registry_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_callback(void) { return &wl_callback_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_compositor(void) { return &wl_compositor_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_shm_pool(void) { return &wl_shm_pool_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_shm(void) { return &wl_shm_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_buffer(void) { return &wl_buffer_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_data_offer(void) { return &wl_data_offer_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_data_source(void) { return &wl_data_source_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_data_device(void) { return &wl_data_device_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_data_device_manager(void) { return &wl_data_device_manager_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_shell(void) { return &wl_shell_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_shell_surface(void) { return &wl_shell_surface_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_surface(void) { return &wl_surface_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_seat(void) { return &wl_seat_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_pointer(void) { return &wl_pointer_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_keyboard(void) { return &wl_keyboard_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_touch(void) { return &wl_touch_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_output(void) { return &wl_output_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_region(void) { return &wl_region_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_subcompositor(void) { return &wl_subcompositor_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_subsurface(void) { return &wl_subsurface_interface; }
static inline const struct wl_interface *swift_wayland_iface_wl_fixes(void) { return &wl_fixes_interface; }
static inline const struct wl_interface *swift_wayland_iface_org_kde_kwin_blur_manager(void) { return &org_kde_kwin_blur_manager_interface; }
static inline const struct wl_interface *swift_wayland_iface_org_kde_kwin_blur(void) { return &org_kde_kwin_blur_interface; }
static inline const struct wl_interface *swift_wayland_iface_org_kde_kwin_appmenu_manager(void) { return &org_kde_kwin_appmenu_manager_interface; }
static inline const struct wl_interface *swift_wayland_iface_org_kde_kwin_appmenu(void) { return &org_kde_kwin_appmenu_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_foreign_toplevel_manager_v1(void) { return &zwlr_foreign_toplevel_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_foreign_toplevel_handle_v1(void) { return &zwlr_foreign_toplevel_handle_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_gamma_control_manager_v1(void) { return &zwlr_gamma_control_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_gamma_control_v1(void) { return &zwlr_gamma_control_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_layer_shell_v1(void) { return &zwlr_layer_shell_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_layer_surface_v1(void) { return &zwlr_layer_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_output_manager_v1(void) { return &zwlr_output_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_output_head_v1(void) { return &zwlr_output_head_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_output_mode_v1(void) { return &zwlr_output_mode_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_output_configuration_v1(void) { return &zwlr_output_configuration_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_output_configuration_head_v1(void) { return &zwlr_output_configuration_head_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_screencopy_manager_v1(void) { return &zwlr_screencopy_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwlr_screencopy_frame_v1(void) { return &zwlr_screencopy_frame_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_dmabuf_v1(void) { return &zwp_linux_dmabuf_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_buffer_params_v1(void) { return &zwp_linux_buffer_params_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_dmabuf_feedback_v1(void) { return &zwp_linux_dmabuf_feedback_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_presentation(void) { return &wp_presentation_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_presentation_feedback(void) { return &wp_presentation_feedback_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_manager_v2(void) { return &zwp_tablet_manager_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_seat_v2(void) { return &zwp_tablet_seat_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_tool_v2(void) { return &zwp_tablet_tool_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_v2(void) { return &zwp_tablet_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_pad_ring_v2(void) { return &zwp_tablet_pad_ring_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_pad_strip_v2(void) { return &zwp_tablet_pad_strip_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_pad_group_v2(void) { return &zwp_tablet_pad_group_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_pad_v2(void) { return &zwp_tablet_pad_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_pad_dial_v2(void) { return &zwp_tablet_pad_dial_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_viewporter(void) { return &wp_viewporter_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_viewport(void) { return &wp_viewport_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_wm_base(void) { return &xdg_wm_base_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_positioner(void) { return &xdg_positioner_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_surface(void) { return &xdg_surface_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel(void) { return &xdg_toplevel_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_popup(void) { return &xdg_popup_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_alpha_modifier_v1(void) { return &wp_alpha_modifier_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_alpha_modifier_surface_v1(void) { return &wp_alpha_modifier_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_manager_v1(void) { return &wp_color_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_management_output_v1(void) { return &wp_color_management_output_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_management_surface_v1(void) { return &wp_color_management_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_management_surface_feedback_v1(void) { return &wp_color_management_surface_feedback_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_image_description_creator_icc_v1(void) { return &wp_image_description_creator_icc_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_image_description_creator_params_v1(void) { return &wp_image_description_creator_params_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_image_description_v1(void) { return &wp_image_description_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_image_description_info_v1(void) { return &wp_image_description_info_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_image_description_reference_v1(void) { return &wp_image_description_reference_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_representation_manager_v1(void) { return &wp_color_representation_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_color_representation_surface_v1(void) { return &wp_color_representation_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_commit_timing_manager_v1(void) { return &wp_commit_timing_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_commit_timer_v1(void) { return &wp_commit_timer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_content_type_manager_v1(void) { return &wp_content_type_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_content_type_v1(void) { return &wp_content_type_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_cursor_shape_manager_v1(void) { return &wp_cursor_shape_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_cursor_shape_device_v1(void) { return &wp_cursor_shape_device_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_drm_lease_device_v1(void) { return &wp_drm_lease_device_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_drm_lease_connector_v1(void) { return &wp_drm_lease_connector_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_drm_lease_request_v1(void) { return &wp_drm_lease_request_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_drm_lease_v1(void) { return &wp_drm_lease_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_background_effect_manager_v1(void) { return &ext_background_effect_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_background_effect_surface_v1(void) { return &ext_background_effect_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_data_control_manager_v1(void) { return &ext_data_control_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_data_control_device_v1(void) { return &ext_data_control_device_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_data_control_source_v1(void) { return &ext_data_control_source_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_data_control_offer_v1(void) { return &ext_data_control_offer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_foreign_toplevel_list_v1(void) { return &ext_foreign_toplevel_list_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_foreign_toplevel_handle_v1(void) { return &ext_foreign_toplevel_handle_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_idle_notifier_v1(void) { return &ext_idle_notifier_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_idle_notification_v1(void) { return &ext_idle_notification_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_image_capture_source_v1(void) { return &ext_image_capture_source_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_output_image_capture_source_manager_v1(void) { return &ext_output_image_capture_source_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_foreign_toplevel_image_capture_source_manager_v1(void) { return &ext_foreign_toplevel_image_capture_source_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_image_copy_capture_manager_v1(void) { return &ext_image_copy_capture_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_image_copy_capture_session_v1(void) { return &ext_image_copy_capture_session_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_image_copy_capture_frame_v1(void) { return &ext_image_copy_capture_frame_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_image_copy_capture_cursor_session_v1(void) { return &ext_image_copy_capture_cursor_session_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_session_lock_manager_v1(void) { return &ext_session_lock_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_session_lock_v1(void) { return &ext_session_lock_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_session_lock_surface_v1(void) { return &ext_session_lock_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_transient_seat_manager_v1(void) { return &ext_transient_seat_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_transient_seat_v1(void) { return &ext_transient_seat_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_workspace_manager_v1(void) { return &ext_workspace_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_workspace_group_handle_v1(void) { return &ext_workspace_group_handle_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_ext_workspace_handle_v1(void) { return &ext_workspace_handle_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_fifo_manager_v1(void) { return &wp_fifo_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_fifo_v1(void) { return &wp_fifo_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_fractional_scale_manager_v1(void) { return &wp_fractional_scale_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_fractional_scale_v1(void) { return &wp_fractional_scale_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_linux_drm_syncobj_manager_v1(void) { return &wp_linux_drm_syncobj_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_linux_drm_syncobj_timeline_v1(void) { return &wp_linux_drm_syncobj_timeline_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_linux_drm_syncobj_surface_v1(void) { return &wp_linux_drm_syncobj_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_pointer_warp_v1(void) { return &wp_pointer_warp_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_security_context_manager_v1(void) { return &wp_security_context_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_security_context_v1(void) { return &wp_security_context_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_single_pixel_buffer_manager_v1(void) { return &wp_single_pixel_buffer_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_tearing_control_manager_v1(void) { return &wp_tearing_control_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_wp_tearing_control_v1(void) { return &wp_tearing_control_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_activation_v1(void) { return &xdg_activation_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_activation_token_v1(void) { return &xdg_activation_token_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_wm_dialog_v1(void) { return &xdg_wm_dialog_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_dialog_v1(void) { return &xdg_dialog_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_session_manager_v1(void) { return &xdg_session_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_session_v1(void) { return &xdg_session_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_session_v1(void) { return &xdg_toplevel_session_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_system_bell_v1(void) { return &xdg_system_bell_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_drag_manager_v1(void) { return &xdg_toplevel_drag_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_drag_v1(void) { return &xdg_toplevel_drag_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_icon_manager_v1(void) { return &xdg_toplevel_icon_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_icon_v1(void) { return &xdg_toplevel_icon_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xdg_toplevel_tag_manager_v1(void) { return &xdg_toplevel_tag_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xwayland_shell_v1(void) { return &xwayland_shell_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_xwayland_surface_v1(void) { return &xwayland_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_fullscreen_shell_v1(void) { return &zwp_fullscreen_shell_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_fullscreen_shell_mode_feedback_v1(void) { return &zwp_fullscreen_shell_mode_feedback_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_idle_inhibit_manager_v1(void) { return &zwp_idle_inhibit_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_idle_inhibitor_v1(void) { return &zwp_idle_inhibitor_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_method_context_v1(void) { return &zwp_input_method_context_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_method_v1(void) { return &zwp_input_method_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_panel_v1(void) { return &zwp_input_panel_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_panel_surface_v1(void) { return &zwp_input_panel_surface_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_timestamps_manager_v1(void) { return &zwp_input_timestamps_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_input_timestamps_v1(void) { return &zwp_input_timestamps_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_keyboard_shortcuts_inhibit_manager_v1(void) { return &zwp_keyboard_shortcuts_inhibit_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_keyboard_shortcuts_inhibitor_v1(void) { return &zwp_keyboard_shortcuts_inhibitor_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_explicit_synchronization_v1(void) { return &zwp_linux_explicit_synchronization_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_surface_synchronization_v1(void) { return &zwp_linux_surface_synchronization_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_linux_buffer_release_v1(void) { return &zwp_linux_buffer_release_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_pointer_constraints_v1(void) { return &zwp_pointer_constraints_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_locked_pointer_v1(void) { return &zwp_locked_pointer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_confined_pointer_v1(void) { return &zwp_confined_pointer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_pointer_gestures_v1(void) { return &zwp_pointer_gestures_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_pointer_gesture_swipe_v1(void) { return &zwp_pointer_gesture_swipe_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_pointer_gesture_pinch_v1(void) { return &zwp_pointer_gesture_pinch_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_pointer_gesture_hold_v1(void) { return &zwp_pointer_gesture_hold_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_primary_selection_device_manager_v1(void) { return &zwp_primary_selection_device_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_primary_selection_device_v1(void) { return &zwp_primary_selection_device_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_primary_selection_offer_v1(void) { return &zwp_primary_selection_offer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_primary_selection_source_v1(void) { return &zwp_primary_selection_source_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_relative_pointer_manager_v1(void) { return &zwp_relative_pointer_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_relative_pointer_v1(void) { return &zwp_relative_pointer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_manager_v1(void) { return &zwp_tablet_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_seat_v1(void) { return &zwp_tablet_seat_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_tool_v1(void) { return &zwp_tablet_tool_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_tablet_v1(void) { return &zwp_tablet_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_text_input_v1(void) { return &zwp_text_input_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_text_input_manager_v1(void) { return &zwp_text_input_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_text_input_v3(void) { return &zwp_text_input_v3_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_text_input_manager_v3(void) { return &zwp_text_input_manager_v3_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_decoration_manager_v1(void) { return &zxdg_decoration_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_toplevel_decoration_v1(void) { return &zxdg_toplevel_decoration_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_exporter_v1(void) { return &zxdg_exporter_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_importer_v1(void) { return &zxdg_importer_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_exported_v1(void) { return &zxdg_exported_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_imported_v1(void) { return &zxdg_imported_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_exporter_v2(void) { return &zxdg_exporter_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_importer_v2(void) { return &zxdg_importer_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_exported_v2(void) { return &zxdg_exported_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_imported_v2(void) { return &zxdg_imported_v2_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_output_manager_v1(void) { return &zxdg_output_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_output_v1(void) { return &zxdg_output_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_shell_v6(void) { return &zxdg_shell_v6_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_positioner_v6(void) { return &zxdg_positioner_v6_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_surface_v6(void) { return &zxdg_surface_v6_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_toplevel_v6(void) { return &zxdg_toplevel_v6_interface; }
static inline const struct wl_interface *swift_wayland_iface_zxdg_popup_v6(void) { return &zxdg_popup_v6_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_xwayland_keyboard_grab_manager_v1(void) { return &zwp_xwayland_keyboard_grab_manager_v1_interface; }
static inline const struct wl_interface *swift_wayland_iface_zwp_xwayland_keyboard_grab_v1(void) { return &zwp_xwayland_keyboard_grab_v1_interface; }

/* Request-handler vtable typedefs (non-colliding names for Swift). */
typedef struct wl_display_interface swift_wayland_wl_display_requests;
typedef struct wl_registry_interface swift_wayland_wl_registry_requests;
/*
 * The vendored core protocol may be newer than the distribution's generated
 * wayland-server-protocol.h. Keep the request-table ABI tied to the vendored
 * XML instead of importing an older system struct that is missing tail
 * requests (Wayland 1.25 adds wl_compositor.release and
 * wl_data_device_manager.release).
 */
typedef struct swift_wayland_wl_compositor_requests {
    void (*create_surface)(struct wl_client *, struct wl_resource *, uint32_t);
    void (*create_region)(struct wl_client *, struct wl_resource *, uint32_t);
    void (*release)(struct wl_client *, struct wl_resource *);
} swift_wayland_wl_compositor_requests;
typedef struct wl_shm_pool_interface swift_wayland_wl_shm_pool_requests;
typedef struct wl_shm_interface swift_wayland_wl_shm_requests;
typedef struct wl_buffer_interface swift_wayland_wl_buffer_requests;
typedef struct wl_data_offer_interface swift_wayland_wl_data_offer_requests;
typedef struct wl_data_source_interface swift_wayland_wl_data_source_requests;
typedef struct wl_data_device_interface swift_wayland_wl_data_device_requests;
typedef struct swift_wayland_wl_data_device_manager_requests {
    void (*create_data_source)(struct wl_client *, struct wl_resource *, uint32_t);
    void (*get_data_device)(struct wl_client *, struct wl_resource *, uint32_t,
                            struct wl_resource *);
    void (*release)(struct wl_client *, struct wl_resource *);
} swift_wayland_wl_data_device_manager_requests;
typedef struct wl_shell_interface swift_wayland_wl_shell_requests;
typedef struct wl_shell_surface_interface swift_wayland_wl_shell_surface_requests;
typedef struct swift_wayland_wl_surface_requests {
    void (*destroy)(struct wl_client *, struct wl_resource *);
    void (*attach)(struct wl_client *, struct wl_resource *, struct wl_resource *,
                   int32_t, int32_t);
    void (*damage)(struct wl_client *, struct wl_resource *, int32_t, int32_t,
                   int32_t, int32_t);
    void (*frame)(struct wl_client *, struct wl_resource *, uint32_t);
    void (*set_opaque_region)(struct wl_client *, struct wl_resource *,
                              struct wl_resource *);
    void (*set_input_region)(struct wl_client *, struct wl_resource *,
                             struct wl_resource *);
    void (*commit)(struct wl_client *, struct wl_resource *);
    void (*set_buffer_transform)(struct wl_client *, struct wl_resource *, int32_t);
    void (*set_buffer_scale)(struct wl_client *, struct wl_resource *, int32_t);
    void (*damage_buffer)(struct wl_client *, struct wl_resource *, int32_t, int32_t,
                          int32_t, int32_t);
    void (*offset)(struct wl_client *, struct wl_resource *, int32_t, int32_t);
    void (*get_release)(struct wl_client *, struct wl_resource *, uint32_t);
} swift_wayland_wl_surface_requests;
typedef struct wl_seat_interface swift_wayland_wl_seat_requests;
typedef struct wl_pointer_interface swift_wayland_wl_pointer_requests;
typedef struct wl_keyboard_interface swift_wayland_wl_keyboard_requests;
typedef struct wl_touch_interface swift_wayland_wl_touch_requests;
typedef struct wl_output_interface swift_wayland_wl_output_requests;
typedef struct wl_region_interface swift_wayland_wl_region_requests;
typedef struct wl_subcompositor_interface swift_wayland_wl_subcompositor_requests;
typedef struct wl_subsurface_interface swift_wayland_wl_subsurface_requests;
typedef struct wl_fixes_interface swift_wayland_wl_fixes_requests;
typedef struct org_kde_kwin_blur_manager_interface swift_wayland_org_kde_kwin_blur_manager_requests;
typedef struct org_kde_kwin_blur_interface swift_wayland_org_kde_kwin_blur_requests;
typedef struct org_kde_kwin_appmenu_manager_interface swift_wayland_org_kde_kwin_appmenu_manager_requests;
typedef struct org_kde_kwin_appmenu_interface swift_wayland_org_kde_kwin_appmenu_requests;
typedef struct zwlr_foreign_toplevel_manager_v1_interface swift_wayland_zwlr_foreign_toplevel_manager_v1_requests;
typedef struct zwlr_foreign_toplevel_handle_v1_interface swift_wayland_zwlr_foreign_toplevel_handle_v1_requests;
typedef struct zwlr_gamma_control_manager_v1_interface swift_wayland_zwlr_gamma_control_manager_v1_requests;
typedef struct zwlr_gamma_control_v1_interface swift_wayland_zwlr_gamma_control_v1_requests;
typedef struct zwlr_layer_shell_v1_interface swift_wayland_zwlr_layer_shell_v1_requests;
typedef struct zwlr_layer_surface_v1_interface swift_wayland_zwlr_layer_surface_v1_requests;
typedef struct zwlr_output_manager_v1_interface swift_wayland_zwlr_output_manager_v1_requests;
typedef struct zwlr_output_head_v1_interface swift_wayland_zwlr_output_head_v1_requests;
typedef struct zwlr_output_mode_v1_interface swift_wayland_zwlr_output_mode_v1_requests;
typedef struct zwlr_output_configuration_v1_interface swift_wayland_zwlr_output_configuration_v1_requests;
typedef struct zwlr_output_configuration_head_v1_interface swift_wayland_zwlr_output_configuration_head_v1_requests;
typedef struct zwlr_screencopy_manager_v1_interface swift_wayland_zwlr_screencopy_manager_v1_requests;
typedef struct zwlr_screencopy_frame_v1_interface swift_wayland_zwlr_screencopy_frame_v1_requests;
typedef struct zwp_linux_dmabuf_v1_interface swift_wayland_zwp_linux_dmabuf_v1_requests;
typedef struct zwp_linux_buffer_params_v1_interface swift_wayland_zwp_linux_buffer_params_v1_requests;
typedef struct zwp_linux_dmabuf_feedback_v1_interface swift_wayland_zwp_linux_dmabuf_feedback_v1_requests;
typedef struct wp_presentation_interface swift_wayland_wp_presentation_requests;
typedef struct zwp_tablet_manager_v2_interface swift_wayland_zwp_tablet_manager_v2_requests;
typedef struct zwp_tablet_seat_v2_interface swift_wayland_zwp_tablet_seat_v2_requests;
typedef struct zwp_tablet_tool_v2_interface swift_wayland_zwp_tablet_tool_v2_requests;
typedef struct zwp_tablet_v2_interface swift_wayland_zwp_tablet_v2_requests;
typedef struct zwp_tablet_pad_ring_v2_interface swift_wayland_zwp_tablet_pad_ring_v2_requests;
typedef struct zwp_tablet_pad_strip_v2_interface swift_wayland_zwp_tablet_pad_strip_v2_requests;
typedef struct zwp_tablet_pad_group_v2_interface swift_wayland_zwp_tablet_pad_group_v2_requests;
typedef struct zwp_tablet_pad_v2_interface swift_wayland_zwp_tablet_pad_v2_requests;
typedef struct zwp_tablet_pad_dial_v2_interface swift_wayland_zwp_tablet_pad_dial_v2_requests;
typedef struct wp_viewporter_interface swift_wayland_wp_viewporter_requests;
typedef struct wp_viewport_interface swift_wayland_wp_viewport_requests;
typedef struct xdg_wm_base_interface swift_wayland_xdg_wm_base_requests;
typedef struct xdg_positioner_interface swift_wayland_xdg_positioner_requests;
typedef struct xdg_surface_interface swift_wayland_xdg_surface_requests;
typedef struct xdg_toplevel_interface swift_wayland_xdg_toplevel_requests;
typedef struct xdg_popup_interface swift_wayland_xdg_popup_requests;
typedef struct wp_alpha_modifier_v1_interface swift_wayland_wp_alpha_modifier_v1_requests;
typedef struct wp_alpha_modifier_surface_v1_interface swift_wayland_wp_alpha_modifier_surface_v1_requests;
typedef struct wp_color_manager_v1_interface swift_wayland_wp_color_manager_v1_requests;
typedef struct wp_color_management_output_v1_interface swift_wayland_wp_color_management_output_v1_requests;
typedef struct wp_color_management_surface_v1_interface swift_wayland_wp_color_management_surface_v1_requests;
typedef struct wp_color_management_surface_feedback_v1_interface swift_wayland_wp_color_management_surface_feedback_v1_requests;
typedef struct wp_image_description_creator_icc_v1_interface swift_wayland_wp_image_description_creator_icc_v1_requests;
typedef struct wp_image_description_creator_params_v1_interface swift_wayland_wp_image_description_creator_params_v1_requests;
typedef struct wp_image_description_v1_interface swift_wayland_wp_image_description_v1_requests;
typedef struct wp_image_description_reference_v1_interface swift_wayland_wp_image_description_reference_v1_requests;
typedef struct wp_color_representation_manager_v1_interface swift_wayland_wp_color_representation_manager_v1_requests;
typedef struct wp_color_representation_surface_v1_interface swift_wayland_wp_color_representation_surface_v1_requests;
typedef struct wp_commit_timing_manager_v1_interface swift_wayland_wp_commit_timing_manager_v1_requests;
typedef struct wp_commit_timer_v1_interface swift_wayland_wp_commit_timer_v1_requests;
typedef struct wp_content_type_manager_v1_interface swift_wayland_wp_content_type_manager_v1_requests;
typedef struct wp_content_type_v1_interface swift_wayland_wp_content_type_v1_requests;
typedef struct wp_cursor_shape_manager_v1_interface swift_wayland_wp_cursor_shape_manager_v1_requests;
typedef struct wp_cursor_shape_device_v1_interface swift_wayland_wp_cursor_shape_device_v1_requests;
typedef struct wp_drm_lease_device_v1_interface swift_wayland_wp_drm_lease_device_v1_requests;
typedef struct wp_drm_lease_connector_v1_interface swift_wayland_wp_drm_lease_connector_v1_requests;
typedef struct wp_drm_lease_request_v1_interface swift_wayland_wp_drm_lease_request_v1_requests;
typedef struct wp_drm_lease_v1_interface swift_wayland_wp_drm_lease_v1_requests;
typedef struct ext_background_effect_manager_v1_interface swift_wayland_ext_background_effect_manager_v1_requests;
typedef struct ext_background_effect_surface_v1_interface swift_wayland_ext_background_effect_surface_v1_requests;
typedef struct ext_data_control_manager_v1_interface swift_wayland_ext_data_control_manager_v1_requests;
typedef struct ext_data_control_device_v1_interface swift_wayland_ext_data_control_device_v1_requests;
typedef struct ext_data_control_source_v1_interface swift_wayland_ext_data_control_source_v1_requests;
typedef struct ext_data_control_offer_v1_interface swift_wayland_ext_data_control_offer_v1_requests;
typedef struct ext_foreign_toplevel_list_v1_interface swift_wayland_ext_foreign_toplevel_list_v1_requests;
typedef struct ext_foreign_toplevel_handle_v1_interface swift_wayland_ext_foreign_toplevel_handle_v1_requests;
typedef struct ext_idle_notifier_v1_interface swift_wayland_ext_idle_notifier_v1_requests;
typedef struct ext_idle_notification_v1_interface swift_wayland_ext_idle_notification_v1_requests;
typedef struct ext_image_capture_source_v1_interface swift_wayland_ext_image_capture_source_v1_requests;
typedef struct ext_output_image_capture_source_manager_v1_interface swift_wayland_ext_output_image_capture_source_manager_v1_requests;
typedef struct ext_foreign_toplevel_image_capture_source_manager_v1_interface swift_wayland_ext_foreign_toplevel_image_capture_source_manager_v1_requests;
typedef struct ext_image_copy_capture_manager_v1_interface swift_wayland_ext_image_copy_capture_manager_v1_requests;
typedef struct ext_image_copy_capture_session_v1_interface swift_wayland_ext_image_copy_capture_session_v1_requests;
typedef struct ext_image_copy_capture_frame_v1_interface swift_wayland_ext_image_copy_capture_frame_v1_requests;
typedef struct ext_image_copy_capture_cursor_session_v1_interface swift_wayland_ext_image_copy_capture_cursor_session_v1_requests;
typedef struct ext_session_lock_manager_v1_interface swift_wayland_ext_session_lock_manager_v1_requests;
typedef struct ext_session_lock_v1_interface swift_wayland_ext_session_lock_v1_requests;
typedef struct ext_session_lock_surface_v1_interface swift_wayland_ext_session_lock_surface_v1_requests;
typedef struct ext_transient_seat_manager_v1_interface swift_wayland_ext_transient_seat_manager_v1_requests;
typedef struct ext_transient_seat_v1_interface swift_wayland_ext_transient_seat_v1_requests;
typedef struct ext_workspace_manager_v1_interface swift_wayland_ext_workspace_manager_v1_requests;
typedef struct ext_workspace_group_handle_v1_interface swift_wayland_ext_workspace_group_handle_v1_requests;
typedef struct ext_workspace_handle_v1_interface swift_wayland_ext_workspace_handle_v1_requests;
typedef struct wp_fifo_manager_v1_interface swift_wayland_wp_fifo_manager_v1_requests;
typedef struct wp_fifo_v1_interface swift_wayland_wp_fifo_v1_requests;
typedef struct wp_fractional_scale_manager_v1_interface swift_wayland_wp_fractional_scale_manager_v1_requests;
typedef struct wp_fractional_scale_v1_interface swift_wayland_wp_fractional_scale_v1_requests;
typedef struct wp_linux_drm_syncobj_manager_v1_interface swift_wayland_wp_linux_drm_syncobj_manager_v1_requests;
typedef struct wp_linux_drm_syncobj_timeline_v1_interface swift_wayland_wp_linux_drm_syncobj_timeline_v1_requests;
typedef struct wp_linux_drm_syncobj_surface_v1_interface swift_wayland_wp_linux_drm_syncobj_surface_v1_requests;
typedef struct wp_pointer_warp_v1_interface swift_wayland_wp_pointer_warp_v1_requests;
typedef struct wp_security_context_manager_v1_interface swift_wayland_wp_security_context_manager_v1_requests;
typedef struct wp_security_context_v1_interface swift_wayland_wp_security_context_v1_requests;
typedef struct wp_single_pixel_buffer_manager_v1_interface swift_wayland_wp_single_pixel_buffer_manager_v1_requests;
typedef struct wp_tearing_control_manager_v1_interface swift_wayland_wp_tearing_control_manager_v1_requests;
typedef struct wp_tearing_control_v1_interface swift_wayland_wp_tearing_control_v1_requests;
typedef struct xdg_activation_v1_interface swift_wayland_xdg_activation_v1_requests;
typedef struct xdg_activation_token_v1_interface swift_wayland_xdg_activation_token_v1_requests;
typedef struct xdg_wm_dialog_v1_interface swift_wayland_xdg_wm_dialog_v1_requests;
typedef struct xdg_dialog_v1_interface swift_wayland_xdg_dialog_v1_requests;
typedef struct xdg_session_manager_v1_interface swift_wayland_xdg_session_manager_v1_requests;
typedef struct xdg_session_v1_interface swift_wayland_xdg_session_v1_requests;
typedef struct xdg_toplevel_session_v1_interface swift_wayland_xdg_toplevel_session_v1_requests;
typedef struct xdg_system_bell_v1_interface swift_wayland_xdg_system_bell_v1_requests;
typedef struct xdg_toplevel_drag_manager_v1_interface swift_wayland_xdg_toplevel_drag_manager_v1_requests;
typedef struct xdg_toplevel_drag_v1_interface swift_wayland_xdg_toplevel_drag_v1_requests;
typedef struct xdg_toplevel_icon_manager_v1_interface swift_wayland_xdg_toplevel_icon_manager_v1_requests;
typedef struct xdg_toplevel_icon_v1_interface swift_wayland_xdg_toplevel_icon_v1_requests;
typedef struct xdg_toplevel_tag_manager_v1_interface swift_wayland_xdg_toplevel_tag_manager_v1_requests;
typedef struct xwayland_shell_v1_interface swift_wayland_xwayland_shell_v1_requests;
typedef struct xwayland_surface_v1_interface swift_wayland_xwayland_surface_v1_requests;
typedef struct zwp_fullscreen_shell_v1_interface swift_wayland_zwp_fullscreen_shell_v1_requests;
typedef struct zwp_idle_inhibit_manager_v1_interface swift_wayland_zwp_idle_inhibit_manager_v1_requests;
typedef struct zwp_idle_inhibitor_v1_interface swift_wayland_zwp_idle_inhibitor_v1_requests;
typedef struct zwp_input_method_context_v1_interface swift_wayland_zwp_input_method_context_v1_requests;
typedef struct zwp_input_panel_v1_interface swift_wayland_zwp_input_panel_v1_requests;
typedef struct zwp_input_panel_surface_v1_interface swift_wayland_zwp_input_panel_surface_v1_requests;
typedef struct zwp_input_timestamps_manager_v1_interface swift_wayland_zwp_input_timestamps_manager_v1_requests;
typedef struct zwp_input_timestamps_v1_interface swift_wayland_zwp_input_timestamps_v1_requests;
typedef struct zwp_keyboard_shortcuts_inhibit_manager_v1_interface swift_wayland_zwp_keyboard_shortcuts_inhibit_manager_v1_requests;
typedef struct zwp_keyboard_shortcuts_inhibitor_v1_interface swift_wayland_zwp_keyboard_shortcuts_inhibitor_v1_requests;
typedef struct zwp_linux_explicit_synchronization_v1_interface swift_wayland_zwp_linux_explicit_synchronization_v1_requests;
typedef struct zwp_linux_surface_synchronization_v1_interface swift_wayland_zwp_linux_surface_synchronization_v1_requests;
typedef struct zwp_pointer_constraints_v1_interface swift_wayland_zwp_pointer_constraints_v1_requests;
typedef struct zwp_locked_pointer_v1_interface swift_wayland_zwp_locked_pointer_v1_requests;
typedef struct zwp_confined_pointer_v1_interface swift_wayland_zwp_confined_pointer_v1_requests;
typedef struct zwp_pointer_gestures_v1_interface swift_wayland_zwp_pointer_gestures_v1_requests;
typedef struct zwp_pointer_gesture_swipe_v1_interface swift_wayland_zwp_pointer_gesture_swipe_v1_requests;
typedef struct zwp_pointer_gesture_pinch_v1_interface swift_wayland_zwp_pointer_gesture_pinch_v1_requests;
typedef struct zwp_pointer_gesture_hold_v1_interface swift_wayland_zwp_pointer_gesture_hold_v1_requests;
typedef struct zwp_primary_selection_device_manager_v1_interface swift_wayland_zwp_primary_selection_device_manager_v1_requests;
typedef struct zwp_primary_selection_device_v1_interface swift_wayland_zwp_primary_selection_device_v1_requests;
typedef struct zwp_primary_selection_offer_v1_interface swift_wayland_zwp_primary_selection_offer_v1_requests;
typedef struct zwp_primary_selection_source_v1_interface swift_wayland_zwp_primary_selection_source_v1_requests;
typedef struct zwp_relative_pointer_manager_v1_interface swift_wayland_zwp_relative_pointer_manager_v1_requests;
typedef struct zwp_relative_pointer_v1_interface swift_wayland_zwp_relative_pointer_v1_requests;
typedef struct zwp_tablet_manager_v1_interface swift_wayland_zwp_tablet_manager_v1_requests;
typedef struct zwp_tablet_seat_v1_interface swift_wayland_zwp_tablet_seat_v1_requests;
typedef struct zwp_tablet_tool_v1_interface swift_wayland_zwp_tablet_tool_v1_requests;
typedef struct zwp_tablet_v1_interface swift_wayland_zwp_tablet_v1_requests;
typedef struct zwp_text_input_v1_interface swift_wayland_zwp_text_input_v1_requests;
typedef struct zwp_text_input_manager_v1_interface swift_wayland_zwp_text_input_manager_v1_requests;
typedef struct zwp_text_input_v3_interface swift_wayland_zwp_text_input_v3_requests;
typedef struct zwp_text_input_manager_v3_interface swift_wayland_zwp_text_input_manager_v3_requests;
typedef struct zxdg_decoration_manager_v1_interface swift_wayland_zxdg_decoration_manager_v1_requests;
typedef struct zxdg_toplevel_decoration_v1_interface swift_wayland_zxdg_toplevel_decoration_v1_requests;
typedef struct zxdg_exporter_v1_interface swift_wayland_zxdg_exporter_v1_requests;
typedef struct zxdg_importer_v1_interface swift_wayland_zxdg_importer_v1_requests;
typedef struct zxdg_exported_v1_interface swift_wayland_zxdg_exported_v1_requests;
typedef struct zxdg_imported_v1_interface swift_wayland_zxdg_imported_v1_requests;
typedef struct zxdg_exporter_v2_interface swift_wayland_zxdg_exporter_v2_requests;
typedef struct zxdg_importer_v2_interface swift_wayland_zxdg_importer_v2_requests;
typedef struct zxdg_exported_v2_interface swift_wayland_zxdg_exported_v2_requests;
typedef struct zxdg_imported_v2_interface swift_wayland_zxdg_imported_v2_requests;
typedef struct zxdg_output_manager_v1_interface swift_wayland_zxdg_output_manager_v1_requests;
typedef struct zxdg_output_v1_interface swift_wayland_zxdg_output_v1_requests;
typedef struct zxdg_shell_v6_interface swift_wayland_zxdg_shell_v6_requests;
typedef struct zxdg_positioner_v6_interface swift_wayland_zxdg_positioner_v6_requests;
typedef struct zxdg_surface_v6_interface swift_wayland_zxdg_surface_v6_requests;
typedef struct zxdg_toplevel_v6_interface swift_wayland_zxdg_toplevel_v6_requests;
typedef struct zxdg_popup_v6_interface swift_wayland_zxdg_popup_v6_requests;
typedef struct zwp_xwayland_keyboard_grab_manager_v1_interface swift_wayland_zwp_xwayland_keyboard_grab_manager_v1_requests;
typedef struct zwp_xwayland_keyboard_grab_v1_interface swift_wayland_zwp_xwayland_keyboard_grab_v1_requests;

#endif /* WAYLANDSERVERC_H */
